### ISSUE TITLE
Timeline skips events if `transportTimeline` array of events are not in ascending tick order

### ISSUE THREAD

**Issue by marcusstenbeck** [Tonejs/Tone.js#101]
I ran into this when I was making a step sequencer. Clicking around, checking the boxes to add and remove events from the timeline caused an event to appear in the wrong order in `transportTimeline`. Then, when the timeline is processed the event is skipped because the `timelineProgress` [is advanced](https://github.com/Tonejs/Tone.js/blob/d0d780fe45364358da34f5bf3754dc448487eff8/Tone/core/Transport.js#L235) to whatever the latest timeline event index was.

Commenting line [235 in Transport.js](https://github.com/Tonejs/Tone.js/blob/d0d780fe45364358da34f5bf3754dc448487eff8/Tone/core/Transport.js#L235) resolved the issue for me.

**Comment by marcusstenbeck** [comment]
I looked a bit closer at [`Transport.setTimeline()`](https://github.com/Tonejs/Tone.js/blob/d0d780fe45364358da34f5bf3754dc448487eff8/Tone/core/Transport.js#L427), and the problem might be that the event is attempted to be inserted at whatever index `timelineProgress` contains. If the transport is playing that index will be all over the place. It seems like changing `for(var i = timelineProgress, ...` to `for(var i = 0, ...` also fixes the issue.

**Comment by tambien** [comment]
I'm doing a little investigating right now. It seems possible that if you're adding a timeline event which is before the other timeline events it wouldn't be put in the right order which is why your second comment about changing the loop to start at 0 would fix this. 

Could you make a jsfiddle which illustrates the issue? A lot of this code has also been refactored/revamped in the latest version (which i'm going to release soon). so it'd be great to have a test case to see if this issue has been fixed in r6.

**Comment by tambien** [comment]
I'm going to close this issue for now since it's probably specific to the old Transport implementation and API. Please reopen if you find this issue still exists.
