### ISSUE TITLE
CtrlMarkov?

### ISSUE THREAD

**Issue by wcrtr** [Tonejs/Tone.js#1029]
**The feature you'd like**
Been reading through the release notes and can't find anything about CtrlMarkov being removed and would love to see it back!

**Any alternatives you've considered**
I don't know in the current documentation if CtrlMarkov has been replicated by any other feature.

**Additional context**
None

**Comment by japentaca** [comment]
I miss it

**Comment by tambien** [comment]
It isn't much code if you wanted to just pull it into your own project.

Here's the original module: https://github.com/Tonejs/Tone.js/blob/389ccf87229df47a1560b37896da8f4c28aea7bb/Tone/control/CtrlMarkov.js

At some point didn't feel like an important part of Tone.js since it does neither scheduling nor synthesis and was more related to generative music more generally. As a maintainer, i've realized that a tightly scoped feature set that works well is the best thing i can do with this library vs trying to jam in the most features.

**Comment by mediashock** [comment]
Why was this removed in the first place?
