### ISSUE TITLE
Improvement - Documentation for Transport

### ISSUE THREAD

**Issue by sfradkin** [Tonejs/Tone.js#104]
The documentation for Transport could be clarified a bit.  It's not immediately clear what the difference between schedule() and scheduleOnce() is other than scheduleOnce() will remove the scheduled event from the timeline after it is fired.

Also, I was a bit confused about the time argument.  I had tried using a future time that would have been a small bit of time away from the current time (e.g. current transport time was 12.5 and I scheduled an event for 13.0), but the event didn't fire until many seconds after it was expected.  However, when I used a now-relative time (+0.5) the event fired when I expected.  I was under the assumption that an event could be scheduled for a specific time in seconds.

**Comment by tambien** [comment]
Thanks for the comment. Timing in Tone is still a little complicated. There are two clock sources to manage, the Transport clock, (which is seekable, pausable, restartable and which the docs usually refer to as the "timeline"), and the Web Audio clock (which counts up from 0 and doesn't stop). This is definitely confusing and could use some more documentation, so i appreciate the issue. 

Maybe the docs should refer to one as `Time` and the other as `TimelineTime` or something like that to clarify when one is used over the other. I think updating the Transport and Event Classes wikis to make this clear would be a good thing too.

It's possible that your issue is that the Web Audio clock was at 12.5, but the Transport's timeline was at 0. And since `schedule` is relative to the Transport's clock, if you put in a value of 13 and then started the Transport, it would take 13 seconds before the event was fired. 

As far as `schedule` vs `scheduleOnce`, they are pretty much identical, except that, as you said, `scheduleOnce` will be removed after it's invoked. so it might be useful for events which you don't want to repeat or be recorded along the Transport's timeline. `schedule` is much more useful than `scheduleOnce`
