### ISSUE TITLE
Tone.Transport.now() - return Transport time

### ISSUE THREAD

**Issue by sfradkin** [Tonejs/Tone.js#106]
It would be nice if Tone.Transport.now() would return the Transport's time rather than the underlying time of the AudioContext.  It is useful to know the transport time for absolute scheduling of future events.

**Comment by tambien** [comment]
Thanks for the suggestion, but I think `Transport.now()` might be a little redundant since there are already two methods to get the Transport's current time: `Transport.position` and `Transport.ticks`. 

Plus, since everything scheduled along the transport is eventually converted into ticks, it might not be that useful to have the Transport's time in terms of seconds anyway. `Transport.toSeconds(Transport.ticks + "i")` would give you the elapsed time of the transport in seconds.

The easiest way would be to use now-relative timing: `Transport.toTicks("+18i")`. In cases where you want the Transport's time to do additional math or processing you could use Transport.ticks directly like: `Transport.schedule(callback, (Transport.ticks + 18) + "i")`.
