### ISSUE TITLE
Ableton Link Suport

### ISSUE THREAD

**Issue by f00b455** [Tonejs/Tone.js#1067]
**Ableton Link as Clock**
As Performer / LiveCoder i would like to sync with Ableton Live.
With Ableton Link implemented or interchangeable Clock implementation  would be very nice!

https://github.com/2bbb/node-abletonlink

Or does this not work because of browser restrictions?
I already implemented it in Orca (Electron Application)

**Comment by f00b455** [comment]
https://github.com/f00b455/Orca/blob/main/desktop/sources/scripts/clockAbletonLink.js

**Comment by tambien** [comment]
@f00b455 i don't think that this would work because Tone.js runs only in the browser and it seems like Ableton Link requires node.js. There might be a way to sync to Ableton with MIDI, but i think that'd be out of the scope of this library which is primarily focused on Web Audio scheduling / synthesis.
