### ISSUE TITLE
For some older Androids, try catch statements will have problems

### ISSUE THREAD

**Issue by liJie-wk** [Tonejs/Tone.js#1070]
1. try{}catch{} , There is a compatibility issue.

2. Change to try{}catch(e) {} and solve it

**Comment by tambien** [comment]
thanks for the suggestion, do you know if this sort of thing counts? 

https://github.com/Tonejs/Tone.js/blob/f34a963f1ba7fa760603b1360237d7792e373406/Tone/core/context/ToneAudioBuffer.ts#L72

if not, then i think all of the try/catch blocks take the `e` parameter (just did a quick search on the codebase).

**Comment by liJie-wk** [comment]
I'm sorry, but I don't quite understand what you mean.
Its error message goes like this.
![Snipaste_2022-04-29_11-58-57](https://user-images.githubusercontent.com/57932868/165895957-a8ec3a2e-5075-4716-8273-beddfd3cab54.png)

I changed all the try catches to this and that's fine
![微信图片_20220428194552](https://user-images.githubusercontent.com/57932868/165896247-602a5c3d-67a9-46e8-a037-e9b74ee95b45.png)

**Comment by tambien** [comment]
It's not in the Tone.js codebase, so it might be within a Tone.js dependency like standardized-audio-context. 

@chrisguttandin does this code look familiar to you?

**Comment by chrisguttandin** [comment]
Yes, this looks very familiar. I'm pretty sure it's coming from here: https://github.com/chrisguttandin/standardized-audio-context/blob/b1e93e093c57b247ce78c281854681de959b38a6/src/helpers/is-constructible.ts#L15.

Am I correct that standardized-audio-context gets bundled with Tone.js? I thought so, since the file shown in the screenshots above is named `Tone.js`. Maybe it's an option to transpile standardized-audio-context before it gets bundled.

I'm trying to publish standardized-audio-context in a recent version of the EcmaScript spec. Right now it's ES2019. My reasoning behind this was that transpiling down from ES2019 to -for example- ES2015 is always possible whereas the opposite is a challenge.

However I also want to change the way I publish packages once more to use the new exports property. But I'm not sure when I will have time to finally do that. Maybe this allows to publish different EcmaScript versions simultaneously.

**Comment by liJie-wk** [comment]
Older versions of android-system-webview aOlder versions of android-system-webview are not supported by some syntaxre not supported by some syntax
