### ISSUE TITLE
Unable to import tone

### ISSUE THREAD

**Issue by cryptozachary** [Tonejs/Tone.js#1089]
Hello All,

I've tried adding ./ or ../ to the import and it does not work. When adding the tone.js script directly to my html index file ,it works, however I do not have access to the tone object file in the window , which is what i really need. Pictures below
![1](https://user-images.githubusercontent.com/103056606/172956067-cebce4cc-0eaa-40d7-abbc-2ef93d0390ce.jpg)
![2](https://user-images.githubusercontent.com/103056606/172956070-dc22667f-5d59-45f8-9f84-65c5516ed032.jpg)
![3](https://user-images.githubusercontent.com/103056606/172956072-d18159e7-45fd-4b5e-b2d8-8af8df63d751.jpg)

**Comment by tambien** [comment]
I would recommend using a javascript bundler such as webpack, rollup or parcel. Plain javascript has a syntax for importing modules, ([more info here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)) but it comes with some caveats and complexities. So i find using a bundler to be the easiest and most compatible way to use Tone.js. 

If you want to continue with the module syntax, then you'll need to follow the recommendation of the error and probably do something like `import * as Tone from "./Tone.js"` instead of what you current have.
