### ISSUE TITLE
Installation page gives impossible (in npm) advice re: individual files

### ISSUE THREAD

**Issue by mcclure** [Tonejs/Tone.js#110]
Looking at https://github.com/Tonejs/Tone.js/wiki/Installation

I find the line: "Using individual files with a module loader can bring your package size down significantly since it will only include the modules used in your code". An example is given with Require.

However, I have downloaded Tone with `npm install --save tone`, and the individual files are not present:

    $ ls node_modules/tone/
    CHANGELOG.md	LICENSE.md	README.md	build		package.json
    $ ls node_modules/tone/build/
    Tone.js		Tone.min.js

I do not know anything about npm, but am following your instructions. My expected behavior is that EITHER "require" with individual files should work as described on your full installation page, OR you should not suggest using individual files in your documentation, OR if using individual files has some sort of caveat ("note this works with bower, but not npm…") you should mention that caveat in your installation instructions.

**Comment by tambien** [comment]
good catch. i didn't notice that only the build files were being uploaded to npm (only to bower) and none of the sources files. I just published an update so that should be fixed.

In order to use the individual files, be sure to make an alias to the root "Tone" directory where all of the source code is. So if you're using npm, create an alias of "Tone" to "npm_modules/tone/Tone" so that internal dependencies can be resolved.

**Comment by mcclure** [comment]
Cool
