### ISSUE TITLE
Installation page "individual files" advice incompatible with Webpack/CommonJS

### ISSUE THREAD

**Issue by mcclure** [Tonejs/Tone.js#112]
Follow up on #110.

I have set up npm to download version 3215e5d from npm so that I can test with the fix for #109. My understanding is that this means I cannot import Tone.min.js from build/ because the version in build/ will be two months old. I need to load the individual source files in order to see the fix for #109.

The docs contain this section "individual files" with instructions on require()ing source files directly out of Tone. Although the start of the document contains instructions for both CommonJS-style includes and RequireJS-style includes, the "individual files" instructions describes RequireJS/AMD style includes (but does not say it is doing this).

Researching this it appears you *cannot* load the individual source files using CommonJS/webpack-- whatever the gulp/UMD magic you are using to glue over the difference between AMD and CommonJS is, it only works with the final .js file in "build".

If the "individual files" trick only works with RequireJS, that is fine, but I would like to suggest you **say so in the documentation**— "this section works only for RequireJS", etc.

On the offchance this is helpful, I have a demonstration of a webpack project using Tone.
* Here is a working version which loads the build/tone.js file https://bitbucket.org/runhello/dryad-artifact/src/a03b5b8e8d6474fb2a02c7983951a4443df48ef4
* Here is a non-working version which loads SimpleFM only https://bitbucket.org/runhello/dryad-artifact/src/ea0a476cbb78b00ba5c88ad707bde58a0e5d7cb1

The source is in src/app.tsx and there are build instructions in the Makefile

**Comment by tambien** [comment]
I took another pass at the [installation wiki](https://github.com/Tonejs/Tone.js/wiki/Installation) page to see if i can incorporate your feedback and clarify things better. 

As you said, the **build** of Tone.js has a UMD footer which enables it to be used with CommonJS, AMD or as a browser global. Because the individual modules are AMD, to use them you need a framework which supports both AMD (like webpack). 

Personally, i use webpack a lot with my projects. Instead of an alias, i typically add the path to the `Tone` folder in the [`resolve.modulesDirectory`](https://webpack.github.io/docs/configuration.html#resolve-modulesdirectories) array. Let me know if that fixes it for you.

**Comment by mcclure** [comment]
Okay, I am sorry. I think I am missing something :( You will have to excuse me, I am new to this kind of Javascript and the many different module frameworks.

Say I create in a directory an app.js:

```
var SimpleFM = require("Tone/instrument/SimpleFM.js")

var fm = new SimpleFM({
      "modulationIndex" : 12.22,
      "carrier" : {
        "envelope" : {
          "attack" : 0.01,
          "decay" : 0.2
        }
      },
      "modulator" : {
        "oscillator" : {
          "type" : "square"
        },
        "envelope" : {
          "attack" : 0.2,
          "decay" : 0.01
        }
      }
    }).toMaster()

fm.triggerAttack("C3")
```

and a webpack.config.js:

```
module.exports = {  
  entry: './app.js',
  output: {
    filename: 'install/app.js'
  },
  resolve: {
    alias: {
      Tone: "tone/Tone"
    },
    extensions: ['', '.webpack.js', '.web.js', '.ts', '.tsx', '.js']
  },
  module: {
  }
}
```

and a package.json:

```
{
  "name": "dryadproject",
  "version": "1.0.0",
  "description": "Generic js art project",
  "main": "app.js",
  "dependencies": {
    "tone": "git+https://github.com/Tonejs/Tone.js#3215e5d"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "paths": {
    "Tone" : "tone/Tone"
  },
  "author": "andi mcc"
}
```

If I run this, I get the failure: `Uncaught TypeError: (intermediate value).toMaster is not a function`

Here is a copy of my demo program if you want to try to run it: [http://vote.runhello.com/j/dryad-proto/tone-include-demo/](http://vote.runhello.com/j/dryad-proto/tone-include-demo/)

I do not understand what "require" is returning. It is something which a webpack user would not expect. What am I missing?

**Comment by tambien** [comment]
No need to apologize. Some of these things are undocumented or could be clarified, so i appreciate you bringing these things up so that i know what common pitfalls are and where i could clarify things better. 

So, this one has to do with the fact that `Tone.Master` and `toMaster` are defined in `"Tone/core/Master"`.  If you add `require("Tone/core/Master")` before you call `toMaster`, then it won't complain that it's `not a function`. 

I think what i'll do is add Master as a dependency to Tone.Source which will make sure that file will be included. I can't think of a good case where you'd want to use one of these sound generators and not eventually connect it to the Master output...

**Comment by mcclure** [comment]
That worked! :O Thanks much. I will test the other open issue.

The only case I can think of you might want sources without master is if you want to use OfflineAudioContext. I haven't investigated yet if Tonejs works with OfflineAudioContext.
