### ISSUE TITLE
Activity and Future Plans for Tone.js

### ISSUE THREAD

**Issue by mikezaby** [Tonejs/Tone.js#1187]
I would like to inquire about the activity and future plans for Tone.js. I noticed that the last release was 7 months ago, and there haven't been many recent commits. Could you provide any information regarding the project's current status and upcoming developments?

**Comment by tambien** [comment]
It's a good question! i'll try to be as transparent as possible with the projects status and roadmap as it stands now: 

Tone.js has a large community of developers who use the library, but as a sole maintainer with a full-time job and no financial backing for the project, it's difficult for me to find time to support the number of questions and requests that i get on here. Tone.js has never had any corporate or foundational support (other than a small number of individual sponsors on github which i really appreciate). I started the project and have maintained it for many years because I believe in making music more accessible and interactive through the browser and web. 

I still very much believe in the library and in the community of musicians and programmers that use it, and would love to find more time one day to add features, clean things up, add more docs, and continue to support users on here, but i don't have a timeline for when that would be

I would gladly support/mentor/meet regularly with anyone who is interested in taking on more responsibility of library maintenance. I am very appreciative to all the contributors, people answering questions on github and in the email forum (thank you so much), and other people who have supported the project throughout the years

Please get in touch if you have bandwidth and would like to take on a more active role in maintenance (or tag someone who might be interested)
