### ISSUE TITLE
PolySynth: swap notes and time arguments in triggerRelease to match other instruments

### ISSUE THREAD

**Issue by hiddedejong** [Tonejs/Tone.js#119]
PolySynth's triggerRelease function receives `triggerRelease(notes, time)`. However, since other instruments are not polyphonic, these instruments do not require a notes argument and their first argument is time. (`triggerRelease(time)`)

When writing functions that should automatically trigger notes in instruments, I have to check if an instrument is a PolySynth and decide on how to structure the function call. It would be easier to swap the arguments in PolySynth so that all instruments can be called with `triggerRelease(time[, notes])`.

**Comment by tambien** [comment]
So i've been thinking about this a bit, you have a good point, but i think i'll leave the API as it currently is. As you point out, having a consistent and unified API is always preferable, but i don't think it works in this case. The convention that i've been using for the instruments is that optional and low priority arguments are later in the arguments list with time usually being at the end. This makes it so that you could easily leave out the time argument and have the envelope trigger immediately. 

In your proposed API, if you wanted to trigger the release of notes immediately, you'd might do something weird looking like `triggerRelease(undefined, ["C3", "G4"]);`. With the current API, it'd just look like `triggerRelease( ["C3", "G4"]);`. 

Since the notes passed into the release of the polysynth are the most important argument (otherwise you end up with hanging notes), i think it's good that the current API emphasis this difference.
