### ISSUE TITLE
Synced players start even though the transport has been stopped or paused

### ISSUE THREAD

**Issue by harumanu** [Tonejs/Tone.js#121]
Hello,

I'm having some trouble using the transport and playing audio files using Player instances. 

I would like to start a number of Player instances in sequence and be able to pause/start this sequence at any given time. The problem is that it seems as if all synced players get scheduled to play when the transport starts, and their play callback get called at their designated time even if the transport has been stopped before it gets there.

Consider this contrived and isolated example:

        var playerA = new Tone.Player("clip1.mp3").toMaster(); // 10 seconds long
        var playerB = new Tone.Player("clip2.mp3").toMaster(); // 10 seconds long

        Tone.Buffer.onload = function () {
            playerA.sync('0:0:0');
            playerB.sync('4:0:0'); // Let's imagine that this represents 10 seconds
            Tone.Transport.start(); // playerA starts playing

            setTimeout(function () {
                Tone.Transport.pause(); // playerA stops playing
            }, 5000);
        };
    }, 1000);

What will happen in this case is that when Transport.pause has been called, there will be about 5 seconds of silence and then playerB will suddenly start playing. If I let it play through and then start the transport again, playerA will continue playing from the point where it was paused (however, playerB actually won't play once the transport reaches 4:0:0).

This feels like a bug to me, or am I misunderstanding the use case of sync?

**Comment by tambien** [comment]
Thanks for the ticket. The issue is that the `sync` method calls the player's `start` method when the Transport is started (with the passed in delay time), and since the player's state is not `"started"` when the Transport's `pause` is invoked, the player ignores it.

I think this could be fixed if there was a `cancel` method on the player (or all the sources) which would cancel events scheduled in the future. I'll have to think a little more on how to best do that. One way would be to store the AudioBufferSourceNode or OscillatorNode along with the rest of the scheduling values so that that node could be stopped and disconnected on `cancel`.

**Comment by polyrhythmatic** [comment]
Having this issue as well. I tried using the dev branch however I'm now getting an error 

`Uncaught InvalidStateError: Failed to execute 'start' on 'AudioBufferSourceNode': The duration provided (-1.30592) is less than the minimum bound (0).t.Player._start`

I'm using player to buffer files on mobile. I split a song into multiple files and load them. All the players are then scheduled using .sync(offset) method.

Would love a solution to this if possible. I've tried using the Transport Schedule function to no avail.

**Comment by tambien** [comment]
Thanks. If you have a second, could you make an example which illustrates the issue? I haven't been able to reproduce it. 

Here's some really minimal code that i tested out and works as expected for me:

```javascript
var player = new Player("audio/FWDL.mp3", function(){
	Transport.start();
}).sync("1m").toMaster();
```
