### ISSUE TITLE
Apply a filter to a subsection of a AudioBuffer

### ISSUE THREAD

**Issue by KevinXZX** [Tonejs/Tone.js#1217]
Hello, 

I was wondering if there's a way to apply a filter e.g. low-pass filter only on a specific interval of an audio buffer. For instance, an example would be having a low-pass filter from 0s to 5s then a high-pass filter from 5 to 10s and lastly shifting the pitch for the last 5s. 

Is this possible/a supported functionality? 

One of the ways I was considering doing this was splitting the audiobuffer myself using the `slice` method and using multiple Player objects to play them one after the other using the `onstop` callback however this results in a noticeable gap in the audio. 

Thanks.

**Comment by dirkk0** [comment]
To my knowledge this is out of scope for ToneJS.
If I were to tackle this problem, I would try to access the WebAudio
buffers 'under the hood' directly and slice them there. This could be a
starting point, but I didn't try this myself yet:
https://miguelmota.com/bytes/slice-audiobuffer/

**Comment by tambien** [comment]
Another way to do it would be to render the audio file with `Offline`. Create two audio sources, one connected to a lowpass filter and another connected to a highpass filter. Then schedule both audio files to play with a matching offset/start time so that they play one after the other. the resulting audio will have the affect as if the first 5 seconds are lowpassed and the second 5 seconds are highpassed.
