### ISSUE TITLE
How can I use a Rubberband node?

### ISSUE THREAD

**Issue by benlieb** [Tonejs/Tone.js#1227]
I'm trying to get rubberband pitch shift node working with my Tone.js audio player. Can't seem to get it to work.

Trying something like this:

```js
      const pitchShiftNode = await createRubberBandNode(
        player.context.rawContext._nativeAudioContext,
        '/audio/music/rubberband-processor.js'
      );
```

Does anyone have a working example of how to use Rubberband with Tone?

**Comment by marcelblum** [comment]
Assume you're talking about use with [rubberband-web](https://github.com/delude88/rubberband-web). I've experimented with it a bit but ultimately decided against using it because latency and cpu use were too high and Rubber Band licensing is not cheap. (Not a knock against Rubber Band itself, sound quality is wonderful and I would have gladly paid up if the other problems weren't there, but using it under the limitations of Wasm and web audio presented too many performance issues to make it worthwhile for me - currently using [phaze](https://github.com/olvb/phaze) instead as a good enough/faster/free alternative.)

Anyway for interoperability with Tone you just need to hack the native node returned by `createRubberBandNode()` into a `ToneAudioNode`. Something like this should work (untested code sorry, going from memory):
```js
const newToneNode = new Tone.ToneAudioNode();
newToneNode.pitchShiftNode = await createRubberBandNode(nativeContext, 'rubberband-processor.js');
newToneNode.input = new Tone.Gain();
newToneNode.output= new Tone.Gain();
newToneNode.input.chain(newToneNode.pitchShiftNode, newToneNode.output);
