### ISSUE TITLE
Tone.Part.start with arguments does not start Tone.Part after stop

### ISSUE THREAD

**Issue by hiddedejong** [Tonejs/Tone.js#131]
Calling `Tone.Part.start(time);` after `Tone.Part.stop();` does not start the `Tone.Part`. Calling `Tone.Part.start();` without arguments does.

An example can be found here: [https://jsbin.com/hufamuboqi/edit?js,console](https://jsbin.com/hufamuboqi/edit?js,console)

**Comment by hiddedejong** [comment]
`Tone.Player` behaves sort of the same way, but does start playing. That's because `Tone.Player` does not check `if (this._state.getStateAtTime(ticks) !== Tone.State.Started)` before starting playback. However, when requesting `Tone.Player.state` after `Tone.Player.start(0)`, it returns `"stopped"` like `Tone.Part` does.

Should `Tone.Part` also skip the `getStateAtTime` check like `Tone.Player`?

**Comment by tambien** [comment]
This is actually the desired behavior. 

I'm working on the documentation to clarify this, but all the Event classes are started and stopped along the Transport's timeline. When you reschedule `Tone.Part.start(0)` the second time, it is actually already scheduled to start at Transport's TimelinePosition=0 and will not be started again. With no arguments `Tone.Part.start()` is started at the current Transport position. 

To walk through your jsbin:

1. The Transport is started
2. 1 second later the part is started at TimelinePosition = 0. This will add the part along the Transport's timeline which by this time is already halfway through the first measure. In the parts internal timeline, it would have already passed the events "C2" and "C3" since it was scheduled to start in the past.
3. The part is stopped at the current TimelinePosition (approx "0:3"). So now the part is scheduled to play between "0:0"~"0:3". If the Transport were stopped and restarted, the part would play for that period. 
4. The part is scheduled to start again at TimelinePosition=0. Since it is already started at that time, it will not be scheduled to start again. And since the current TimelinePosition is > "0:3", it reports its state as "stopped".  
5. The part is started at the current TimelinePosition (approx "2:0"). The part's state === "started" as long as the TimelinePosition is greater than "2:0". 

[Here's a wiki](https://github.com/Tonejs/Tone.js/wiki/TimelinePosition) which hopefully clarifies this a little more. 

Also regarding Tone.Player, it does actually test the current state, but that test is done in the parent class, Tone.Source, and will not restart if it is currently playing (unless retrigger=true).
