### ISSUE TITLE
Incorrect state returned from getStateAtTime

### ISSUE THREAD

**Issue by lukephills** [Tonejs/Tone.js#132]
I've noticed while using the Sampler, that when you triggerRelease and immediately triggerAttack, occasionally the buffer doesn't play. I think the Envelope at that point could be in the wrong state? 

This happens regularly if it's hooked up to a computer/midi keyboard and you play different notes quickly.

It's hard to pin down exactly what's going wrong but I've created a simple setTimeout example which shows an inconsistency (not the same problem I'm talking about but I think it could be related): http://jsbin.com/wazekijori/edit?js,console
(The buffer should be triggered twice)

**Comment by lukephills** [comment]
It appears to be worse with longer audioBuffers. Should that have an effect?

**Comment by lukephills** [comment]
I've narrowed it down to line 125 of Source.js
 
`if (this._state.getStateAtTime(time) !== Tone.State.Started || this.retrigger){`

getStateAtTime is returning 'started' when it should be 'stopped'.

This is the same problem as issue #74

**Comment by tambien** [comment]
Hey Luke. Thanks for the issue. I've been trying to wrap my head around why this is happening for you. I've haven't been to recreate the issue on my end after clicking "run" on that jsbin on multiple computers many hundreds of times. 

My only guess is that the events are firing out of order. Which maybe possible with a midi keyboard or computer keyboard that events too close together might arrive out of order... 

I don't think it's related to that line you reference in Source.js, because `this.retrigger=true` in Tone.Sampler's player, so it doesn't matter what the state returned by `this._state.getStateAtTime(time)` is, that conditional will always pass. 

I've updated your jsbin to the new Sampler API so you can test out to see if you're still experiencing that problem: http://jsbin.com/risaragaci/1/edit?js,console

**Comment by tambien** [comment]
@lukephills I finally was able to recreate the issue and did a little debugging in the console. i think i understand what's happening:

Chrome (and probably other browsers) only updates the AudioContext.currentTime every block (128 samples = 2.9ms @ 44.1k). So when the timeouts trigger 1 millisecond apart from each other, the `currentTime` which is returned is sometimes the same, and when it's the same you get no sound because you are trying to schedule a triggerAttack and triggerRelease at the same exact time. 

This is probably what was happening to you in the other issue that you referenced. The times need to be at least one block away from each other.

**Comment by lukephills** [comment]
Hey @tambien yes, that sounds about right. I did find a work around in the end for Blokdust but I've forgotten what it was now. It's definitely useful to know that the times need need to be at lease one block apart. Thank you for looking into this.

**Comment by tambien** [comment]
@lukephills Glad you figured it out as well. 

Just to clarify, it's not that the time values need to be one block apart (they can be scheduled one sample apart), but when you're using the immediate scheduling (i.e. no time argument passed into triggerRelease) you need to make sure that you're not inadvertently scheduling things at the same time.
