### ISSUE TITLE
Tone.Sampler hangs on Mac OS Safari 9.0.3, fails silently

### ISSUE THREAD

**Issue by hatsumatsu** [Tonejs/Tone.js#139]
I think I found a bug using `Tone.Sampler` on latest Safari (v. 9.0.3): Loading an .mp3 sample, creating a loop then waiting for the `load` event on `Tone.Buffer` the loop starts in Chrome and Firefox as expected. In Safari however the `load` event is fired but the playback somehow stops / fails silently without an error. This happens only on first load while reloading the page starts the loop as intended. It might have something to do with loading the external file because when the bug occurs Safari doesn't show the mp3 file in the Resource tab of its DevTools.

You can find a reduced test case here 
https://github.com/hatsumatsu/tonejs-safari-debug

or here (JS only)
https://gist.github.com/hatsumatsu/5d67dc2a1373086de50da46d14d1ef80

PS: Thanks for creating this impressive library!

**Comment by hatsumatsu** [comment]
I must admit that the test case I provided above is not really minimal, here is a way simpler version of the code I use that still reproduces the described behavior:

````
sampler = new Tone.Sampler( {
	'A': 'bass.mp3'
} ).toMaster();			

Tone.Buffer.on( 'load', function() {
	sampler.triggerAttack( 'A' );
} );
````

> https://github.com/hatsumatsu/tonejs-safari-debug/blob/master/minimal.html

Thanks in advance!

**Comment by tambien** [comment]
Thanks for the updated example. I just ran it and i was able to recreate the silent failure as you describe. 

I opened up the console and inspected `Tone.context.state` which reports itself as `"suspended"` instead of `"running"`. I'm not sure if an "explicit user action" is required to start the context as stated in [apple's guidelines for iOS](https://developer.apple.com/library/safari/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/PlayingandSynthesizingSounds/PlayingandSynthesizingSounds.html). 

I tried attaching the sample triggering to a button, but that didn't fix it either. The only thing which did solve the problem was to explicitly call `resume` on the context. I am going to investigate a little more and see if this is something i can wrap up into [StartAudioContext](https://github.com/tambien/StartAudioContext).

**Comment by hatsumatsu** [comment]
Thanks for looking into it, the suspended audio context is an interesting insight. I tried several methods of triggering `resume()` on it and it seems that `setTimeout`, `setInterval` and random events like `mousemove` do the trick though its no "explicit" user action.

**Comment by tambien** [comment]
I updated StartAudioContext with some of these suggestions to hopefully fix this issue. We can move this bug over to that repo if it continues.
