### ISSUE TITLE
Scheduling a future note from a callback

### ISSUE THREAD

**Issue by andyhall** [Tonejs/Tone.js#142]
Hi,

I can't figure out the correct syntax to schedule a future note from inside a callback (like a Tone.Loop callback).

That is, suppose I have a loop running every half note, which plays a quarter note:

```js
var loop = new Tone.Loop(function(t) {
    synth.triggerAttackRelease('C4', '4n', t)
}, '2n').start()
```

What I want to do is schedule a second note, one quarter note into the future compared to time `t`:

```js
var loop = new Tone.Loop(function(t) {
    synth.triggerAttackRelease('C4', '4n', t)
    Tone.Transport.schedule(function(t2) {
        synth.triggerAttackRelease('D4', '4n', t2)
    }, '????')
}, '2n').start()
```

But I can't figure out what the `????` should be. `'+4n'` isn't quite right, as it would occur a quarter note after the callback is executed, rather than after time `t`. Based on the docs I thought it could be set to an expression like: `t + ' + 4n'`, but this doesn't work either - the scheduled callback gets delayed by an amount of time that seems to depend on when the Transport was started.

Here's a full working sample of the code I thought would work, showing the delay. Is this a bug, or am I doing something wrong?

```js
var synth = new Tone.SimpleSynth().toMaster()    
    
var loop = new Tone.Loop(function(t) {
    synth.triggerAttackRelease('C4', '4n', t)
    Tone.Transport.schedule(function(t2) {
        synth.triggerAttackRelease('D4', '4n', t2)
    },  t + ' + 4n')
}, '2n').start()

var delay = 2000 // timing of the scheduled note depends on this??
setTimeout(function () {
    Tone.Transport.start()
}, delay)
```

**Comment by tambien** [comment]
The number returned from the Tone.Loop callback is in AudioContext time which is the value that all Web Audio nodes use to schedule. Tone.Transport has another timeline which it keeps track of independently which has additional capabilities like seeking, looping, pausing, etc. `Transport.schedule` takes this time value as the argument not the AudioContext time. 

I try to describe it in more detail in this [wiki page](https://github.com/Tonejs/Tone.js/wiki/TimelinePosition)

The simplest solution to your question would just be to schedule both notes in the callback without an additional `schedule` inside of the callback. 

```javascript
var loop = new Tone.Loop(function(t) {
    synth.triggerAttackRelease('C4', '4n', t)
    synth.triggerAttackRelease('D4', '4n', t + synth.toSeconds("4n"))
}, '2n').start()
```

The way you are scheduling will have additional side effects, which is that if you were to stop and restart the transport, all of those events that you set with `Tone.Transport.schedule` would be playing again in addition to the ones that you're scheduling. So you'd be adding more and more scheduled notes along the Transport each time you stop and restarted. 

If scheduling inside of callback is in fact what you want to do, i would use `Transport.scheduleOnce` instead of `schedule` because it will remove the event after it's been invoked. And then we get to your original question: I think the easiest way at the moment (this will change slightly with r7) is to construct a time string using the current Transport position and concatenate `" + 4n"` to that. 

```javascript
var loop = new Tone.Loop(function(t) {
    synth.triggerAttackRelease('C4', '4n', t)
    Tone.Transport.scheduleOnce(function(t2){
        synth.triggerAttackRelease('D4', '4n', t2)
    }, Tone.Transport.position + " + 4n");
}, '2n').start()
```

**Comment by andyhall** [comment]
Gotcha, thanks. I'd supposed all the APIs used transport time and the conversion to context time was done behind the scenes.
