### ISSUE TITLE
Scheduler-related crackle in r7 on Nexus 7

### ISSUE THREAD

**Issue by markmarijnissen** [Tonejs/Tone.js#143]
I am using a loop to trigger a melody every measure. Minimal example here: http://jsbin.com/dafivecugu/1/edit

The audio crackles all the time. It crackles when triggered from the loop. It also crackles when triggered by a click. Only when I stop the loop and it finishes the current one. Those few seconds sound suprisingly clear.

Strange isn't it? I am not aware of Tone.js internals, so you could give a hint?

The error is also reported on Nexus 4, some iPhone and other mobile devices.

**Comment by markmarijnissen** [comment]
btw , couldn't get StartAudioContext working in the fiddle.

**Comment by tambien** [comment]
i updated [your bin](http://jsbin.com/hototejasu/4/edit?html,js,output) for the latest version of Tone.

I've got no good way of testing this since i don't have a Nexus phone handy. The only thing that i can think of is that i've seen some Web Worker performance issues before on Android and since the clock is using Web Workers maybe it's causing some kind of performance related crackles. 

If you can, modify [this](https://github.com/Tonejs/Tone.js/blob/master/build/Tone.js#L6946) `UPDATE_RATE` value to be something bigger say 50 or 100. and see if that helps at all. that'll make it poll the background thread less often and if the Web Workers are the issue, then it should help.

**Comment by tambien** [comment]
@markmarijnissen Please git it a shot with r9 if you have a chance and let me know if you're still experience this issue

**Comment by ziagrosvenor** [comment]
I have a similar issue occurring on IPhone 5. When I chain multiple effects there is more crackle. At the moment there is a small amount of crackle with only one FeedbackDelay. The crackle occurs after multiple notes are played. How do I set the ```UPDATE_RATE``` config?

**Comment by tambien** [comment]
Crackling is a sign that your processor can't keep up with the audio rendering and is dropping samples. I wrote [a wiki](https://github.com/Tonejs/Tone.js/wiki/Performance) on some performance related matters. Hopefully it helps a little.

UPDATE_RATE has been changed to "latencyHint". You can schedule further in advance if you try `Tone.Transport.latencyHint = 0.5`.

**Comment by ziagrosvenor** [comment]
@tambien Thanks for your quick reply and help! 

I have found that setting ```Tone.Transport.latencyHint = 0.5``` doesn't decrease the crackling. 

I also tried setting the ```latencyHint``` to ```"balanced"``` - And I still get some crackling.

Would it be possible to configure a low sample rate to achieve a degraded mobile experience?

**Comment by tambien** [comment]
@ziagrosvenor as of now, [sampleRate](https://webaudio.github.io/web-audio-api/#widl-BaseAudioContext-sampleRate) is a readOnly property and cannot be set in the Web Audio API.

**Comment by ziagrosvenor** [comment]
@tambien Okay is it possible to control the sample rate of the web workers?

**Comment by tambien** [comment]
@ziagrosvenor i don't think so
