### ISSUE TITLE
Bug in the Sampler?

### ISSUE THREAD

**Issue by AlesTsurko** [Tonejs/Tone.js#146]
Hey!
Few days ago it was possible to load multiple samples into the sampler and then trigger these by names:

```javascript
var sampler  = new Tone.Sampler({
  "A.1" : "/path/to/sample1.mp3",
  "A.2" : "/path/to/sample2.mp3",
  "B.1" : "/path/to/sample3.mp3"
}).toMaster();

sampler.triggerAttack("A.2");
```

Yesterday my code stopped to work with the error:
>Error: Tone.Player: tried to start Player before the buffer was loaded

Is it a bug or did you changed something?

**Comment by tambien** [comment]
Thanks for the ticket. I actually decided to simplify Sampler in the new release. Now it only accepts a single buffer (though you can set a new one by changing `sampler.player.buffer`) and passes it through an AmplitudeEnvelope. If you'd like functionality similar to the previous Sampler, check out a new class called [Tone.MultiPlayer](https://tonejs.github.io/docs/#MultiPlayer). It's got a basic AR (attack/release) envelope instead of an ADSR like in Sampler, but is better suited to handling many buffers.

**Comment by AlesTsurko** [comment]
Thanks! Looks like the MultiPlayer is exactly what I need. I just didn't found if it's possible to loop samples with this. Is it possible?
