### ISSUE TITLE
Tempo changes and time calculations

### ISSUE THREAD

**Issue by alexthewilde** [Tonejs/Tone.js#169]
First off, I really appreciate the effort you've put into making Tone.js such an excellent library!

I need a little bit of help to wrap my head around how to implement a Transport with tempo changes. I'm aware of `Tone.Transport.bpm.rampTo()` to create tempo change progressions and it's working beautifully. However, Tone doesn't seem to respect bpm value changes when converting absolute times to Transport positions, correct?

Here's a concrete example:
- a Transport with 3 measures, 4/4 signature, bpm = 100
- a tempo change: `0 (100bpm) - - - 1 (change to 120 bpm) - - - 2 (120bpm) - - -`

Now I would like to know the relative BarsBeatsSixteenth position at 6 seconds Transport time, i.e. `Tone.Time(6).toBarsBeatsSixteenths()`. This should return something like "2:33" but Tone still calculates with bpm=100 for all measures so it will return "2:2".

The background here btw is to implement beat mapping for music recordings with natural tempo variations. It should be possible to seek to a certain time in the recording and the Transport would automatically jump to the corresponding beat position in its timeline. Thus my need for converting absolute time to a relative Transport position.

I'm using `Tone.Sequence` to generate the basic beat structure. The idea was to make use of tempo curves to synchronise beats with the actual musical recording. Have you ever encountered this use case before?

**Comment by tambien** [comment]
This is a good question. At the moment, all the time calculations in Tone.js are done "just-in-time" and are based on the current bpm value at the time the value was requested. So if you ask for it to convert 6 seconds at the beginning of the Transport's timeline while the tempo is 120bpm, it'd return "3:0:0". If you asked for it after it's transitioned to 100bpm you'd get "2:2:0" and if you ask for it somewhere during the ramp, you'd get something in between. 

The solution to this is a little complex. The only way to get the accurate measure is to use some calculus and integrate over that period of time given all of the programmed curves on the bpm. @echo66 published a great paper about this technique and has an implementation [here](https://github.com/echo66/bpm-timeline.js). 

Eventually, i do hope to use this technique in the Tone.Clock which would make this sort of timing calculations possible.

**Comment by alexthewilde** [comment]
I see, thanks a bunch Yotam. I discovered bpm-timeline.js just yesterday and I actually wanted to ask about your opinion. It really does seem like a natural fit for Tone.js's tempo management, so I'm curious in which way you'll incorporate it as you mentioned.

For now I'll be going down another route to achieve what I need. Instead of using Tone.Sequence with relative times, I'm rolling my own beat calculation logic which ultimately creates single Transport events for each beat with absolute times down the calculated tempo curve. The downside of it is that I loose the power of Tone's relative time calculations and Transport.bpm basically becomes irrelevant too.

**Comment by tambien** [comment]
@alexthewilde I know this issue is pretty stale at this point, but i've been thinking about how best to achieve what you're trying to do for a while now, and i've got a proposed solution. I've been gradually introducing some of the concepts from @echo66's bpm-timeline paper such as the ability to calculate the elapsed beats in a given period of time even during a complex automation curve. Most of that functionality is in [Tone.TickSignal](https://tonejs.github.io/docs/dev/TickSignal) but it's trickled up to Clock/Transport as well. 

I've added a `timeToTicks` and `ticksToTime` methods on the TickSignal (which is the Transport's bpm signal), this will let you calculate the elapsed ticks given a time while factoring in any scheduled curves to the bpm. 

```javascript
var now = Transport.now()
Transport.bpm.setValueAtTime(100, now);
Transport.bpm.setValueAtTime(120, now + 1);
Transport.bpm.timeToTicks(6, now).toBarsBeatsSixteenths()
```

The slight difference you'll notice from the example you gave in your original issue (`Tone.Time(6).toBarsBeatsSixteenths()`) is that `timeToTicks` takes both the duration you want to calculate as well as the time that you'd like to calculate from. You can see in the above example that `Transport.bpm.timeToTicks(1, now)` and `Transport.bpm.timeToTicks(1, now+1)` would return different things, so that second argument is required. 

I'm sure you've figured out a totally different way to do this by now, but hopefully this is helpful for future projects or other people trying to do a similar thing.

**Comment by alexthewilde** [comment]
@tambien that sounds like a real slick solution! As a matter of fact I've also used the tempo curve functions from bpm-timeline.js to calculate the beat events between two given timestamps. This has worked fine for me but as I've stated before, it forced me to work with raw events rather than using Tone's relative times.
