### ISSUE TITLE
Scheduling value and ramped changes in a signal

### ISSUE THREAD

**Issue by andyhall** [Tonejs/Tone.js#171]
Hi,

I'm trying to make an effect where a synth's frequency value jumps and ramps between various values - e.g. starting at 400 and ramping to 800, but halfway through jumping from its current value to a different value, and then continue to ramp. Right now I'm doing this: 

```js
synth.triggerAttackRelease(400, 1)
var now = Tone.now()
var slop = 0.001
synth.frequency.rampTo(650, 0.5, now)
synth.frequency.setValueAtTime(500, now + 0.5 + slop)
synth.frequency.rampTo(800, 0.5, now + 0.5)
```

This works more or less, but for more complicated cases the code gets pretty hairy, and if the slop is too small then things start to fail randomly.

Is there an easier way to do this with a `TimelineSignal`? From reading the docs and the source, it *looks* like I could use a TimelineSignal to drive the frequency parameter, and then if I set a value in the middle of a ramp it would magically work out the intermediate values for me. Something vaguely like this:

```js
var freq = new Tone.TimelineSignal().connect(synth.frequency)
freq.value = 400
freq.rampTo(800, 1, 0)
freq.setValueAtTime(500, 0.5)
```

But in practice, `connect`ing a TimelineSignal to other parameters doesn't seem to do anything, and I can't find any docs or comments that show how it should work.

Am I missing something obvious, or is this not the way to go about things?

Thanks!

**Comment by tambien** [comment]
What you're describing is possible with both Signal and TimelineSignal. TimelineSignal will give you the added ability to know scheduled values in the future, which is useful if you're trying to cancel and schedule a new ramp without any discontinuity. 

`rampTo` is for immediate ramping of values, it sets the current value of the signal (using `setValueAtTime`) and then ramps from there using `(linear or exponential)RampToValueAtTime`. So what you're describing in your first example should be written as:

```javascript
synth.frequency.rampTo(650, 0.5)
synth.frequency.setValueAtTime(500, now + 0.5)
synth.frequency.exponentialRampToValueAtTime(800, now + 1)
```
That will ramp from the current value to 650 for a half second, then immediately jump to 500 and then from there ramp to 800. 

I used `exponentialRampToValueAtTime` in the second case because rampTo is going to schedule an unnecessary `setValueAtTime` with the wrong value; Signal does not compute future values, only TimelineSignal does that, so when Signal schedules the second rampTo it is based off of the **current value** of the signal (440 or whatever your starting value is) not the computed future value of the signal (in this case 500). 

If you use TimelineSignal, you could just write it in the above way or how you wrote it in your first example because the second invocation of `rampTo` will compute the future value: 

```javascript
var timelineSignal = new Tone.TimelineSignal(440).connect(synth.frequency)
var now = Tone.now()
timelineSignal.rampTo(650, 0.5, now)
timelineSignal.setValueAtTime(500, now + 0.5)
timelineSignal.rampTo(800, 0.5, now + 0.5)
```

The reason that your second example probably wasn't working is most likely because the time values that you put given (0 and 0.5) had already passed. You want to schedule it relative to the AudioContext's current time (i.e. `now`). 

I hope that clarifies things a little.

**Comment by andyhall** [comment]
Thanks, got things working now!

I was overlooking that TimelineSignal doesn't have a rampTo method, so those calls were falling back to the Signal method and behaving differently from TimelineSignal's other ramp methods.
