### ISSUE TITLE
Swing implementation

### ISSUE THREAD

**Issue by algomusic** [Tonejs/Tone.js#180]
When setting the swing value in the Transport, the first two 16th notes in each beat are correctly lengthened and shortened, but the remaining two 16ths seem not to be varied. Resulting in an inconsistent swing feel.

**Comment by tambien** [comment]
[This is how](https://github.com/Tonejs/Tone.js/blob/master/Tone/core/Transport.js#L207) swing is currently calculated. I added a sinusoidal curve to the delay amount so that it's not uniformly pushing the beat back which was leading to the swung notes eventually getting pushed onto the beat. Using the sinusoidal curve, the up beat is the most swing at the notes around it are progressively less delayed.

[Here](https://jsfiddle.net/faxx637t/2/) is a little test case for swing. Sounds pretty swung to me, but i'm open to other suggestions.

**Comment by algomusic** [comment]
Thanks or the elegant example to test the swing function. Slowing it down makes the rhythm more discernible to me. To my ears the 8n loop works as expected, I expect the 16n loop to sound identical but twice as fast (compare by halving tempo), however it does not.

**Comment by tambien** [comment]
Can you post an example of what you mean? 

The other variable at play is the `swingSubdivision` which defines the downbeats vs the upbeats. Just tried halving the bpm and doubling the `swingSubdivison` and loop rate [[link](https://jsfiddle.net/faxx637t/3/)]. Sounds the same as the other test case. 

I'm not convinced that i've got the right way to do swing but i couldn't find other implementations to reference.

**Comment by algomusic** [comment]
Seems to be 'solved'. First, of course, the swingSubdivision needs to be set correctly. But then also the time value passed to Tone.Transport.start() is critical. If it is 0 (or empty) then the swing function is out of phase. But a slight delay in starting, say '+1', provides enough time, it seems, for things to initialise correctly and align. Below is my test case, that uses the Part routine (which my project is using).

var osc = new Tone.Oscillator('C2').toMaster()

var part = new Tone.Part(function (time, noteData){
	osc.start(time).stop(time + 0.05)
}, [["0:0:0"], ["0:0:2"], ["0:1:0"], ["0:1:2"], ["0:2:0"], ["0:2:2"], ["0:3:0"], ["0:3:2"]]).start(0);

Tone.Transport.swing = 0.5
Tone.Transport.swingSubdivision = "8n"
Tone.Transport.bpm.value = 100
Tone.Transport.start('+1')
