### ISSUE TITLE
Adding / removing effects from Tone.Master

### ISSUE THREAD

**Issue by jsruvi** [Tonejs/Tone.js#187]
Hello!
Could you please explain me how can I dynamically add and remove effects from Tone.Master ?

For example I created effects:
`let effect1 = new Tone.JCReverb(0.5); `
 `let effect2 = new Tone.AutoFilter();`

And then I want them applying to all my played synths / samplers etc.
And when I click on button - some of that effects should disappear.

How can I do that ?

**Comment by tambien** [comment]
I think the simplest way to do this would be to connect your source(s) to the effects and then connect the effects to Tone.Master. 

To connect them in series, first effect1 then effect2 then Tone.Master: `source.chain(effect1, effect2, Tone.Master)`

To connect them in parallel you can do `source.chain(effect1, Tone.Master); source.chain(effect2, Tone.Master);`

To disconnect the source from the effects you can then just `source.disconnect()` or to bypass the effects you can turn their `wet` signal down to 0. `effect1.wet.value = 0;  effect2.wet.value = 0`

There's a little more info on connecting/disconnecting [on this wiki article](https://github.com/Tonejs/Tone.js/wiki/Connections).

**Comment by jsruvi** [comment]
Thank you!

**Comment by miikaluolajanmikkola** [comment]
I have a humble feature request related to this topic: Bypass would be a convenient parameter to set effects on and off in an arbitrary node chain. Tuna.js has it and I love the feature, but I'm ditching the lib because ScriptProcessorNodes cause crashes. With Tone.js it looks like I'd have to write multiple if-else clauses and UI-logic for each individual effect whether on or off. Handling connection logic becomes even more complicated if every second effect is off.. Would be nice to say:

var chorus = new Tone.Chorus(1.5, 2.5, 0.5, [optional boolean bypass, default = false]);
masterChain.push(chorus);

My app takes care of the rest, and this way it is handy and fun to try different fx and combinations.

**Comment by tambien** [comment]
currently no `bypass` boolean, but you can set `chorus.wet.value = 0` to bypass the effect.

**Comment by Razz21** [comment]
Sorry, for opening this old thread, but if someone is still interested in bypass functionality, here is my implementation:
```javascript
/* wrapper for effect class / bus */
class FX extends Tone.ToneAudioNode {
  constructor(options) {
    super();
    this.effect = new options.effect(options.options); // create effectNode in constructor
    this._bypass = options.bypass;
    this._lastBypass = options.bypass;

    // audio signal is constantly passed through this node, 
    // but processed by effect only, if bypass prop is set to `false` 
    this.input = new Tone.Gain();
    this.output = new Tone.Gain();

    this.effect.connect(this.output);

    this.activate(!options.bypass); // initialize input node connection
  }

  get bypass() {
    return this._bypass;
  }

  set bypass(val) {
    if (this._lastBypass === val) return;

    this._bypass = Boolean(val);
    this.activate(!val);
    this._lastBypass = val;
  }
  
  /*
 activate effect (connect input node), if bypass == false
 */
  activate(doActivate) {
    if (doActivate) {
      this.input.disconnect();
      this.input.connect(this.effect);
    } else {
      this.input.disconnect();
      this.input.connect(this.output);
    }
  }
 
  toggleBypass() {
    this.bypass = !this._bypass;
  }

  dispose() {
    super.dispose();
    this.effect.dispose();
    return this;
  }
}

```
example usage
```javascript
const osc = new Tone.Oscillator().start();

const fx1 = new FX({ 
  effect: Tone.Distortion,       // effect class
  options: { distortion: 0.8 }, // effect initial options
  bypass: true,                     // initial bypass value
});
const fx2 = new FX({ effect: Tone.Phaser, bypass: false});
const osc.chain(fx1, fx2, Tone.Destination);
```

With some customization to class above you can even change/remove effect on the fly with current bypass option and creating sth like dynamic fx-bus.

I am pretty new to this library and this solution probably is not perfect, but works (at least). Any advices/fixes are welcome.

**Comment by cdcv** [comment]
Razz21, thank you for contributing this.  I think it would be great if tonejs incorporated a simpler wrapper like this within the codebase.  In the meantime, can I ask if you might provide a couple more examples that I think would benefit both us and other users.
1) How do you change effect parameters during a 'live', playing sound using your class?  Do you have to create a new sound instance, or can you change an existing one while it is playing.  This is, for us, the most important question.
2) How do you chain a whole series of effects (more than the two that chain allows)?
3) Is it possible to make changes using your class to both all audio output (eg through Destination) and individually to particular sounds or instruments?
4) Which sound modifiers will your class work on?  Will your class work on volume/gain?
5) Is it possible to use your class to gradually change effect parameters, eg through a rampTo functionality?

Thanks again for posting this.

**Comment by Razz21** [comment]
@cdcv The general idea was to wrap effect component (or any other `ToneAudioNode` derieved class) and allow user to connect/disconnect it on the fly (and maybe save some CPU). Just connect this component once to general signal chain and control inner `effect` behaviour.
This class extends `ToneAudioNode` and inherits all its methods and properties and you can use them as any other tonejs components - connect/disconnect another nodes to it in signal chain. This object was not designed to use with SignalNodes (e.g. Oscillators) as `effect` property.

lot of questions here, but I'll try to answer them (or at least some of them):
1. You can use tonejs `set()` method and access properties using nested objects [(docs)](https://tonejs.github.io/docs/14.7.58/ToneOscillatorNode#set), for example:
```js
// assume you've created some synth object that contains `fx1` property which is an `FX` instance 
// with some effect that has `wet` property:
synth.set({ fx1 : { effect : {wet : 0.5} } } ); // effect-component properties accesible by `effect` property
```
Effect inside this class is reused -does not destroyed/initialized on every bypass toggle, simply disconnected and reconnected to inner `input`/`output` nodes to allow audio signal to be passed through node, even the `effect` is _disabled_ (object is still kept in memory, just not processing any signal. If  you need something more modular I would recomment creating custom logic to initializing/destroying components, this implementation wont work).
2. `chain()` is tonejs method and allows to connect infinite number of `AudioNodes` in series, check in [docs](https://tonejs.github.io/docs/14.7.58/ToneOscillatorNode#chain). Just create new FX effect and add to chain before last output node, `Tone.Destination` in example. If you need something like `send`/`receive` bus check official tonejs [exampes](https://tonejs.github.io/examples/buses)
3. this class does not add any new functionality to standard tonejs components, its simply a wrapper for AudioNode, that allows you to connect/disconnect them from an signal chain and should work with any valid AudioNode (with `input` and `output` properties, this is WAAPI/tonejs thing).
4. node to work on must be valid `ToneAudioNode`, what means should contain `input` and `output` property, without it you get an error because you use connect FX's `input` prop (which is an output for, another in chain, `effect` prop) to node without valid `input` prop (like any `SourceNode`, e.g. `Oscillator` or even `Envelope` (has no input property, [docs](https://tonejs.github.io/docs/14.7.58/Envelope#input))).
5. you can control all `effect` parameters as in any other Tone component.

You can check my implementation of master fx chain in this [project](https://github.com/Razz21/vue-synth/blob/master/src/Synth/Effects.js). Maybe you find something useful for you.
