### ISSUE TITLE
Mobile performance optimisation/limits?

### ISSUE THREAD

**Issue by tomduncalf** [Tonejs/Tone.js#188]
Hi,

First of all, thanks for Tone.js. It's an awesome library, we recently used it to build a little festive sequencer (available at http://jingle.roli.com) and Tone made the audio part easy and fun :)

I had a question about mobile performance/optimisation, which may be a more general WebAudio performance thing, but I figured here was a good place to ask. 

Essentially, I've found that on mobile (iPhone 6S being the device I've tested with most), WebAudio seems to put quite a strain on the device. 

For that sequencer, for example, there are 4 tracks, each made up of 16 sampler nodes (one per sample, so you can trigger any sample on any track at any time and individually route the audio for each channel). This is fine on desktop browsers, but on iOS I can see the CPU usage goes up quite high as soon as the audio context is started and never goes down, regardless of whether the transport is playing. 

Fortunately, it remains just about glitch free as it is, but if I try adding in some effects nodes to each track (e.g. One delay and one phaser, per track), I get quite a few crackly glitches on the iPhone 6S during playback (and WebKit CPU use goes even higher) - even if I disable the playhead animation. 

So I suppose what I'm asking is whether I am expecting iPhone WebAudio to handle an unreasonable amount with this setup, or if it's just not a great implementation on iOS - or indeed, if there are any performance optimisations that are worth a try. For what it's worth, I tried the latest dev branch and the lookahead parameter maybe made it a little better but still some glitches, and changing the worker update interval seemed to make no difference. I did notice Blokdust glitches on iOS quite a lot, so perhaps it's just a platform limitation. 

Would be interesting to get your thoughts anyhow, and thanks again!

Tom

**Comment by tambien** [comment]
Great demo. 

I've made a wiki that i'll be adding to about [performance and best practices](https://github.com/Tonejs/Tone.js/wiki/Performance) to avoid glitches. It's not at all comprehensive, but it's got a few of the things that i've found while working with Web Audio/Tone.js. It's mostly relevant to r9 (which i'll be putting out soon), but has some general guidelines as well. 

The CPU running high even without the transport on makes sense. As soon as you start making Web Audio nodes and connecting them, the underlying audio graph is starting to process the audio. I think a lot of browsers will optimize out these silent buffers when nothing is playing, but maybe iOS is not there yet. 

There are no hard and fast limitations that i can quote you offhand. I think it depends a lot on what sort of audio processing you're doing and what else you're trying to do on the page. It'd be great to make a performance evaluation of all the Tone.js nodes, but benchmarking and performance testing Web Audio turns out to be pretty difficult. 

I hope that helps a little. Gonna close this for now since it's not a specific issue.
