### ISSUE TITLE
Cross-Origin XMLHttpRequest , issue on buffer loading

### ISSUE THREAD

**Issue by simdax** [Tonejs/Tone.js#191]
Hello !

Great lib, music sequencing made easy as possible :)

little problem : I'm using chromium and the Tone.buffer load func causes a 
```
XMLHttpRequest cannot load an error file:///home/simdax/prog/web/simdax.github.io/EVO/game/sound/mp3/button.mp3. 
Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.
```
even with a --allow-file-access-from-files

Kind of annoying, a little tip to avoid the problem would be great !

**Comment by tambien** [comment]
Looks like you're trying to load a local file. I don't think that XHR is designed to do that. 

Simple solution would be to run a local server and use that instead of trying to access files directly from your drive. 

Maybe there is some additional flags that you could start Chrome up with for even more lax security which would let you do this, but i'm not sure what those would be.
