### ISSUE TITLE
Accessing native BiquadFilterNode methods in Tone.Filter

### ISSUE THREAD

**Issue by DannyDane** [Tonejs/Tone.js#193]
Hi,

I'm trying to use Tone.Filter to draw a frequency response curve.
I see the getFrequencyResponse method in the _filters property but have no idea how to access this method in my program.

If someone could point me in the right direction what would be aweomse.

**Comment by tambien** [comment]
I've done a little investigating and it seems like this is not currently possible to add to Tone.Filter. Filter is implemented with a connected series BiquadFilterNodes which allows it to have different rolloff curves than just the basic -12db/octave. And to synchronize all of the AudioParams, each parameter has a Tone.Signal connected to it. While the spec says about `getFrequencyResponse` that the "frequency response returned must be computed with the AudioParam sampled for the current processing block". It seems like none of the browser makers have implemented this specific part of that method because having a signal connected to the params makes it return all zeros in the browsers that i tested... unless there's something that i'm overlooking. 

Otherwise, i think this would be pretty easy to implement: the magnitude response is the product of all of the magnitude responses of the connected filters and the phase is the sum of the phase responses.

**Comment by tambien** [comment]
I'm going to close this until the browser makers implement `getFrequencyResponse` while a signal is connected to the frequency AudioParam. 

Happy to revisit then. Please submit a issue to FF and Chrome if this a high priority to you.
