### ISSUE TITLE
Tone.GrainPlayer doesn't respect duration

### ISSUE THREAD

**Issue by catarak** [Tonejs/Tone.js#195]
For example,
```javascript
var player = new Tone.Player({
    url: 'https://cdn.rawgit.com/Tonejs/Tone.js/master/examples/audio/loop/bass.mp3'
}).toMaster();

Tone.Buffer.on('load', function(){
  Tone.Transport.start();
  player.start(0, '0:0:0', '16n');  
});
```
will play the very beginning of the sample for a 16th note. If you change the `Player` to a `GrainPlayer`, it will play the sample to the end. Not sure if this is the expected behavior, but there's also not any documentation for the `start` function for the `GrainPlayer`, so I'm not sure.

**Comment by tambien** [comment]
whoops! good catch. the docs for GrainPlayer are incomplete because i forgot to add `@extends {Tone.Source}` to the GrainPlayers jsdoc description. 

Currently, the [GrainPlayer's start method](https://github.com/Tonejs/Tone.js/blob/master/Tone/source/GrainPlayer.js#L130) doesn't accept a third argument, but it'd be easy enough to add that and make it more consistent with Tone.Player, so i'll put that in for the next release and update the docs to reflect that. 

For now you can just play a `16n` section like this: `player.start().stop("+16n")`

**Comment by catarak** [comment]
awesome, thanks yotam 😄
