### ISSUE TITLE
issue with triggerAttackRelease when using an argument of 0

### ISSUE THREAD

**Issue by jeremymuller** [Tonejs/Tone.js#203]
This
```javascript
synth.triggerAttackRelease("C5", 0, 0, 0.5);
```
doesn't sound the same as this:
```javascript
synth.triggerAttack("C5", 0, 0.5);
synth.triggerRelease();
```

The former just plays a note forever without ever triggering the release. I wanted to use `synth.triggerAttackRelease()` since it's a convenience method but I also wanted access to the velocity. However, I also wanted an attack and then immediately trigger the release, that's why I set duration and time as 0. When I look at this method in the code, it looks like you're just checking if the argument is undefined, so when I use 0 it fails the undefined test and moves on to something else. It might work if the test was:
```javascript
if (this.isUndef(time) || time <= 0) {
    time = this.now() + this.blockTime;
}
```
I guess it would need to be more sophisticated than this since some arguments could also be "4n". I can still use this method if I do something like this:
```javascript
synth.triggerAttackRelease("C5", 0.001, 0, 0.5);
```

**Comment by jeremymuller** [comment]
Actually, I realized I should be using the argument like:
```javascript
synth.triggerAttackRelease("C5", Tone.now(), 0, 0.5);
// or this
synth.triggerAttackRelease("C5", "+0", 0, 0.5);
```
That makes sense now, although I originally assumed that if I used the argument of `3` it meant the duration was 3 seconds. Could this type of argument be an option for a future release?

**Comment by tambien** [comment]
The first issue you were experiencing was because you were triggering `triggerAttackRelease` with a duration of 0. That means that there are 0 seconds between the start of the attack and the start of the release. So the behavior should be that you would hear nothing. In the implementation though, `triggerRelease` is only invoked when the value of the envelope is greater than 0, it was never being invoked so you were only hearing the attack. 

I've updated the docs to make a note that the duration must be greater than 0. 

Currently, the third argument (when to trigger the envelope) is already optional. With no argument it will default to the current AudioContext time. In most cases, you probably don't want to pass in 0 into the third argument since the AudioContext time of 0 is when Tone.js is first initialized and has most likely already passed by the time this part of the code is invoked since the time between loading Tone.js and executing the rest of the scripts usually takes a little time.
