### ISSUE TITLE
Tone.Time.valueOf

### ISSUE THREAD

**Issue by JackCA** [Tonejs/Tone.js#205]
Thought it might be a good idea to have a `valueOf` method on `Tone.Time` objects so that the following would evaluate correctly:

<img width="292" alt="screenshot 2017-02-27 21 38 04" src="https://cloud.githubusercontent.com/assets/296167/23393103/363fa696-fd35-11e6-9442-16b77d43a801.png">

What do you think? I will offer to implement again or you can run with it.

You could probably just alias it to `toTicks`

🎵

**Comment by tambien** [comment]
I think `eval` is the same as `valueOf`. 

`Tone.Time('0:0:1').eval()` will give you the current value in whatever units is the default type of that class, so `Tone.Frequency('4n').eval()` is the same as `Tone.Frequency('4n').toFrequency()` and `Tone.TransportTime('4n').eval()` is the same as `Tone.TransportTime('4n').toTicks()`

Might be interesting to include some comparison operators like `gt`, `lt`, etc.

**Comment by JackCA** [comment]
@tambien the difference being that `valueOf` is automatically invoked when doing comparisons. See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/valueOf

I very easily worked around this by just using `toTicks` during the comparison but I think it's pretty common to implement `valueOf` when it makes sense for things that are often compared.

implementing the individual comparison functions on the objects themselves seems interesting, but not sure what advantage over `valueOf` is especially considering the difference in effort to implement/maintain.

Anyways, thanks for hearing me out and offering your thoughts.

🤘

**Comment by tambien** [comment]
@JackCA oh interesting! I wasn't aware that valueOf has this special property. 

So probably the easiest route is just to alias `eval` with `valueOf` and it would hopefully work pretty seamlessly. I think `eval` is preferable over `toTicks` since, it will adapt to all of the classes which implement specific types like `TransportTime` and `Frequency`. Plus that fact that `toTicks` is quantized to the PPQ while `eval` doesn't have this limitation. 

Feel free to send a PR. Just make sure it's on the `dev` branch. And a couple of validation tests would be much appreciated.
