### ISSUE TITLE
Advice on drawing a playhead when using a high latencyHint

### ISSUE THREAD

**Issue by jackschaedler** [Tonejs/Tone.js#209]
First off, thanks for making Tone.js available for everyone on github. It's a really wonderful library!

I have what may potentially be a dumb question, so here goes:

I'd like to draw a playhead on my site, and it would be ideal if I could use the Sequence/Part progress() function to do so. When using a `latencyHint` of `fastest`, this works very well, and I am able to very smoothly animate a playhead. If I start increasing the latency, the animation gets very chunky. For example, using the `playback` `latencyHint` results in a really choppy experience.

See fiddle: https://jsfiddle.net/1euz7nea/

I'm wondering what the preferred way to create something like a playhead might me. Should I be using Tone.Draw() instead? Any advice would be greatly appreciated.

**Comment by tambien** [comment]
Good question. Synchronizing visuals and audio is not trivial at all since they have different timing requirements and update rates. `latencyHint` is about balancing performance and update rate. So `latencyHint='fastest'` would update very often but be more taxing on the performance while `latencyHint='playback'` should give you better audio performance by updating less often. 

A couple of simple suggestions would be to just use a `latencyHint` which gives you decent performance and good enough visual updating. Alternatively you could try adding a css transition or tweening to smooth the jumps between updates. `latencyHint='playback'` updates every 0.5 seconds, so you could use 500ms as your tweening value to smooth jumps. 

The last suggestion would be to just compute your own progress since you can get the duration of the Tone.Sequence loop and you know the start time of the Transport.

**Comment by jackschaedler** [comment]
@tambien That makes perfect sense, thanks for the very thorough answer!
