### ISSUE TITLE
Add a `duration` argument to Tone.MultiPlayer.startLoop()

### ISSUE THREAD

**Issue by jackschaedler** [Tonejs/Tone.js#215]
It would be nice to have a `duration` argument to Tone.MultiPlayer.startLoop(). When playing back looped samples it would be convenient to be able to schedule the stop time at the same time as you schedule the start time. You can fake this by calling stop() on the MultiPlayer immediately after calling startLoop(), but this isn't a satisfactory solution because stop() will immediately remove the playing source from the list of active sources, making any subsequent calls to stopAll() ignore a potentially still playing source (if the stop time was scheduled far into the future).

Is there any reason why it would be a bad idea to allow specifying a duration here? I'm happy to make a PR if this makes sense.

**Comment by tambien** [comment]
Yeah good point. MultiPlayer's `start` methods could use a little revisiting I think. Currently `startLoop` takes an optional 7 arguments which is well above most "best-practices" guidelines, so i'm reticent to add an 8th argument. One solution is to break it apart into multiple `startLoop` methods like: `startLoopBetween` or `startLoopForDuration`. Best would be if it were more consistent with the other `start` APIs which are more typically something like: `(time, offset, duration)`. 

I think returning the Tone.BufferSource would be a good option since it would let the caller modify any attribute of that BufferSource without needing to pass it all in as arguments. Maybe also allowing the parameters to be passed in as an object would alleviate some of the parameter bloat. 

As far as your second question, currently the regular `start` method has a `duration` argument but internally it just called `stop` which has the same problem that you were mentioning of calling `stop` externally. 

Not sure what the best solution is, but i think MultiPlayer is definitely worth revisiting. Could you describe your use case a little more or share some code?

**Comment by jas-ableton** [comment]
Hi @tambien, thanks for the response, and sorry for the very tardy reply! The use case is for building something like a piano roll where the MultiPlayer is responsible for playing back a looping piece of audio for a duration which is known a-priori when the note starts.

`startLoopForDuration` or something similar would be ideal. 

I also really like the pattern of passing a package of parameters in an object. Getting the argument ordering incorrect can lead to some tricky bugs.
