### ISSUE TITLE
Tone.Follower to ramp an input signal

### ISSUE THREAD

**Issue by LennysLounge** [Tonejs/Tone.js#236]
I have been trying to controll the gain of a source by using a square lfo.
However this will create an clicking sound whenever the gain changes from 0 to 1.
I want to reduce this by ramping the gain using a follower however this doesnt seam to work.
```
var gain = new Tone.Gain().toMaster();
var osc = new Tone.Oscillator(440).start();
var lfo = new Tone.LFO(0.5).start();
lfo.type = "square";
var follower = new Tone.Follower();

osc.connect( gain );

lfo.connect( follower );
follower.connect( gain.gain );
```

**Comment by tambien** [comment]
This seems related to [this issue](https://github.com/Tonejs/Tone.js/issues/125). 

Since the square wave does not ramp between 0 and 1, but instead ramps between a something like 0.15 to 0.85, it might not produce the desired effect. 

I think the more reliable way to do this would be use Tone.Clock or Tone.Loop and schedule the ramp from within a callback

```javascript
let highGain = false
const clock = Tone.Clock(time => {
  highGain = !highGain
  //apply a 10ms linear ramp between the values
  gain.gain.linearRampTo(highGain ? 1 : 0, 0.01, time)
}).start()
```
