### ISSUE TITLE
Transport.scheduleRepeat breaks in Firefox when startTime is 0.

### ISSUE THREAD

**Issue by AshlinDuncan** [Tonejs/Tone.js#239]
The code below is not working in Firefox:
```
var synth = new Tone.Synth().toMaster();

Tone.Transport.scheduleRepeat(function(time){
	console.log(time);
	synth.triggerAttack('A2', time);
}, "8n");

Tone.Transport.start();
```
The `triggerAttack()` method seems to be unable to handle the passed in `time` value, since the error appears only when that method is called, and passing in a static time (ex: `triggerAttack('A2', '2')`) works fine.

Weirdly, it works fine when a non-zero `startTime` is specified, i.e.
```
Tone.Transport.scheduleRepeat(function(time){
    //...
}, "8n", "1m");
```

Works perfectly in Chrome.

Anyone have a workaround? Or am I doing something wrong?

**Comment by tambien** [comment]
Seems like there's two issues in this one. One is that Firefox is throwing an error the first time that the synth is being triggered. This actually goes away if you schedule the transport to start slightly in the future: `Transport.start("+0.1")`. This seems like it's because it's trying to schedule something at a time which is slightly in the past. According to the spec, it's not supposed to throw an error, just clamp to the current time. I need to investigate a little more. 

Second issue is that Clock doesn't have a try/catch block to catch this error so it just keeps trying to reschedule at the same time and the clock is unable to progress forward past this error time. This second error i fixed. So it will throw a single error if it's unable to schedule the event, but from there, it will be able to schedule the event.

**Comment by AshlinDuncan** [comment]
Thanks for taking a look! Keep me posted :)
