### ISSUE TITLE
Issue with the Transport loop

### ISSUE THREAD

**Issue by maximedupre** [Tonejs/Tone.js#265]
Let's say the Transport is set to loop from 5 seconds to 10 seconds. If I change it's position in seconds to 20 seconds while it is started, it will immediately change it's position to 5 seconds. The issue is that we can't seek to after the loop. We can only seek within the loop or before the loop. If the transport is paused or stopped, this bug doesn't occur.

I saw in another ticket that you have modelled the loop behaviour of Ableton and Ableton does not behave like this, this is why I think it's a bug.

**Comment by tambien** [comment]
Related to #223, i changed the behavior away from the Ableton model so that now the Transport will not go past the loopEnd time while loop=true.  Closing this issue would reopen #223. To accomplish what you're trying to do, you could  set Transport.loop to false, when moving the seconds outside of the loop range. 

Changing the position while the Transport is paused/stopped should not readjust the position to the loop start. That will only happen when the Transport is playing.

**Comment by maximedupre** [comment]
Hey @tambien,

I would like to clarify a behaviour of the Transport looping. If the Transport is started at 10 seconds and we activate the loop selector, which goes from 2 seconds to 5 seconds, the Transport will immediately jump to 2 seconds.

Is your position on this subject that this is the expected behaviour? Is it impossible to have both the looping activated and the transport that is continuing on its current path (meaning that in the example the transport would continue to 11, 12, 13, etc, without being displaced to 2)?

Thanks

**Comment by tambien** [comment]
That's right. The current behavior is if `loop = true`, it is looping between the two loop points.
