### ISSUE TITLE
Cracklings due to CPU Leak after 1-2 minutes

### ISSUE THREAD

**Issue by dotgreg** [Tonejs/Tone.js#274]
Hello, first thanks for that amazing library.

I am working on an [experimentation ](https://github.com/dotgreg/XinDaw) to create a live coding environment inside the web browser using Tonejs. I needed something that could be stable over the time of a performance, maybe 1-2h first.

However while working on Tonejs, I realized the sound was rapidly crackling after 1-3 minutes of playing and modifying the transport. I started to read on that subject, trying to isolate the cause, apply [the best performances practices](https://github.com/Tonejs/Tone.js/wiki/Performance) from the tonejs wiki, from now without much success. But I managed to get some useful informations and a good demo to reproduce the problem.

Demo : https://jsfiddle.net/dotgreg/8sst7trg/66/ I add here 30 synths with random parameters on the transport. On my (quite beefy) computer (Dell xps15 9560, i7, 16gb ram), when I open chrome task Manager, I see the CPU usage of the tabs constantly raising from 1-2% to reach 13% after only a minute (crackling start at 9%).

![screenclip](https://user-images.githubusercontent.com/2981891/33238309-3dcf606a-d2c6-11e7-8806-fc3fc428c0a6.png)

Thinking it was maybe due to tonejs implementation, I decided to do some other tests on other libraries and got surprisingly the same problem on the testing page (http://codecur.io/us/projects/song-demo) of [WAD](https://github.com/rserota/wad). The only difference is that WAD follow the same CPU raise to reach 12% CPU but then fall again to 3% after reaching the pike.

![screenclip](https://user-images.githubusercontent.com/2981891/33238373-57273a6e-d2c7-11e7-8e79-6e636b38ad99.png)

I tested that fiddle on many devices and browsers to make sure my setup is not the problem, same results all the time (android chrome/native browser, chrome windows, microsoft edge windows).

I am also surprised by the lack of documentation or discussion on that subject, does anybody has that problem? Am I doing something wrong? (but looks Im really doing something fairly simple on my demo). 
Is that a problem due to the tonejs implementation of the web audio api or a problem of performance of the web audio api itself?
Are my expectations of the web audio api too high (creating a live coding environment) for what it can actually do today? 

Thanks for your help :)

**Comment by tambien** [comment]
Thanks for the thorough investigation into the issue. Looks like the problem might not be with Tone.PluckSynth. If i switch it to a Tone.Synth, (https://jsfiddle.net/814jLvs8/) there's no crackling. I'm able to run the page for many minutes and not hear a problem. 

The way the PluckSynth works is using Karplus-Strong synthesis using a LowPassCombFilter. I've seen a few issues with feedback delays in Web Audio implementations. I'm waiting anxiously for the AudioWorklet so i can replace this component. Though, I've never seen this specific problem that the page stops working consistently after a couple of minutes. 

I will open another issue specifically for the PluckSynth. My guess is that the feedback delay might be introducing floating point errors somewhere. I would be great to distill these issues and submit the bug to the browser makers. 

If you're after this specific synth type, check out this [Pluck String Node](https://mohayonao.github.io/pluck-string-node/) which uses a variation on the Karplus-Strong synthesis to good effect.

**Comment by dotgreg** [comment]
Thanks for the fast answer, Pluck was indeed the culprit here :)

As that behavior was more general on my system, I spent a day as well trying to figure out what was wrong in my code, as those pikes would also appears. 

My CPU constant load raise was due to the fact I was updating elements on the fly on the transport by deleting and recreating them (a constraint of how I designed my system). But by doing that, I forgot to dispose() all the elements (Synths, effects, etc...) in the deleted code. Which cluttered the CPU and memory after a few modifications.

Cracklings are due to CPU not being able to follow, and not disposing/cleaning everything not needed anymore clutters CPU very fast. If it is not that obvious, maybe something worth mentionning the performance wiki.

**Comment by brokyo** [comment]
Excited to find this thread as I've been having a very similar issue but with oscillators and effects rather than synths and I'm sort of stumped.

I'm working on a [procedural drone](https://healingcodes.under-construction.club/) that periodically starts an oscillator connected to a handful effects. As I near 30 oscillators in the system I get a CPU spike and audio cut out. 

The general chain looks like this:

**Osc**
`Oscillator > AutoPanner > Tremolo > Vibrato > Chorus > Gain (Out Node)`

which is connected to a main effects chain:

**Main Patch**
`Gain (In Node) > Freeverb > AutoPanner > Gain > Master`

(I'm not super proficient with performance profiling but here's a similar image if it's of any use)
<img width="1274" alt="oscillator_limit_" src="https://user-images.githubusercontent.com/1268510/37851129-1b89cffa-2eb4-11e8-92d8-e022e2232db3.png">

I recognize this seems like a weird approach but I'm randomly assigning values to each effect in each oscillator chain to make a more interesting drone so this setup is essential under my current thinking.

I set up a [codepen to debug this](https://codepen.io/brokyo/pen/gexpQm?editors=1011) and if I remove all the effects I can add a huge number of oscillators so I know it's something with the effects or my approach to them. Right now I'm just brute forcing this by commenting out effects and seeing performance but this doesn't feeling like a great system. Is there a better way to approach this and end up with less CPU usage? Am I just hitting the best I can realistically expect from the browser? Any feedback would be super helpful as I'm feeling clueless :)

[[also @dotgreg I love XinDaw. I was working on an adjacent idea [here](https://under-construction.club/synth) (in the 'compose' tab.) I see you stopped development - did you ever get anywhere with this? I'd love to be able to have proper live updating...]]
