### ISSUE TITLE
Timing not working?

### ISSUE THREAD

**Issue by trusktr** [Tonejs/Tone.js#281]
I'm not sure, but timing seems to be either not working, or not intuitive.

For example, here I expect four notes to evenly fire within one second:

https://jsfiddle.net/zxsthhmq/72/

But that doesn't happen, instead the notes fire on some other schedule. In fact, only three notes ever fire (from what I can hear).

**Comment by tambien** [comment]
It takes a moment before that code to executed. By the time the first 'triggerAttackRelease' is invoked, it's scheduled time of 0 has already passed. Since you can't schedule things in the past,  either it's cut short or squelched entirely by the second event.

The surefire way to avoid this is to get the AudioContext time right before you want to schedule something (with `Tone.now()`) and schedule all of your events relative to that time. 

https://jsfiddle.net/zxsthhmq/75/

**Comment by trusktr** [comment]
If it helps, I'm in Chome 62.

**Comment by tambien** [comment]
I just kept the values in your original example which have the time values **0, 0.25, 0.75** and **1**, so they are not evenly spaced to begin with. If you'd like it to be evenly spaced, try [these values](https://jsfiddle.net/zxsthhmq/76/)

Removing 'now' from the example code would be difficult. One of the fundamental difficulties of working with Web Audio is grappling with the synchronous timing of audio and the asynchronous timing of javascript. Chris Wilson has [a widely-cited article](https://www.html5rocks.com/en/tutorials/audio/scheduling/) on this challenge. If you have improvements to the API or examples of Web Audio code that accomplished this better, i'm open to suggestions and PRs.

There's a couple of things in Tone.js that might be useful: [Tone.Offline](https://tonejs.github.io/docs/r11/Tone#offline-static) will give you the behavior which is closer to what you're describing because you can schedule everything in advance and then 'render' the audio out. Tone.Transport offers a way to schedule events along a seekable, loopable timeline that is separate from the AudioContext time and can be started and stopped. I would also point out the 'now-relative' timing which can be passed into any timing parameter. So you could rewrite your example [like this](https://jsfiddle.net/zxsthhmq/78/) to accomplish the same thing.
