### ISSUE TITLE
Tone.Sequence not running on iOS

### ISSUE THREAD

**Issue by AvneeshSarwate** [Tonejs/Tone.js#284]
Basic example based on the StartAudioContext basic.html example:
https://gist.github.com/AvneeshSarwate/5124424b2b64758d6d246c1930b05eb4

On Chrome for the desktop and on Android, the note strings appear in the bottom left of the window and update as expected, but in iOS 11 (both Chrome and Safari), the first note is displayed and then it does not change.

**Comment by tambien** [comment]
You are creating a new audio context and then passing it into StartAudioContext. So that AudioContext is probably being started by the user action, but Tone.js' context is still 'suspended'. 

Try changing [this line](https://gist.github.com/AvneeshSarwate/5124424b2b64758d6d246c1930b05eb4#file-basic-html-L52) to `StartAudioContext(Tone.context, ".starterButton")`. 

Let me know if that works for you

**Comment by AvneeshSarwate** [comment]
Ahh that did it! Thanks!
