### ISSUE TITLE
Should `connect` return the destination node to allow for chained calls?

### ISSUE THREAD

**Issue by jackschaedler** [Tonejs/Tone.js#291]
https://github.com/Tonejs/Tone.js/blob/74556314c116cd254c3935b2e2529adf86814226/Tone/core/Context.js#L521

When passing in your own audioContext to Tone, it might be nice if the connect shims returned the return value of the native function, which would allow clients to continue to chain `connect` calls when using Tone. (https://developer.mozilla.org/en-US/docs/Web/API/AudioNode/connect)

There might be a good argument for not doing this that I'm overlooking.

**Comment by tambien** [comment]
yeah i've been thinking about this since they added it to the specification and planning on making that update. and simultaneously updating `Tone.prototype.connect` to be consistent with the WAA and return the node that you're connecting to instead of `this`. 

My only hesitation is that i often use this pattern in the examples and all over the codebase: 

```javascript
const thing = new Tone.Thing().connect(otherThing)
```

And then should `toMaster()` return Tone.Master...?

Though, regarding your issue, I will start by updating that overwritten `AudioNode.prototype.connect` method right away so that i stay consistent with the API.
