### ISSUE TITLE
Loop/Transport Problem

### ISSUE THREAD

**Issue by phesterman** [Tonejs/Tone.js#303]
Here's what happens:

1. create a loop;
2. schedule an event after its last iteration;
3. start the transport;
4. the loop loops as expected, the scheduled event occurs as expected;
5. stop, then cancel the transport;
6. create a new loop, and schedule an event after it;
7. start the transport;
8. both loops play simultaneously!  Tone.Transport.cancel() doesn't seem to have had any effect.

If you don't schedule the event after the loop, everything works as you'd expect.  Maybe I’m missing the boat somehow, but I’ve only had this problem with r11...I'm not sure about r10, but it worked correctly in r9.

http://jsfiddle.net/phesterman/ma10vcLk/

Thanks,

Peter

**Comment by tambien** [comment]
Thanks for the bug report. I finally got a chance to dive into the issue. Seems like the problem was caused by the fact that `cancel` was removing the scheduled events, but not disposing of the underlying `TransportRepeatEvent` which had an event listener for the Transport's `start` and would add itself back to the scheduled events when the Transport was started. I will push this fix shortly along with a test validating those changes. 

Your use-case brings up another issue related to how to deal with the Loop event once the underlying Transport events have been cancelled. I think ideally the Loop.state would report itself as 'stopped', but since the Loop is not notified that the Transport event has been removed. Loop.state will return `started` yet it will make no sound. I will look into this a little further
