### ISSUE TITLE
Transport pause and start events are not triggered when very close to each other

### ISSUE THREAD

**Issue by salomvary** [Tonejs/Tone.js#308]
Transport does trigger pause and start events when `pause()` and `start()` calls happen within the same event loop tick or within a very short time.

I would expect all three events to be triggered in all scenarios below:

```js
Tone.Transport.on('stop', () => console.log('stop'));
Tone.Transport.on('pause', () => console.log('pause'));
Tone.Transport.on('start', () => console.log('start'));

// Logs start only
Tone.Transport.start();
Tone.Transport.pause();
Tone.Transport.start();

// Logs start only
Tone.Transport.start();
setTimeout(() => {
  Tone.Transport.pause();
  setTimeout(() => {
    Tone.Transport.start();
  }, 1);
}, 1);

// Logs start pause start
Tone.Transport.start();
setTimeout(() => {
  Tone.Transport.pause();
  setTimeout(() => {
    Tone.Transport.start();
  }, 100);
}, 100);

```

https://jsfiddle.net/4prj98rh/11/

**Comment by tchakabam** [comment]
Seeing this too, had to use workarounds, but is rather disappointing :) 

Can someone give a hint where a fix may be done in Tone?

**Comment by tambien** [comment]
A change in event is only tested and the event is triggered every update callback. That code is handled by the [Clock](https://github.com/Tonejs/Tone.js/blob/dev/Tone/core/Clock.js#L256). The default update rate for the clock is 0.033s. so in the current implementation you're limited to a state clock state change every ~33ms. 

What is your use case that you need to start, pause and restart the clock immediately?

**Comment by tambien** [comment]
Made an update yesterday which would allow state changes which are closer together than the update interval. [Here's a test](https://github.com/Tonejs/Tone.js/blob/dev/test/core/Clock.js#L397) validating that change. Though the events still cannot be scheduled immediately like you have in your first example. Not sure if that's an edge-case worth addressing right not since i can't think of a use case for it.

**Comment by tchakabam** [comment]
Hey @tambien 

Awesome, thanks a lot! We will try this.

However, in fact, I realized myself we also need to for example schedule play calls a little bit (`+1`) in front of current audio clock time relative to pause calls done on the same scheduling tick :) Imo that solves all of the issues. I understand and it make sense that commands on the transport scheduled on the same time and resulting in unchanged state don't actually triger a state change event. The problem was doing scheduling of commands right on our side as well.
