### ISSUE TITLE
Tone.PolySynth and Tone.Sampler duration

### ISSUE THREAD

**Issue by bgarton** [Tonejs/Tone.js#310]
Ok, I set up a polyphonic sampler like this:

var polysamp = new Tone.PolySynth(3,  Tone.Sampler, {
      "C3": "bradaaah1.wav",
      "C4": "bradaaah2.wav"
   } );

and then I want to play a note with it:

polysamp.triggerAttackRelease("F3", 0.1);

but instead of the 0.1 duration I get the entire sample.  I've tried setting the 'release' value on the PolySynth, tried scheduling triggerAttack and triggerRelease separately, but it still insists on playing the whole thing.

brad

PS:  I hope this is the right place to post these queries.  Are there other forums for tone.js I should know about?

**Comment by tambien** [comment]
In the latest version, Sampler should be used without PolySynth since it is already fully polyphonic. (i should make it throw an error if trying to use it in the PolySynth constructor). 

Feel free to post general questions (non bugs/issues) on the [tone.js forum](https://groups.google.com/forum/#!forum/tonejs).

**Comment by tambien** [comment]
In the latest dev build it will [throw an error](https://github.com/Tonejs/Tone.js/blob/dev/Tone/instrument/PolySynth.js#L60) if you try to use it with a class which doesn't extend Tone.Monophonic to avoid this confusion in the future
