### ISSUE TITLE
Unable to use Tone.Transport.stop() Stop instantly if Tone.Transport start with offset

### ISSUE THREAD

**Issue by cliftonshum** [Tonejs/Tone.js#319]
Hi,

Here is a simple jsfiddle which show this issue:
https://jsfiddle.net/s2b24dt6/20/

After selecting 2 local wav files, 
**CASE1:** if I press "Loop Part1" -> press "Stop" after few seconds ->Sound stop instantly (Perfect!)
**CASE2:** if I press "Loop Part2" -> press "Stop" after few seconds ->Sound will stop after the loop is ended (Not expected, i through it would stop instantly just like first case)
**CASE3:** if I press "Loop All Part" -> press "Stop" while Part1 is playing ->Sound stop instantly (Perfect!)
**CASE4:** if I press "Loop All Part" -> press "Stop" while Part2 is playing ->Sound will stop after the loop is ended (Not expected, i through it would also stop instantly )

Thanks,
Clifton

**Comment by deanslamajr** [comment]
I've encountered this issue as well. It seems to occur whenever `Tone.Player#sync` is used to associated more than a single source with `Tone.transport`.

I've put together a jsfiddle that demonstrates the bug of `Tone.Transport#stop` failing to stop playback of _some_ of the synced sources:

https://jsfiddle.net/h5usLdu9/

**Comment by tambien** [comment]
Thank you for the test cases. Appears to be fixed in the latest dev release. Here's [a fork of the jsfiddle](https://jsfiddle.net/L8me7tnu/) with the latest build. 

It would be great to try and formalize these these test cases and add it to the [test/Player](https://github.com/Tonejs/Tone.js/blob/dev/test/source/Player.js) to make sure there is no regression in the future.
