### ISSUE TITLE
LFO modifies the sound of the node it is attached to, even if the former is not started

### ISSUE THREAD

**Issue by maximedupre** [Tonejs/Tone.js#321]
https://jsfiddle.net/25qc2L74/16/

It is unexpected to me that, If you comment `lfo.connect(oscillator.output)`, the sound changes. Why does the LFO have an impact on the sound even when it's not started?

**Edit**

My problem is better represented by this example:

https://jsfiddle.net/4v6norrr/2/

Please comment the `lfo.connect(envelope)` line and listen before/after.

The same problem occurs, but it is more similar to my use case. An envelope with no input source should not produce any sound, but when a LFO is attached to it, the signal is modified and produces what seems to be very low frequencies (perhaps the frequencies of the LFO).

**Comment by tambien** [comment]
As far as i can tell, the LFO is working as expected. If the desired outcome of connecting the LFO to the `oscillator.output` is to make a volume tremolo, try connecting it to `oscillator.volume` like [so](https://jsfiddle.net/a657jrqz/). 

I believe what we're hearing has to do with the fact that until it is started, the LFO's resting value is at `phase 0`, and with the default arguments (min=0, max=1), it means it outputs is DC offset of 0.5. If you connect that indirectly to the speakers like in your second example, you'll hear a low click and if that is summing with the oscillator output, you will hear some distortion. To make the LFO rest at 0, set the [min and max to -1 and 1](https://jsfiddle.net/6t19wder/1/). or adjust the phase of the lfo, to 270 degrees so that it rests at the min value.

**Comment by maximedupre** [comment]
[Setting the phase to 270 does not seem to help](https://jsfiddle.net/6t19wder/4/), but setting the min and max to -1 and 1 does as you said.

**Comment by tambien** [comment]
If the LFO type is set to `sine` at phase 0, the oscillator will rest half way between the min and the max. That means that at 90 and 270 the oscillator will be at the max and min of it's oscillator
