### ISSUE TITLE
Sampler is creating sounds in the incorrect octave, in some cases

### ISSUE THREAD

**Issue by andygock** [Tonejs/Tone.js#339]
Hi,

Could someone check this?

I've made a sampler with the following samples:

```js
{
                E3: "E3.mp3",
                A4: "A4.mp3",
                D4: "D4.mp3",
                G4: "G4.mp3",
                B5: "B5.mp3",
                E5: "E5.mp3",
                A6: "A6.mp3",
                D6: "D6.mp3",
                G6: "G6.mp3"
}
```

When attempting to `triggerAttack("C5")` - it ends up playing a note which is actually `C4`. When playing a sequence `["D4", "F4", "A5", "C5"]` - first three notes are correct, but C5 is incorrect. JS Fiddle below:

https://jsfiddle.net/andygock/krx2Lb73/

Thanks

**Comment by tambien** [comment]
i was confused myself for a little while and i think i understand the issue. If i understand correctly, you're trying to play a Dm7 with close spacing right? The correct pitches for that would be ["D4", "F4", "_A4_", "C5"]. (A4 **not** A5). 

https://jsfiddle.net/rgh1kpko/

It seems like the problem is that you're making the octaves change at the A's, but they actually change at the Cs. 

In fact the wikipedia article on [Scientific Pitch Notation](https://en.wikipedia.org/wiki/Scientific_pitch_notation) says this:

>The octave number increases by 1 upon an ascension from B to C (and not from G♯ to A, as one might expect).

😋

**Comment by andygock** [comment]
Ah yes, you're exactly right. Silly me, I didn't realise the notation changed numbers from B to C. Thanks!
