### ISSUE TITLE
Worse performance and audio degradation upgrading from v11 to v12

### ISSUE THREAD

**Issue by Ecafracs** [Tonejs/Tone.js#354]
I was rewriting my app in vue (coming from angular) and noticed that the audio was noticeably worse, both in terms of number of dropped notes and sound quality. (A sawtooth sound I was using sounded noticeably thinner.) It turned out I had pulled the newer v12 for my vue project while my angular project was still on v11.  When I updated my angular project to v12, it now exhibits the same issues.  

I had also noticed that v11 showed me warnings of events being scheduled before the current time (which seems to have been removed in v12), so while investigating that, I started instrumenting my app to count the number of times that the callback in a Tone.Part or Tone.Loop is called with a time that was earlier than the current time. This happened to some extent, and varied depending on the load (based on number of notes, tempo, and animating divs) with v11.  When I then updated to v12 (0.12.80), the number of times this happens exploded, regardless of the load.  It seems like practically every time the callback is called, the time passed in is between 20ms and 200ms (and occasionally much greater) before the current time.

**Comment by tambien** [comment]
could you please post some reference code or an example of what you’re referring to.

**Comment by Ecafracs** [comment]
Not sure if you want to go through my project's code, but it will take me some time to create an isolated example.  

But in case you want to see it in the meantime:
https://github.com/FlatThirteen/flat-thirteen

The code that is logging the issue I'm seeing is here:
https://github.com/FlatThirteen/flat-thirteen/blob/bd6336bf21bb1d380ecb3a83f886310ff69d5b34/src/client/common/core/transport.service.ts#L127

To see the issue in action:
You start the server via "yarn start"
Go to: http://localhost:3000/backing
Push the green play button.  Watch the red number(s) in the lower right go up as more callback events are called with a time before the current time.
You can adjust the tempo or add/remove notes, and disable the graphic effects with the space bar, to vary the load.  You can also change the latencyHint provided to AudioContext 
Update the tone package to v12 to see how much worse it gets.

**Comment by tambien** [comment]
One thing to point out about [this line](https://github.com/FlatThirteen/flat-thirteen/blob/bd6336bf21bb1d380ecb3a83f886310ff69d5b34/src/client/common/core/transport.service.ts#L129) is that Tone.now() returns the [currentTime + lookAhead](https://github.com/Tonejs/Tone.js/blob/dev/Tone/core/Context.js#L131). So it might still be ahead of the currentTime (which you can find by checking `Tone.context.currentTime`).

**Comment by Ecafracs** [comment]
That definitely explains a lot about what I'm seeing in my debug logging.  The documentation on this page could probably make that a lot clearer: https://tonejs.github.io/docs/r12/Tone

It doesn't explain the difference in actual audio quality I'm experiencing between the two versions though.

**Comment by tambien** [comment]
it'd be really helpful to debug the issue if you could host a minimal example on jsfiddle with the synths/effects that sound different between the two versions. i don't have time to build and debug the project that you posted.

**Comment by Ecafracs** [comment]
V11: https://jsfiddle.net/Ecafracs/9una8zbt/
V12: https://jsfiddle.net/Ecafracs/r62ub31k/

The sound is noticeably different in v12, less full sounding.
Turning on the cowbell and going to, say, tempo 300 breaks the audio in v12 much easier than v11.

**Comment by tambien** [comment]
thanks for the examples, makes it much clearer what you're referring to. if i remember correctly between r11->r12 i changed the decay curve to be setTargetAtTime instead of linearRampToValueAtTime, so your synth settings might need to be adjusted between the two versions. the decay portion of the synth has overall less energy which is probably why it sounds thinner. i went with this decay since it seemed like most synths used this type of exponential decay over a linear decay. 

I'll add the ability to set the decay curve similar to the ability to set the attack and release curves in this next version. 

regarding the dropping notes, i don't think it's a performance thing. i think it might have to do with rounding errors between the upgraded version of Tone.Clock. i think it's possible that it skips a tick occasionally since it seems to happen more as the clock progresses further.

**Comment by tambien** [comment]
@Ecafracs try your example the latest '[dev](https://unpkg.com/tone@13.1.22/build/Tone.js)' build (will be published very shortly) and `{'decayCurve' : 'linear'}` in your synth envelopes and let me know if that has that tone that you like from r11.

**Comment by Ecafracs** [comment]
I created another JSFiddle with r13 and it still sounds the same as r12:
r13: https://jsfiddle.net/Ecafracs/stq8udL2/
r12: https://jsfiddle.net/Ecafracs/r62ub31k/
r11: https://jsfiddle.net/Ecafracs/9una8zbt/

**Comment by tambien** [comment]
seems like my envelope theory wasn't right. turns out i changed the decay envelope type before r11. To my ears it sounds like most of the 'thinness' change you're referring to is from the FatOscillator in the Synth

I think i found the culprit: I introduced a synth optimization in r12 where the oscillator starts and stops while silent instead of continuously running. That made a difference with the FatOscillator since some of it's fatness came from the fact that the phases of it's oscillators were out of alignment. the fix is to start each of the oscillators at a different phase rotation, this reintroduces some of the thickness you were talking about.
