### ISSUE TITLE
repeated Transport pause() and start() causes degraded performance

### ISSUE THREAD

**Issue by muhengseow** [Tonejs/Tone.js#370]
My use case is very similar to the Transport Sync demo. I want to handle scenarios where the audio sees heavy replay, multiple seeks, etc. as users may want to edit the playback and fast-forward/rewind to listen to their changes. Over time, the performance slowly degrades after multiple Transport.pause() and Transport.start().

Easy repro:
```
let toggle = false;
setInterval(() => {
    toggle ? Transport.pause() : Transport.start();
    toggle = !toggle;
}, 50);
```
and let it run for a couple minutes.

On the Transport Sync demo `daw.html` after about ~1000 toggles the animation freezes running on a MacBook Pro (Retina, 13-inch, Early 2015). While this is a lot of playing and pausing, more complicated animations or audio tracks running on a lower powered device will freeze up a lot earlier.

This appears to be due to the internal state tracked by the underlying Clock/TickState/Timelines from the Transport on every pause and start. I'm still reading through the code here, but it doesn't seem necessary to track this state once play has resumed. Calling Transport.stop() clears all these internal events and restores performance, but also resets the timeline to the beginning, so this is only doable if we want to stop and reset all sources.

**Comment by muhengseow** [comment]
Looks like this is because internally pause() and start() and tracked as unique events on the Timeline. After many pauses and starts, the Timeline becomes fairly large. At around 200-250 events I was noticing degraded performance.

**Comment by tambien** [comment]
@muhengseow Thanks for the issue. 

I think the degradation doesn't necessarily have to do with storing all the previous events: since Tone.Timeline uses binary search, inserting and finding an item event among 100,000 events should only be a dozen or so function calls. 

What it probably has to do with is Tone.TickSource which manages the tick counter accounting for bpm automation. 'Pause' is sort of a difficult case since bpm automation events can still be added, so it can't precompute the number of ticks at the moment the event is inserted like it can with 'stop' and 'start'. 'stop's ticks are always equal to 0 and 'start's is either equal to 0 or to the passed in tick offset value. This means that to calculate the current number of ticks, it must begin it's computation from the last 'stop' event which has a known value of 0 and then sum together all the elapsed ticks accounting for 'pause' events. 

This is done at each tick of the clock (about 400 times a second depending on your bpm and PPQ), so i can see why it might degrade performance. In (what i thought was) a typical case, this isn't very many calculations, but in your use-case, it's got to account for 1000 stop/pause events. 

I can't think of a way where it doesn't need to recompute over all of the start/pauses, since it's important that it accounts for any changes to the bpm automation curve. Though, there maybe some simple optimizations which would cut down on a lot of processing. Memoizing values along the bpm automation timeline would help a lot, maybe also being able to query the bpm timeline for any scheduled events within some period of time and performing some simplified calculations given no automations.

i'll start by making a test case which hits this performance problem so i can validate any optimizations that i make.

**Comment by styk-tv** [comment]
Could this be related to shifting timeline during playback issue and not reset during stop i discovered in #626 ?

**Comment by tambien** [comment]
@styk-tv no this has to do with how pause is implemented. In order to compute the total paused duration, it's got to look back and sum all of the paused times from the last 'stop' event. If you've got hundreds of 'pause' events, this gets computed each time to enable maximum flexibility with tempo scheduling, which causes the performance issue.

**Comment by arpo** [comment]
Is this still an issue?

**Comment by muhengseow** [comment]
> Is this still an issue?

Yes. I just tried repeating Tone.Transport.pause()/start() at https://tonejs.github.io/examples/daw and this problem still exists.

**Comment by yifanmai** [comment]
Hi @tambien, I'm a new contributor and would like to tackle this issue. I tried implementing the memoization approach in #1004.

This approach assumes that events added to TickSource are in strictly increasing chronological order; if this is not true then we'll have to invalidate the memoized values whenever an event is added out of order.

I've manually tested that this approach works on the DAW example.

**Comment by tambien** [comment]
Thank you for that contribution @yifanmai 

It does in fact seem like the assumption that the events are always increasing is sort of baked into the code already. Looking at it now, every call to [`setTicksAtTime`](https://github.com/Tonejs/Tone.js/blob/da733856203227d9ff837cf62e830b4b0b149e47/Tone/core/clock/TickSource.ts#L294-L302) also clears the timeline from that point forward using a call to `this._tickOffset.cancel(time)`. 

I'll add some thoughts to the PR. It'd be good to include some tests that test against this assumption.
