### ISSUE TITLE
Tone.Sampler()  envelope attack > 1 sec?

### ISSUE THREAD

**Issue by TomAuger** [Tonejs/Tone.js#373]
` let sampler = new Tone.Sampler(partials, {
	            baseUrl: "myDir/",
	            onload: this.onInstrumentReady,
	            attack: 100000000000, // I've tried all sorts of values here (1, 10, 100, 1000...) 
	            release: 100000 // same here
            });
            sampler.connect(this.audioChain.mainGain);

sampler.triggerAttackRelease(frequency, 10, Tone.now(), velocity);`

I'm trying to have the Sampler a long attack (like 4-5 seconds), but can't seem to get anything past about 1 second.

**Comment by tambien** [comment]
I'm not able to recreate this issue [here](https://jsfiddle.net/yLx57mkd/). I hear the envelope fade in. 

The issue might be related to #363 if you're using the current release and passing in a velocity value. Try using the latest build `tone@next` and see if it still has the issue.

**Comment by TomAuger** [comment]
Hi @tambien thanks for the quick response!

Actually, using your same fiddle, I'm totally able to reproduce the issue. Try changing the release value from 2 to 20, 200 or even 2000 - one would expect an extremely long release, but it sounds about exactly the same as the original value of 2. I'm assuming "2" is 2 seconds?

```
let sampler = new Tone.Sampler({
	'C4' : 'https://tonejs.github.io/examples/audio/casio/C2.mp3'
}, {
  onload: () => {
    sampler.triggerAttackRelease('C4', 2000)
	},
  attack : 1
}).toMaster()
```

**Comment by TomAuger** [comment]
I'm sorry I'm really not trying to extend the length of a sample. 

Please try your fiddle again with a much longer sample source. I'm happy to be proven wrong of course! But I'm trying this on 20 second+ samples and not seeing the longer release / decay values.

**Comment by tambien** [comment]
Sorry for my confusion. I've dug into this a little more and i'm pretty sure this has to do with the fact that the sampler uses a setTargetAtTime envelope for the attack and decay portions. That envelope type is not very conducive to long, gradual changes. 

I've added a "curve" attribute to Sampler which can be either 'linear' or 'exponential'. Try a 'linear' envelope for your situation. hopefully that creates the effect that you're going for.

**Comment by TomAuger** [comment]
Thanks for continuing to look into this!

I've tried this snippet and I do feel like the ramp up is more gradual, but it doesn't appear to be an exact mapping to time (seconds). This may be due to the shorter sample length.

`let sampler = new Tone.Sampler({
	'C4' : 'https://tonejs.github.io/examples/audio/casio/C2.mp3'
}, {
	curve: "linear",
  onload: () => {
    sampler.triggerAttackRelease('C4', 2000)
	},
  attack : 5 // is this supposed to be 5 seconds?
}).toMaster()`

**Comment by tambien** [comment]
It looks like the curve is behaving normally, but is limited by the duration of the sample and the math of the exponential attack curve. 

If you open [this demo](https://codesandbox.io/s/purple-fast-fyuym) and set the attack curve to be much larger than the sample, you'll still get the audio of the sample because the curve is exponential, most of the amplitude is towards the beginning of the curve. so even if you set it to a large number (like 1000), you'll get at about 50% of the amplitude within that first second of audio. 

If you set that curve to linear you'll see that it does only rise a very small amount before the end of the 1 second sample. 

Going to close again. lmk if i'm missing something.
