### ISSUE TITLE
Time and expressions

### ISSUE THREAD

**Issue by phesterman** [Tonejs/Tone.js#374]
Although I understand the rationale for eliminating string expressions in Time and TimeBase, I sure miss being able to represent and manipulate tempo-independent, BPM-relative values as single strings: "4n/7" for a septuplet, "4n/5" for a quintuplet, or "1n*2" for a breve, for example. Sorry if I've missed the boat on this somehow.

Peter

**Comment by tambien** [comment]
The expressions were adding code and complexity, as well as performance degradation in parsing the expression strings. 

Tone r13 has an object notation which i think allows you to express most of the previous expression strings. For example `"2*4n + 4t"` is now represented as `{ "4n" : 2, "4t" : 1 }`. Also a quintuplet and septuplet can be represented like this `"5n"`, `"7n"` or `"10n"`, `"20n"` for a half-note or quarter-note quintuplet, etc. 

Additionally, all the TimeBase classes implement `valueOf` which allows you to use native javascript math instead of string expression: `Tone.Time('4n')/5` for example (though it is slightly more verbose). 

Hope these satisfy your use-cases for time expressions

**Comment by phesterman** [comment]
Thanks.  I had seen the objects mentioned in the r13 ChangeLog, but didn't understand how they'd be used.  The other note values will be very helpful, too!

Peter
