### ISSUE TITLE
Tone.Buffer url not accepting AudioBuffer type

### ISSUE THREAD

**Issue by jjbeans1** [Tonejs/Tone.js#382]
Tone.Buffer should be able to accept an AudioBuffer as its url. https://tonejs.github.io/docs/r12/Buffer

However when I pass in an AudioBuffer as a Tone.Buffer url, the ToneBuffer object is undefined. 

Here is a simple example illustrating the problem: https://jsfiddle.net/jjbeans/z9marxbt/4/

In the console, you'll see the ToneBuffer object is undefined in the callback. 

Seems this was a known issue a few years back in Tone.Player and should have gotten fixed: https://github.com/Tonejs/Tone.js/issues/100  

I originally found this issue in Tone.Player and tested Tone.Buffer and noticed the same underlying issue with the url not accepting an AudioBuffer.

I'm pretty new to Tone and working with the Web Audio API, so I could very well be missing something super straightforward here. Appreciate any help!

**Comment by tambien** [comment]
In this situation, the onload callback does not really make any sense, because there is nothing to load. The `onload` callback is invoked inside the constructor immediately before the constructor has finished executing which means that the `loaded` variable is still undefined, causing the error that you got. This is similar to the situation in #376 

If you remove the callback, it works as expected. https://jsfiddle.net/hc6kyas3/

I've decided to remove the callback in cases where a fully loaded buffer is passed in to avoid this confusion in the future.

**Comment by Seanitzel** [comment]
Just ran into this too,
might be a good idea to mention it in the api :)
