### ISSUE TITLE
PitchShift have noise

### ISSUE THREAD

**Issue by Jexim** [Tonejs/Tone.js#383]
Hello. You are made a good audio lib, thank you.
I have problem with Tone.PitchShift.
After change pitch value I will get audio with noise.
You can see this example https://jsfiddle.net/Jexim/2jusapvr/95/
And compare with https://files.fm/f/dect3q4g (it made by http://onlinetonegenerator.com/pitch-shifter.html for pitch value -5).
I was try change windowSize but it not give me the right result.
What could be the problem?
Thank.

**Comment by tambien** [comment]
Tone.PitchShift is a very simple real-time pitch shifter using delay lines and LFOs. You shouldn't expect to get results comparable to what you would get with an offline pitch shifter like [rubberband](https://breakfastquay.com/rubberband/) or the one you linked to. The artifacts that you're hearing are just part of the pitch shifting process. 

Since you're using an audio file, i'd give Tone.GrainPlayer a try which may give you a better results.

**Comment by Jexim** [comment]
@tambien thanks for the quick response.

**Comment by liJie-wk** [comment]
> 能会

This question was very helpful to me

**Comment by liJie-wk** [comment]
This question was very helpful to me
