### ISSUE TITLE
Transport stops after bpm change

### ISSUE THREAD

**Issue by animateddata** [Tonejs/Tone.js#385]
Hi,

I've set up a pattern and a range input to change the bpm. I've found that changing the bpm to high values seems to stop the transport. It seems worse if the slider is moved quickly.

Occurs on Windows Chrome, Firefox and Edge.

Codepen example:

https://codepen.io/animateddata/pen/wEqMVx

(The fact that the note indicator stops suggests that the transport has stopped, rather than the synth not working.)

Tone.js is fantastic BTW - thank you!

Peter

**Comment by tambien** [comment]
thanks for the issue! should be fixed in the latest dev release. 

Here's a little validation fiddle: https://jsfiddle.net/yotammann/m2bdafw6/

The problem was a little hard to pin down: you were assigning tempo with `Transport.bpm.value = tempo` and under the hood setting the value in this way was using `context.currentTime` instead of `context.now()`. This caused events to be scheduled essentially in the past (according to the current position of the clock), which caused it to skip ticks which led to events being dropped from the timeline.

**Comment by animateddata** [comment]
Thank you @tambien - that's fixed it. Really appreciated. I'm working on some nice demos, so if they turn out as I hope I'll share.  This fix definitely helps me out :)
