### ISSUE TITLE
Cracklings due to using mp3 samples

### ISSUE THREAD

**Issue by pianorockcover** [Tonejs/Tone.js#388]
Hello! First, thanks for that amazing library.

I'm trying to run some parts (Tone.Part) that using preloaded mp3-samples simultaneously. But  the result has many pops, crackles and other unwanted artifacts.

Demo: https://test.njdstudio.com/smm/int/

Code example:
`// Synth Part
        Tone.Transport.bpm.value = 140;
        var synthPart = new Tone.Part(function(time, event) {
             piano.triggerAttackRelease(event.note, event.dur, time)
        }, [{ time : 0, note : 'B2', dur : '4n'},
            { time : 0.25, note : 'E2', dur : '4n'},
            { time : 0.5, note : 'G2', dur : '4n'},
            { time : 0.75, note : 'E2', dur : '4n'},
            { time : 1, note : 'G2', dur : '4n'},
            { time : 1.25, note : 'D2', dur : '4n'},
            { time : 1.5, note : 'E2', dur : '4n'},]);

        synthPart.loop = true;
        synthPart.start(0);

        // Bass Part
        var bass = new Tone.Synth().toMaster()

        Tone.Transport.bpm.value = 140;
        var bassPart = new Tone.Part(function(time, event) {
            bass.triggerAttackRelease(event.note, event.dur, time)
        }, [{"time": "0", "note": 'B1', "dur": "4n"}]);

        bassPart.loop = true;
        bassPart.start(0);

        // Pad Part
        Tone.Transport.bpm.value = 140;
        var padPart = new Tone.Part(function(time, event) {
            pad.triggerAttackRelease(event.note, event.dur, time)
        }, [{"time": "0", "note": 'B3', "dur": "2n"}]);

        padPart.loop = true;
        padPart.start(0);`

Are my expectations of the web audio api too high for what it can actually do today? Or I'm doing something wrong?

Thanks for your help :)

**Comment by tambien** [comment]
i’m unable to access the link you provided. if you have a minimal test case in a jsfiddle or codepen, that’d be helpful. 

it seems like you’re not asking too much of the WAA in the snippet you posted. it’s possible if your samples were very long or you are doing a lot of graphics rendering at the same time you would get performance related crackles. please reference the existing issues like #378 and the wiki article on performance best practices. 

Going to close this because it seems like a duplicate covered elsewhere.
