### ISSUE TITLE
Setting the latencyHint to the lowest causes the callbacks to be called too late

### ISSUE THREAD

**Issue by maximedupre** [Tonejs/Tone.js#391]
[The code is also available in this fiddle.](https://jsfiddle.net/zfo5py6g/1/)

    Tone.context.latencyHint = 0

    let looping = (time, divisionIndex) => {
      console.log(time, Tone.context._context.currentTime);
    }

    new Tone.Sequence(looping, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], "16n").start(0);
    Tone.Transport.start();

As you can notice, when setting `Tone.context.latencyHint = 0`, the `looping` callback is called too late, as most of the time, the current time will be greater than the the callback `time` argument.

**Comment by tambien** [comment]
thanks for the issue @maximedupre. this is the intended behavior and maybe a good illustration of the purpose of the lookAhead time and why you may not want to set the latencyHint to 0. :)

For example,`context.latencyHint = “fastest”` currently sets the lookAhead time to 0.01 to avoid this specific issue. Even then there’s a good risk of the context.currentTime getting ahead during execution on slow devices or when the page is rendering a lot of things since the AudioContext runs in a separate thread. 

Your best bet for staying ahead of the context time is to have an appropriate lookAhead/latencyHint for your application which will probably always be greater than 0. I’ll leave in the ability for latencyHint to be 0 in case there is a use case for the lowest possible latency in exchange for less timing accuracy and more clicks.
