### ISSUE TITLE
Latency with external midi keys

### ISSUE THREAD

**Issue by giacomorebonato** [Tonejs/Tone.js#396]
Hi, I started for fun a project where the idea is to create a UI for ToneJS and then play notes by listening to midi events, fired from an USB connected piano.
We are having latency issues of something less than a second.
The issue is not present if we just play a sound through audio API, without using ToneJS.

Is it a normal limitation of browser performances or something that we can improve in the codebase?

Here is the code that we use to play sounds:
https://github.com/giacomorebonato/ossynth/blob/master/src/App.tsx

**Comment by tambien** [comment]
by default Tone.js adds a short `lookAhead` value (0.1 seconds) to the AudioContext.currentTime. In general, this produces more consistent timing and better performance. You can set your own lookahead value though if you'd like lower latency:

try `Tone.context.lookAhead = 0`

You can also schedule events with `Tone.immediate()` which returns the AudioContext.currentTime instead of `undefined` or `Tone.now()` which returns the `currentTime + lookAhead`
