### ISSUE TITLE
Lots of crackling on Pixelbook

### ISSUE THREAD

**Issue by Ecafracs** [Tonejs/Tone.js#413]
On the Pixelbook i7 running ChromeOS Version 70.0.3538.110 (Official Build) (64-bit)
many of the demos on https://tonejs.github.io/demos such as Oscillator, Groove Pizza, Musical Chord Progression Arpeggiator, Discreet Music, Solace, and Inside Music exhibit varying amounts of popping and crackling, ranging from mildly annoying to entirely unusable.

**Comment by tambien** [comment]
Thanks for the issue. From what you're describing, it seems like this issue is across multiple versions and various features of Tone.js. in this form, i think this issue is too broad from me to try to deal with and might be related to hardware/software limitations of Web Audio and the Pixelbook more than anything Tone.js specific. 

Going to close, if you can break it into more specific and reproducible issues, feel free to reopen.

**Comment by redfoxDW** [comment]
Maybe you could offer a spot where people could leave their hardware/browser feedback? The information on Tone.js behavior in various device & browser configurations seems really helpful.
