### ISSUE TITLE
Weird Sounds from Some Monophonic Synths when Overlapping Attack-Release Calls

### ISSUE THREAD

**Issue by fabb** [Tonejs/Tone.js#422]
When calling `triggerAttack` several times, and after that calling `triggerRelease` several times, some monophonic synths' sounds break. I have not yet found out why.

```
  Tone.Transport.loop = true;
  Tone.Transport.loopEnd = "1:0:0";
  Tone.Transport.schedule(time => {
    metal.triggerAttack(time);
    metal.triggerAttack(time + Tone.Time("0:1:0"));
    metal.triggerRelease(time + Tone.Time("0:2:0"));
    metal.triggerRelease(time + Tone.Time("0:3:0"));
  }, 0);
```

Here's a Codepen that demonstrates the issue:
https://codepen.io/fabb64/pen/ebjJZq
(switch between `scheduleDuoSynthNotes` and `scheduleMetalSynthNotes` to listen to the two respectively)

Here are audio recordings of the problems (generated by just playing back the Codepen from above on the latest Chrome 71):

[weird_synths.zip](https://github.com/Tonejs/Tone.js/files/2742063/weird_synths.zip)

**Comment by fabb** [comment]
Thanks! When wrapping into a poly with polyphony=1 it works fine, as expected.

**Comment by tambien** [comment]
@fabb that might be because Tone.PolySynth prevents double triggering of the release.

**Comment by tambien** [comment]
Thanks for this test case! helped me find a very hard to reproduce bug which ended up being a floating-point error. The underlying oscillators are scheduled to stop, and then in the next Transport Loop restarted with _nearly_ the same time. In the timeline class when two values are the same, the event is pushed onto the end which is what should have happened, but because of the floating point math, the second start was very very slightly less than the previous stopped time. 

The solution here was to introduce comparisons with some epsilon threshold in the Timeline class. Seems to have fixed this issue. 

Here's your code with the latest changes: https://jsfiddle.net/yotammann/L48zhgnp/

**Comment by fabb** [comment]
Awesome that you found it!
