### ISSUE TITLE
Bug playing and seek an AudioBuffer using Player?

### ISSUE THREAD

**Issue by charlesswanson** [Tonejs/Tone.js#424]
Not sure if this is a bug, or a lack of understanding on my part...

I am using Tone.Offline to put 4 seconds of sounds into an AudioBuffer. Then, I want to be able to play that AudioBuffer starting from any offset (0-3 seconds). I'd like to be able to 'play' multiple times without reloading the page.

From the docs, it sounds like the Player class' restart method would do the trick: https://tonejs.github.io/docs/r13/Player#restart

However, it only works once for me, and doesn't work unless my chosen offset is 0. Here's a demo:
https://codepen.io/charlesswanson/pen/qLLjQY?editors=1010

Am I misunderstanding something about how Player works? Or is there a bug?

Thank you

**Comment by tambien** [comment]
Looks like the issue was just that you were trying to start at time 0, which is when the AudioContext is first created so it's already in the past, maybe the right behavior is that it should just clamp to the currentTime. If you change line 39 to `this.tonePlayer.restart(Tone.now(), offset)` it should work.

**Comment by charlesswanson** [comment]
Thank you, that does the trick! I must consider that time is not always relative, but can also be absolute.
