### ISSUE TITLE
Firefox - PolySynth with FMSynth Performance

### ISSUE THREAD

**Issue by tboie** [Tonejs/Tone.js#427]
Playing multiple voices of a PolySynth with FMSynth on Firefox causes performance issues on Firefox.

tone@next with Firefox 64.02 (latest)
https://jsfiddle.net/timboie/wdsun3m6/

tone@0.12.80 OK

**Comment by tambien** [comment]
Seem approximately the same as the performance on Chrome. I should also point out that tone@latest is (13.4.9) and tone@next (13.4.10) don't differ by any significant code. so curious why it's working for you on tone@latest

**Comment by tboie** [comment]
Ah, had 0.12.80 set as latest.

Here's a video for reference using @next
https://www.youtube.com/watch?v=9nFcpsF4W2E

**Comment by tambien** [comment]
thanks for the video. very helpful. i will investigate

**Comment by tboie** [comment]
Appears to be an OS issue (osx 10.9.5)

Tested on VM with latest version of ubuntu: OK

**Comment by tboie** [comment]
OS/Hardware issue?  Need to find other machines/setups to test on

**Comment by ctrl-alt-d** [comment]
Me too. I have issues with your sample on Firefox:

* OS: Fedora 29
* Firefox: 65.0 (64-bit)
* HW: Core i7, 3.5 GHz, 16GB, Intel HD Graphics 620 ( https://www.techradar.com/reviews/razer-blade-stealth-2017 )

**Comment by tboie** [comment]
OS X 10.9.5
2.6 Gz Intel Core i7
16 GB 1600 MHz DDR3
FireFox 65.0.1

**Comment by tambien** [comment]
Seems like the issue has to do with the fact that firefox struggles with `oscillator.setPeriodicWave(periodicWave)`. Using any non-basic oscillator types bogs it down. I implemented an optimization which doesn't use periodicWave for basic wave types, but if you were to set "sine2" or any custom partials array instead of just "sine", you'd get the same issue on FF. 

This bug should probably be brought to firefox's attention and assigned there, since there's little more than this optimization that i can do to address it.
