### ISSUE TITLE
Filter does not respond correctly to the signal when fed a sine osc

### ISSUE THREAD

**Issue by faxinadu** [Tonejs/Tone.js#431]
Opened this issue then thought the mistake is in my own code, now I am not sure anymore so opened it again.

If I feed a sine oscillator (one with lots of harmonicity via fm) to the filter module, then the filter does not react to the signal. If i change the source to a sawtooth the filter responds to the signal. Not sure what is going on.

I know this is a rather big example, i will try to get a smaller one as well. The subtractive signal is filtered while the additive signal is not, even though they are both fed to the filter in the same manner. If I change one of the additive oscs to a saw to test, then the filter responds correctly to it:

https://faxinadu.net/jstest/tone/synth/

Apologies if this is not a library issue but an issue in my code, just confused and not sure about this.

Thanks

**Comment by marcusprice** [comment]
I'm not a total expert on audio, but isn't this because sine waves have far less harmonic content than other types of waveforms? It was my thought that sine waves generate a pure tone, whereas sawtooth, square, triangle and other waveforms generate a bunch of harmonics which is what you are filtering out in subtractive synthesis.

**Comment by faxinadu** [comment]
this is why i mentioned that they contain lots of harmonics via fm. you can check the example synths. take the subtractive gain low, and pull up the fm on the additive. this produces very rich waveforms. then move the filter slider, nada.

**Comment by marcusprice** [comment]
Oops, missed that. I tried to play with your example but couldn't generate any sound at all. Noticed a few errors in the console too, not sure if that's related or not. 

If you post another example I'd be interested in checking it out.

**Comment by tambien** [comment]
I'm also unable to get your example to make sound. I think it's probably because of an autoplay policy issue. Check [this section](https://github.com/Tonejs/Tone.js#starting-audio) of the readme for tips on how to start the audio. 

There are a number of attributes which would affect the amount of attenuation of the filter. As @marcusprice mentioned, it might have something to do with the frequency and harmonics of the source signal or the cutoff frequency of your filter. For example if i were to pass a sine tone at frequency 440 into a lowpass filter with frequency above 440, i would expect no attenuation. Similarly if the filter frequency is very high or the oscillator frequency very low, i would expect negligible affect on any incoming signal.  Also double check that your filter type is what you expect (probably expecting "lowpass"). 

Here's an example of a an FMOscillator going through a lowpass filter with user controlled cutoff frequency: 

https://jsfiddle.net/yotammann/v90j6krm/

**Comment by faxinadu** [comment]
I actually know about the chrome audio starting policy, but when I started working with Tone.js everywhere I checked it worked automatically web and mobile, checked on probably 6 computers with Chrome... wonder how come it isn't for you guys? So just to clarify as of now this button is a must or not?

Filter is set to lowpass yes. In fact after more testing, the attenuation is there, it is just very very subtle. Maybe I just need to play more with the filter slider, perhaps making it non linear will make all the difference. I will report back.

**Comment by tambien** [comment]
The autoplay thing is tricky with a bunch of different factors which Chrome has that are pretty opaque to the user/developer. I don't know if it _needs_ to be a button, but the example in the README is the most consistent way that i've found to start the audio. 

Going to close for now, since it doesn't seem to be a Tone.js related issue, but might be something more specific to your application. Re-open if it turns out there is an issue on the Tone.js side, and especially helpful if you could create a minimal example of the issue.
