### ISSUE TITLE
"The AudioContext was not allowed to start" happens just by including the lib

### ISSUE THREAD

**Issue by gabrielflorit** [Tonejs/Tone.js#443]
"The AudioContext was not allowed to start" message happens just by including tone.js. Here's an example: https://tonejs.github.io/unmute/examples/basic.html

Is there a way to avoid this?

**Comment by tambien** [comment]
i've looked into this a bit when the warning first started appearing, and haven't found a good way to fix this. it seems like we can reduce the number of warning messages by deferring some internal node 'starts' to when the AudioContext is started, but there is still going to be at least one warning when the context is created on initialization. Creating a context on initialization has been the behavior since the beginning of Tone.js, so changing it at this point would break a lot of things. 

I'm not sure if Chrome plans on having that message in there forever, or if they might change it once enough people have adopted and understood the autoplay policy. it might be worth creating a bug report to see what they say about it. 

For now i am going to close this issue, since it seems like mostly an aesthetic thing, and no fix from what i can tell. but feel free to add to this thread for updates relevant to the warning message.

**Comment by gabrielflorit** [comment]
Thank you for the detailed reply.

**Comment by meszaros-lajos-gyorgy** [comment]
I found a solution, which works, if you are working in an environment, where dynamic module loading is supported.

Statically imported Tone.js, results in warning:

```javascript
import Tone from 'tone'

// ...

const synth = new Tone.Synth().toMaster()
```

Dynamically imported Tone.js, no warning:

```javascript
let Tone

const enableButton = document.getElementById('any-button-to-trigger-user-interaction-with')
enableButton.addEventListener('click', () => {
  import('tone').then(module => {
    Tone = module.default
  })
})

// ...

if (Tone) {
  const synth = new Tone.Synth().toMaster()
}
```

The downside of this solution, is that you need to check whether Tone has already been imported before using it.

**Comment by mrtnmgs** [comment]
@meszaros-lajos-gyorgy's solution worked for me, except that `module` didn't have a `default`. Not sure if things changed in a more recent version of Tonejs. Replacing `Tone = module.default` by `Tone = module` did the trick.
