### ISSUE TITLE
Declick

### ISSUE THREAD

**Issue by zeronerorgb** [Tonejs/Tone.js#452]
Hello, when I create several oscillators with similar frequencies, a sinusoid overlay effect appears and a rattle is heard to fix this using an algorithm or a de-click module for example (http://help.izotope.com/docs/rx5/de-click.html ), but I did not find anything like this in the documentation, how can I fix this?

https://jsfiddle.net/zeronero/35z9ca1L/11/

**Comment by tambien** [comment]
Tone.js doesn't have a de-clicking algorithm implemented. if there is a way to do that in Web Audio, it might be cool to include that in the library.

My guess is that click is being caused by the instantaneous starting of those oscillators. i might try turning down the volume on the oscillators and also adding a short Gain envelope going 0 to 1 at the moment when those oscillators are started.
