### ISSUE TITLE
Part plays twice, when Part.loop = 1

### ISSUE THREAD

**Issue by meszaros-lajos-gyorgy** [Tonejs/Tone.js#494]
Hi!

_I made another jsfiddle to illustrate the issue: https://jsfiddle.net/lmeszaros/yL1zx78u/39/_

I have `Part.loop` set to `1` and `Transport.loop` set to `false`, but Part will loop as if Part.loop was set to 2.

**Comment by jaredellison** [comment]
Hi! Just discovered this library and started looking at a few open issues to get familiar.	

This loop logic appears to be implemented in [`Tone.Event.prototype._rescheduleEvents`](https://github.com/jaredellison/Tone.js/blob/305e716cde80faaf8600e5e500b94f551daa1f7d/Tone/event/Event.js#L139)  and the question seems to be over what happens when `loop` is 0, 1, or greater than 1.

I'm with you @meszaros-lajos-gyorgy, it seems like the sequence should play once when `loop === 1` and twice when `loop === 2`.  

Currently, if `loop ` is false or 0, single events are scheduled and if `loop`  is 1 or greater, repeating events are scheduled (even if it's one repeat).

I drafted a pull request (#508) where `Tone.Event.prototype._rescheduleEvents` handles 0 and 1 loops in the same way - the sequence plays only once and there is no change to the functionality when `loop` is true, false or greater than 1.

This prompts the questions: 

- Should `loop === 0` actually mean that no events are scheduled? 
- Would it be helpful to add a [test](https://github.com/Tonejs/Tone.js/blob/305e716cde80faaf8600e5e500b94f551daa1f7d/test/event/Event.js#L293) for this behavior around 0 or 1 loops?

**Comment by meszaros-lajos-gyorgy** [comment]
While we are at checking on the loop property, I would have a suggestion:

I don't know the history of the `loop` property for the `Part` and `Transport` classes, but from a developer's perspective I think it would be clearer, if it would only accept integers. Does `loop === false` mean `loop === 0`? Does `loop === true` mean `loop === Number.MAX_SAFE_INTEGER`?

Or if the boolean values are more reasonable for the property, then the quantified value should be set via a different property, for example `loopFor`.

**Comment by tambien** [comment]
@jaredellison thanks for the PR! it'd be great to include a test like the one you linked to validate your PR. 

You're right that it's a bit weird that `loop = 0`, `loop = false`, and `loop = 1` all have equivalent behavior, but i think the alternative is more confusing: if you set `loop = 0` (which you might think is false) and it made no sound at all, that would seem like a bug to me. 

We can clarify the docs that loop is either true/false or a number > 1 which i hope would alleviate most confusion around that feature. 

@meszaros-lajos-gyorgy i think if you set it to `loop = 2.5` it would loop for 2.5 iterations, so i don't think an integer value is necessary here. `loop = true` means `loop = Infinity`.

**Comment by jaredellison** [comment]
@tambien and @meszaros-lajos-gyorgy, thanks for the feedback!

I've just pushed an update to the PR including tests and updated JSDoc comments for the Part and Event classes to outline this behavior around loop values of 0, 1 and false.

**Comment by meszaros-lajos-gyorgy** [comment]
Cool! Thank you very much!
