### ISSUE TITLE
why Tone.Time('0 + 8n + 8n + 8n + 8n').toNotation() returns "2n" in old version,and retrun "1m" in new ?

### ISSUE THREAD

**Issue by bythink** [Tonejs/Tone.js#498]
use lastet version from https://tonejs.github.io/build/Tone.js
result:
Tone.Time('0 + 8n + 8n + 8n + 8n').toNotation() 1m
Tone.Time('8n + 8n + 8n + 8n').toNotation() 1m
Tone.Time('8n + 8n').toNotation() 1m
Tone.Time('4n + 4n').toNotation() 1m

all of them returns "1m" . why?

and . I use this version https://www.guitarland.com/javascripts/Tone.js

results:
Tone.Time('4n + 4n').toNotation() 2n
Tone.Time('8n + 8n').toNotation() 4n
Tone.Time('8n + 8n + 8n + 8n').toNotation() 2n
Tone.Time('0 + 8n + 8n + 8n + 8n').toNotation() 2n

**Comment by bythink** [comment]
use lastet version  from  https://tonejs.github.io/build/Tone.js
result:
Tone.Time('0 + 8n + 8n + 8n + 8n').toNotation()      1m
Tone.Time('8n + 8n + 8n + 8n').toNotation()   1m
Tone.Time('8n + 8n').toNotation()   1m
Tone.Time('4n + 4n').toNotation()     1m

all of them returns  "1m" .  why?



and . I use this version https://www.guitarland.com/javascripts/Tone.js

results:
Tone.Time('4n + 4n').toNotation()  2n
Tone.Time('8n + 8n').toNotation()  4n
Tone.Time('8n + 8n + 8n + 8n').toNotation()  2n
Tone.Time('0 + 8n + 8n + 8n + 8n').toNotation()  2n

**Comment by tambien** [comment]
string expressions were removed in version 12, so it seems like the fact that they always return "1m" is just a bug from it not being able to parse the expression. I think the best way to acheive what you're trying to do is probably something like this: 

`Tone.Time(Tone.Time('8n') + Tone.Time('8n')).toNotation()`

Since Tone.Time implements `valueOf()`, the expression will be converted to seconds and then you can find the closest notation value of that.
