### ISSUE TITLE
Envelope 'Release' property does not accept '8n' string.

### ISSUE THREAD

**Issue by gntsketches** [Tonejs/Tone.js#501]
This pen: https://codepen.io/gntsketches/pen/KjVdBm attacks and releases a synth through the Loop method. The envelope's " attack" property accepts the string '8n', however the "release " property does not. Nothing plays if you set release to '8n'. According to the API, they both except a "time" type of value, so it seems like this should work.

**Comment by tboie** [comment]
you can try using Tone.Time('8n') or Tone.Time('8n').toSeconds() as a work-around for now

**Comment by tambien** [comment]
Currently fixed on the typescript branch. This issue is with [this line](https://github.com/Tonejs/Tone.js/blob/dev/Tone/instrument/Synth.js#L102). `this.envelope.release` needs to be wrapped in `this.toSeconds()` in order to convert it to a number. 

validation example: https://codepen.io/yotam/pen/bXGJJq

Will eventually be merged back into dev and master.
