### ISSUE TITLE
irregular square wave

### ISSUE THREAD

**Issue by JTorresConsulta** [Tonejs/Tone.js#506]
I'm analyzing the square sound wave with Audacity spectrum and I view that the square wave is not perfect but so irregular as you can see in the capture:

https://i.ibb.co/W2ThYHd/tonejs-irregular-wave.png

Its a bug? its possible to get a perfect wave?
Thank you!

**Comment by tambien** [comment]
I wonder if Audacity is distorting the wave somehow. Or if what is being visualized is not the waveform, but something else. i'm not so familiar with Audacity, so i don't know what's being visualized, but i see the values center around -60, which makes me think that it might be showing loudness in decibels instead of the waveform. 

Here is a square wave plotted with Plot.ly from the browser:

![image](https://user-images.githubusercontent.com/1323402/60065217-153a8a00-96d1-11e9-8297-c2579da992f6.png)

And here's the same square in Ableton Live:

![image](https://user-images.githubusercontent.com/1323402/60065308-74989a00-96d1-11e9-9d45-14d328c7ebb3.png)

**Comment by JTorresConsulta** [comment]
Hi Yotam. Thank you for your answer.
Its strange for me because I have same results in a mobile device.

Have you the code for that wave graph?

My code is the next:

```
var o = new Tone.Oscillator().toMaster(); 
o.type="square";
o.frequency.value=2;
o.start();

```

**Comment by tambien** [comment]
I use the OfflineAudioContext to try and get the cleanest recorded output and i use a wrapper of Plot.ly that i built for testing to graph it: https://codesandbox.io/s/polished-sea-i51dv

I downloaded Audacity to see if i can see what you're seeing, using a file generated from the above code, i still get the same square wave, but i do see an option to show the waveform in decibels vs the raw waveform: 

![image](https://user-images.githubusercontent.com/1323402/60198466-a6177f80-980f-11e9-8922-6c06ae75bd2f.png)

two questions: does it make a difference if you change it to "waveform" instead of "waveform (db)"? also, how are you recording the waveform output?

**Comment by JTorresConsulta** [comment]
Hi Yotam,
Your example dont launch the wave sound as my script in  http://www.emdr-es.com/waves.html

The output recorded in audacity showed in DB.
Look the irregular continuous sound bands in 6k, 2k, 1.5 K.... etc... (neither  its should not exist in a pure square wave)

https://i.ibb.co/ftcMv5b/oscillator-tonejs-irregular-wave-db.png
[https://i.ibb.co/ftcMv5b/oscillator-tonejs-irregular-wave-db.png](img)

**Comment by tambien** [comment]
The example i posted just renders audio straight to an AudioBuffer which removes the potential for speakers or physical audio hardware to interfere with the signal. 

From my measurements, it looks to me like the square wave is rendering as expected, but maybe the issue is that you want to render an _ideal_ square wave which modules between ±1?

If you'd like an ideal square wave at 2hz, i think the easiest way to do that would be to generate an audio buffer at your desired length, and manually fill the samples (`f(t) < PI ? 1 : -1`). You can set that to an AudioBufferSourceNode and set it to `loop=true`. 

A little more info about ideal vs approximate square waves:

The Web Audio API renders all waveforms with a [fourier series](https://en.wikipedia.org/wiki/Square_wave#Fourier_analysis). This is part of the [Web Audio specification](https://webaudio.github.io/web-audio-api/#oscillator-coefficients) which Tone.js uses to generate the square wave, so i don't really have any control over how it renders waveforms. i think they probably chose this method for practical considerations.

Given this harmonic approximation the square wave should have [peaks at odd harmonic multiples of the fundamental](https://en.wikipedia.org/wiki/Square_wave#/media/File:Spectrum_square_oscillation.jpg) which looks consistent with your spectrogram image. 

This conversation also seems related to #125 about ideal vs imperfect square waves.
