### ISSUE TITLE
[Request] Vue/React examples/demos.

### ISSUE THREAD

**Issue by sustained** [Tonejs/Tone.js#507]
Sorry if this is the wrong place for such a request but basically I'd like to request some examples that make use of Vue (or even React... even though I don't personally use it).

I've found a fair amount of threads on the forum from people struggling with how to archirecture their Vue+Tone application and unfortunately none of them have any replies.

I too find myself in this situation.

Vue and React are extremely popular and they aren't going away any time soon. I think it would be very worthwhile for there to be some demos/examples that use something like Vue or React.

Thoughts?

**Comment by tambien** [comment]
As a place to start, you can take a look at the Tone.js UI which is all built with Polymer which shares some similarities to Vue/React. https://github.com/Tonejs/ui

**Comment by ejarzo** [comment]
@sustained Ableton's new [Learning Synths](https://learningsynths.ableton.com/get-started) site uses React and Tone ([source](https://twitter.com/AbletonDev/status/1143880805317525506)). I  reached out to them to see if they could publish the source (🙏) or maybe some examples because that would be an outstanding resource for us devs using React+Tone. Even without the source code, it's a cool demo to play around with if you haven't already.

**Comment by sustained** [comment]
That's great, let's hope they are open to releasing the source.

**Comment by DouglasDev** [comment]
I have experience using toneJS in conjunction with Vue. If you have a specific example or demo you would like to see, I could work on it. Let me know.

**Comment by nwesthoff** [comment]
I've been playing with ToneJS and React the past week. I'm trying to recreate Teenage Engineering's PO28 (and maybe more later) as closely as I can. 

[Demo](https://digital-pocket-operators.netlify.com/) and [Source](https://github.com/nwesthoff/Digital-Pocket-Operators). 

Not too much Tone in there yet (just a basic synth with a filter on a sequencer, bpm and swing adjustment). Hope to add a little more over the next few weeks.

**Comment by tambien** [comment]
It seems like there are some examples of Tone.js used with Vue/React and there doesn't seem to be any one way to go about it, or any major gotcha's (more than normal gotchas in Tone.js and React separately). Plus the examples are all created with web components which is pretty similar to React. 

I'm going to close this since i don't think there's anything specific to programming Tone.js with Vue/React.

**Comment by digitalfabric92** [comment]
@ejarzo Did Ableton get back to you about releasing the source for Learning Synths?

I am also very interested in building off it. The design is great!

David
@digitalfabric
