### ISSUE TITLE
Synth Typescript Definitions

### ISSUE THREAD

**Issue by motifn** [Tonejs/Tone.js#509]
Hi - I've had to work on the typescript definitions for Tone.js synths, as these are essential for autocomplete on https://www.motifn.com.

Here's the current definitions I'm using for the synths (sure I've got some things wrong):
https://www.motifn.com/typedefs/synths.d.ts

Here's the issues encountered:

1) The tone.d.ts name `OscillatorOptions` had to be changed to `ToneOscillatorOptions` to avoid a name collision with types defined in the standard javascript library. This was actually quite nasty: was wondering why on earth I was getting type errors. Here's the link to w3 spec:
https://www.w3.org/TR/webaudio/#dictdef-oscillatoroptions

2) The tone.d.ts type definitions didn't have optional properties for synth options. This is pretty essential, as people don't want to explicitly provide default values for every property. Interestingly, there might be potential type re-use here between synth definitions and synth instantiations w/ typescript's mapped types. For example, `Partial<T>` will create a type where each property is optional. I'd expect something similar would be useful for Tone.js. For example, the volume property might have the type of an optional number in the definition, but have a type that lets you modulate the volume over time in the instantiated synth...

3) It would be useful to have a uniform way to declaratively model synth modulation over time. Static typing concerns aside, I've got this working with Tone.js today for some properties (e.g. modulating volume, modulationIndex, harmonicity) but not in others (pitch shifting w/ the PitchShift component). This seems to be because the `setValueAtTime` concept isn't ubiqitous. Again, typescript has a mechanism that might come in handy here: the `pluck` concept, that lets you pick a subset of properties to create a new type. So you'd pluck properties from a synth/effect to represent a type comprised of properties that could be modulated over time.

4) The numeric suffixes are probably too explosive in terms of the number of possibilities to express in Typescript. So combining "fat" and "square" into "fatsquare" is doable, but also suffixing with "5" isn't going to fly - it has to be defined with a separate property.

5) According to the docs `OmniOscillator` throws exceptions if some properties are set, based on the type. Wondering if there's a way to model only legal combinations with static types.

Let me know what kind of help you're looking for w/ the typescript port.

Cheers
Ben

**Comment by tambien** [comment]
thanks Ben! all interesting points. Gladly accepting PRs on the typescript branch. [here's a short doc](https://github.com/Tonejs/Tone.js/wiki/Typescripting-Tone.js) i put together with some more details. 

1. Wasn't aware there was a collision with OscillatorOptions, but that's an easy enough thing to change. 

2. I've been using Partial<Options> in the typescript port. you can see an example [here](https://github.com/Tonejs/Tone.js/blob/typescript/Tone/source/oscillator/Oscillator.ts#L75). 

3. Properties that have a setValueAtTime are class members that extend Signal or AudioParam. I'm not familiar enough with `pluck` to see how that could work, but glad to review a PR or example if that's a better way to do it. 

4. You'll see in addition to `type` there is `baseType`, `sourceType` and `partialCount` which are the broken down components of the type combos.

5. If there is the possibility to have conditional types such that `width` is only available when `osc.type === 'pulse'`, that would be awesome! but i'm not quite sure how that could be done. 

Going to close this since it's not really an issue. glad to continue this conversation here or through a PR. 

thanks!

**Comment by motifn** [comment]
Apologies in advance if I'm not being clear still in the learning curve!

Regarding 3 - perhaps to pose as a question:

How can I schedule a pitch shift for a particular time in the future? Naively I expect to be able to go `pitchShift.pitch.setValueAtTime` but the only available member is `pitchShift.pitch` which immediately changes the pitch. In contrast, with `modulationIndex` I can go: `synth.modulationIndex.setValueAtTime`.

**Comment by tambien** [comment]
Yeah unfortunately properties that don't have those methods (like setValueAtTime) are not able to be scheduled in the same way. I try to make all properties signal-rate whenever the implementation allows since it opens up many new opportunities. But in the case that you're referring to (the PitchShift effect), that's not a possibility because of how the Scale.js object is implemented using a WaveShaperNode. And since changes to the WaveShaperNode curve cannot be scheduled, that propagates up through the LFO.min/max values and to the PitchShift.pitch property.

**Comment by motifn** [comment]
Interesting. The scenario I had that hit this problem was trying to bend notes with grain synthesis. Setting the `detune` parameter seemed to change the pitch only as frequently as the grain size allowed, which meant a staggered not smooth sounding pitch shift. So then I tried pitch shifting, but this couldn't be scheduled. Is there anyway to make this work?

**Comment by tambien** [comment]
So this is another situation where the implementation details make it difficult to do exactly what you're trying to do. The big issue here is actually a Safari bug which hasn't been addressed so i've having to work around for a few years. 

It is possible (thought a little complicated) if you implement your own granular synth. The granular synth is composed of short segments of BufferSourceNodes whose playbackRate parameter is a signal-rate parameter. Because of the Safari bug, i'm not able to attach a signal to the playbackRate parameter in order to implement this feature, but if you do it yourself you can either A) attach a signal to the playbackRate parameter and schedule that signal-rate attribute which would affect each of the individual grains' playbackRate if you don't care as much about Safari support, or B) schedule each of the individual grains' playbackRate params so that together they combine into a smooth frequency curve. The second option is a little more complicated to calculate the timing right, but would not be affected by the Safari bug i was referring to.

**Comment by motifn** [comment]
OK - that sounds quite complicated, but perhaps doable. BTW, what actually is the safari bug?

**Comment by tambien** [comment]
@motifn connecting a signal to the playbackRate doesn't do anything: https://bugs.webkit.org/show_bug.cgi?id=127674
