### ISSUE TITLE
Sampler fails to play on Safari

### ISSUE THREAD

**Issue by motifn** [Tonejs/Tone.js#518]
Created the smallest possible repro here:
https://stackblitz.com/edit/min-knamvn?file=index.ts

Works fine on Chrome, but on Safari, it silently fails. Interestingly, I also tried running it against the latest typescript branch of Tone.js: still works fine on Chrome, but this time, on Safari, got a *non-silent* error:

```
n.context.createGain is not a function. (In 'n.context.createGain()', 'n.context.createGain' is undefined)
```

P.S. I realize you must be a bit overloaded; perhaps I can save you time with a pull request for your Midi library regarding the issue I raised there. Just let me know whether my thinking on that one seems right or not. Anyway getting late need to sleep hesitant to submit this issue in case I'm no longer making sense lol anyway...

**Comment by motifn** [comment]
Peeking into the state, it appears the underlying `webkitAudioContext`'s `state` is `suspended`. So a workaround is to call `resume` on the underlying `webkitAudioContext` immediately after creating the sampler with the following line:

```
sampler.context._context.resume()
```

Where adding that line to the code looks like:

```
const Tone = require ("tone")

function playSample() {
  const sampler = new Tone.Sampler({
    C4:"https://tonejs.github.io/examples/audio/salamander/A7.mp3"
  },
    () => {
      sampler.triggerAttack("C4")
    }
  ).toMaster()    
  sampler.context._context.resume() // necessary for Safari
}

// within the handler of some UI event such as a click:
playSample()
```

**Comment by tambien** [comment]
that's funny i was just in the middle of writing a response. it seems like you've got the idea. 

For the issue on 13.4.9, the issue is that the audio context is not started. since you've got a deferred callback which actually makes the sound, the browsers aren't able to understand that as an explicit user action starting the audio, so i think Safari won't let you play any sound until a user clicks a button followed directly by either context.resume() or something that makes sound. 

For starting the context, it's enough to either call `Tone.start()` or `sampler.context.resume()` from within that button callback. I don't think you need to grab into the internal `_context`. 

The second issue with Safari on the typescript branch is because there are no shims on that branch yet, and since Safari requires `webkitAudioContext` instead of `AudioContext` and that code isn't in there yet.
