### ISSUE TITLE
Saving Audio to Tone Player Trims silence Unnecessarily

### ISSUE THREAD

**Issue by zbaker94** [Tonejs/Tone.js#524]
I may be doing something wrong but I am at a loss. I have a class that creates a player and (when prompted) records the output of a tone.synth. The recorded audio is converted to a blob and then a URL and put in the player. Whenever the user hits the record button a new player is created with the output of the synth. The intent here is to allow the user to loop sounds they have recorded while layering more sounds on top. the issue is that for every recording after the first, silence is removed. This results in misaligned players. So if I play a note at measure one and then stop recording then start recording and play another note at measure two when I play it back the second note plays as soon as the transport starts. I have verified the issue by looking at the size of the audio buffer. For every recording, after the first, the buffer is much smaller than the buffer of the first recording.

I tried to get my code up on stackblitz but couldn't get it running but here is the relevant code that is producing this behavior. (https://github.com/zbaker94/stackblitz-jssynthlooper/blob/master/src/app/channel.model.ts)

I m happy to reformat the question or look elsewhere if this is not a bug and I am just doing something wrong. Thanks!

**Comment by tambien** [comment]
There's nothing in Tone.js that does any silence removal or automatic buffer trimming, so my guess is that the issue might be coming from the fact that the MediaRecorder does not start recording exactly when you call `recorder.start()`, but instead starts a moment after resulting in a slightly shorter buffer. Because everything in the Web Audio world is precisely schedulable, but other APIs like the MediaRecorder are not, makes them sometimes hard to mix and keep precise timing. 

If you're only recording Web Audio (like Tone.Synth) and don't need to record any outside inputs (like the microphone), i'd take a look at Tone.Offline. Capture all of the synth events relative to the loop start time, and then schedule a new synth inside of Tone.Offline. This could quickly create a buffer of the precise length which you can then add to Tone.Player.

**Comment by tambien** [comment]
@zbaker94 did you have a chance to further take a look at what was causing the issue?

**Comment by tambien** [comment]
Going to close due to inactivity. Doesn't seem to be a Web Audio or Tone.js issue. Please reopen if it looks like it is.
