### ISSUE TITLE
Quintuplets, septuplets, nonuplets, ... timing

### ISSUE THREAD

**Issue by myleftshoe** [Tonejs/Tone.js#526]
I created a metronome app that plays x ticks per beat. If x is 2, 3, 4, 6, 8, timing is perfect i.e the first tick will always fall on the beat, but if x is 5, 7, 9, the first tick starts becomes out of sync.

I'm calculating the loop interval using `Tone.Time('4n')/ticks`

I can remedy this by tweaking the PPQ to be evenly divisible by the number of ticks. e.g. setting it to 190 for 5 ticks, 189 for 7 and 9 ticks. Is this what needs to be done or am I missing something?

**Comment by myleftshoe** [comment]
Don't know what I did but it seems okay now. Closing.

**Comment by tambien** [comment]
It would make sense to me that you might need to make the PPQ divisible by your subdivision in order to maintain accuracy over a long period of time since the ticks are rounded to the nearest value. I'd say if the issue comes back, then your intuition of making the PPQ a multiple of the subdivision you're trying to capture would work.

**Comment by myleftshoe** [comment]
@tambien Thankyou!
