### ISSUE TITLE
"Uncaught ReferenceError: global is not defined" when importing individual components

### ISSUE THREAD

**Issue by myleftshoe** [Tonejs/Tone.js#530]
`at Tone.js:561`

which is this line:
```Tone.global = Tone.isUndef(global) ? window : global;```

I'm importing like this:
```
import Tone from 'tone/Tone/core/Tone';
import ToneTransport from 'tone/Tone/core/Transport';
import TonePart from 'tone/Tone/event/Part';
import ToneLoop from 'tone/Tone/event/Loop';
import TonePlayer from 'tone/Tone/source/Player';
```
Just importing Tone `import Tone from 'tone';` works but I'm trying to reduce bundle size so not ideal:

If I change the problematic line to `Tone.global = window;` the problem goes away.

Note that I'm using svelte and initially had another problem - same as [Why does Tone JS not play nice in a Svelte component?
](https://stackoverflow.com/questions/55039122/why-does-tone-js-not-play-nice-in-a-svelte-component?rq=1) on stackoverflow, which seems to have gone away for me now but perhaps this is related? (don't really know why it went away, maybe because I don't reference Tone from within the component anymore - it's split into a separate js file which is imported into the svelte component.

**Comment by tambien** [comment]
`global` is a variable added by webpack, so i can see how you would run into this problem if you were using a different bundler. 

There are a few solutions to the issue that i can think of: you can define the global object as webpack does before you import tone i think it should be something like `global = typeof self !== 'undefined' ? self : this`. You could also try out the experimental `tone@typescript` branch which deals with the window object differently and does not rely on webpack for that part. Currently not all of the modules are converted to typescript, but if you're using only basic ones, then it might be sufficient (and of course [contributions are super helpful](https://github.com/Tonejs/Tone.js/wiki/Typescripting-Tone.js))

Not sure where Tone.js is violating strict-mode as the SO overflow answer says, but help pointing that out is also appreciated. I assume that the typescript branch wouldn't have that issue either since the javascript code is generated by `tsc`.

**Comment by myleftshoe** [comment]
Thanks @tambien, that fixed it! Specifically I added the `intro:` property to `rollup.config.js` which puts the global def at the top of `bundle.js`.
```
output: {
	sourcemap: true,
	format: 'iife',
	name: 'app',
	file: 'public/bundle.js',
	// Added this line:
	intro: 'var global = typeof self !== undefined ? self : this;'
},
```
