### ISSUE TITLE
Filter rolloff of -6

### ISSUE THREAD

**Issue by JackCA** [Tonejs/Tone.js#531]
I'm trying to reimplement the [soundfont spec](http://freepats.zenvoid.org/sf2/sfspec24.pdf) and it requires a 6db low-pass filter rolloff. Is there a particular reason why 12 is the highest value allowed there?

If there's no particular reason, I'm happy to open a PR

**Comment by tambien** [comment]
Unfortunately it's not not possible with the [BiquadFilterNode](https://webaudio.github.io/web-audio-api/#biquadfilternode) which according to the spec "implements a standard second-order resonant lowpass filter with 12dB/octave rolloff." Tone.js Filter has a rolloff of just 12, 24, 48, and 96 which are achieved through chaining these BiquadFilterNodes. 

It's possible to create a first order lowpass with the new IIRFilter, but the frequency could not be an audio-rate Param in that case so it wouldn't mix well with the existing Tone.Filter. 

That said, if you were keen to take a stab at contributing a OnePoleFilter with a non-audio-rate frequency parameter, that'd definitely be appreciated. If you do contribute, it'd be great if you could add it to the `typescript` branch since that already has a cross-browser shim for the IIRFilter.

**Comment by JackCA** [comment]
@tambien okay that totally makes sense that it's a limitation from the base web audio implementation.

It's not noticeable enough that I'll try and tackle the OnePoleFilter rigth now but I might take a stab at in the near future.

Thanks!

**Comment by JackCA** [comment]
@tambien are you aware of a way to emulate/approximate the effects of a 6db filter using the existing nodes available? Possibly by altering the filter frequency?

**Comment by tambien** [comment]
It's possible to do with the IIRFilterNode, though i haven't figured out the right coefficients yet to create a single low-pass filter. If you figure out how to do it, please share! 

http://www.earlevel.com/main/2012/12/15/a-one-pole-filter/

**Comment by JackCA** [comment]
@tambien whoops, sorry -- I wasn't very clear.

I meant more so altering the 12db rolloff's filter frequency to most closely emulate the 6db rolloff's effect.

**Comment by tambien** [comment]
not that i'm aware of, but that doesn't mean that there isn't.
