### ISSUE TITLE
Tone.Signal crackling sound

### ISSUE THREAD

**Issue by lukephills** [Tonejs/Tone.js#55]
I'm trying to use a Tone.Signal as a gain node, but when I set new values I hear a slight crackling sound but no change to the gain. Is this the right way to use Signals?

`this.Effect = new Tone.Signal(1, 'db');`
`this.Effect.value = newValue;`

I've tried using different units but I still can't get it work.

**Comment by tambien** [comment]
that looks right in terms of constructing a signal. can you post a minimal example? What are you routing that signal to?

is it possible that you have the signal somehow connected directly or indirectly to the master output? that would make your output have a DC offset and could make things crackle and clip.

**Comment by lukephills** [comment]
Yes it's being routed to another Signal and then .toMaster()

https://docs.google.com/file/d/0B-FXQg_VQV3JdXVQMDBFN090U3c/edit

**Comment by tambien** [comment]
I have two guesses: first i would use Tone.Meter to see what kind of values you're getting on your output. The normal range is centered around 0 and +/- 1. If you have a signal connected to the output, there's a chance you've got a DC offset which would cause clipping on the output. When the noise isn't playing, the value at the output should be 0. 

The second suggestion would be to use the `rampTo` method when changing values. The difference here is that instead of setting a new value right away (which would cause an audible jump in values known as zippering), you smoothly interpolate between the values.

**Comment by tambien** [comment]
Any updates on this?
