### ISSUE TITLE
Broken timing when using Tone.Sequence or Tone.Loop to trigger the NoiseSynth

### ISSUE THREAD

**Issue by chaosprint** [Tonejs/Tone.js#552]
This is more prominent when the number of notes is 16.

Definition:

```
const lowPass = new Tone.Filter({
  frequency: 1000,
}).toMaster()

const noise = new Tone.NoiseSynth({
  noise: {
    type: 'pink',
  },
}).connect(lowPass)
```
Neither of Loop nor Sequence works:
```
var loop = new Tone.Loop(function(time){
	noise.triggerAttack()
}, "16n")

Tone.Transport.stop()
Tone.Transport.start()
loop.start().stop("4m")
```

```
var seq = new Tone.Sequence(function(time, note){
	noise.triggerAttack()
}, [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16], "16n")

Tone.Transport.stop()
Tone.Transport.start()
seq.start().stop("4m")
```

**Comment by tambien** [comment]
Here's an example of your code with some slight modifications which tighten up the timing: 
https://codesandbox.io/s/noise-synth-timing-example-h6ewq

```js
var seq = new Tone.Sequence(function(time, note){
	noise.triggerAttack(time)
}, [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16], "16n")
```

The timing is approximate because you are not using the passed in 'time' value to the callback functions. Javascript timing is not sample-accurate (pretty loose in fact), which is why there is a precise time value passed into the callback functions.

Going to close this issue. Please comment or reopen if it's still not working for you.
