### ISSUE TITLE
artifact when playing note with note value of 0.5

### ISSUE THREAD

**Issue by walterbender** [Tonejs/Tone.js#560]
Here is a simple script to demonstrate the problem:
<pre>
	<script src="lib/Tone.js"></script>

	<script type="text/javascript">
           var synth = new Tone.PolySynth(8, Tone.AMSynth).toMaster();
	  synth.triggerAttackRelease('G4', 0.5);
	</script>
</pre>

Any value except 0.5 seems to work fine. With 0.5 there is a strange pop at the end of the sound.
Try 0.49 or 0.51. They sound fine.

Tested on Firefox 69.0.3 (64-bit) on Fedora. Also experienced the problem with Chromium.

**Comment by walterbender** [comment]
Forgot to mention: Tone JS Release 13.8.25

**Comment by tambien** [comment]
The issue was that the attack/decay portion of the envelope was exactly 0.5 seconds long and the release was triggered at the exact moment the decay ended, it caused it to cancel the previous anchor point. Should be fixed in the latest `tone@typescript`. [Here's a demo](https://codesandbox.io/s/amsynth-pop-4ill8).
