### ISSUE TITLE
GrainPlayer long lookahead cannot play immediately

### ISSUE THREAD

**Issue by JackCA** [Tonejs/Tone.js#570]
I think this is probably related to https://github.com/Tonejs/Tone.js/issues/568, but when using a long latencyHint like `playback` you cannot schedule a `GrainPlayer` start event that occurs before the `latencyHint` (like using `immediate()`).

[Example](https://jsfiddle.net/JackCA/qjpze351/19/)

(apologies for all of the issues 😬)

**Comment by tambien** [comment]
GrainPlayer uses Tone.Clock internally which means it'll always have the lookAhead applied to its scheduling. The callback of the clock is invoked with a `lookAhead` in order to give enough time to schedule the events in the callback. 

In this example you're sort of asking for two things that are at odds with each other, which is that you'd like everything to be scheduled far in advance to keep stable playback, but for two of these things to start immediately.

I added slightly more explanation to `immediate` to illustrate the difference between it and `now` and recommended in most cases `now` be used over `immediate`. Let me know if this explanation is clear enough.

**Comment by JackCA** [comment]
Yeah I was worried that there was no distinction between scheduling immutable events far in the future versus this GrainPlayer scheduling example.

If they are intrinsically linked,  I guess what I'm looking for is a way to have two transports: one for interactive feedback, and one for rarely mutated events that need a more stable clock.

Looks like this was explored in https://github.com/Tonejs/Tone.js/issues/108.

Can you suggest any way to achieve what I'm going for? As an example, if you go to [midi.city](https://midi.city), I'd like the keyboard to have low-latency + lower accuracy, but the drum machine loops to have high accuracy + high latency.

**Comment by JackCA** [comment]
And FWIW, I'm using `Tone.Part` -- maybe we could implement an optional unique lookahead for an instance it that is greater than or equal to the global lookahead?

**Comment by tambien** [comment]
The typescript branch makes it much easier to have 2 audio contexts running in parallel. All nodes on the typescript branch can have a context passed into the constructor. So, as long as the two don't need to be connected to each other or share any of the same timing, you can do something like this: 

```javascript
import { Context, Oscillator } from "tone"
const ctxA = new Context({lookAhead: 0.01})
const ctxB = new Context({lookAhead: 0.5})
const oscA = new Oscillator({context: ctxA})
const oscB = new Oscillator({context: ctxB})
```

This will also give you two transports (accessible from `ctxA.transport`). 

`lookAhead` is tied to the Context so it can't be on a per-object basis. The concept behind a fixed lookAhead is to synchronize and maintain timing across all nodes, sort of like you might have Delay Compensation in most DAWs; as long as everything is delayed equally, you can maintain tight timing.

**Comment by tambien** [comment]
I'm going to close this issue. For now there is no way around managing multiple lookAheads in the same Context.

**Comment by JackCA** [comment]
Sounds good. I may look into the multi-context solution, that's a great feature.

I'd have to duplicate a lot of nodes into each context but it may be worth it.
