### ISSUE TITLE
Typescript Perf Degradation: Freeverb + JCReverb

### ISSUE THREAD

**Issue by JackCA** [Tonejs/Tone.js#571]
In the typescript branch, it appears that just by creating multiple `JCReverb` or `Freeverb` instances, even if they aren't connected to anything, will create pretty significant performance issues.

The issue is more pronounced with `Freeverb` and the issue doesn't appear with `@next`.

[Example](https://jsfiddle.net/JackCA/wuq8hg5L/9/)

**Comment by tambien** [comment]
I've revamped one of the main components of these two nodes which is the FeedbackCombFilter which is probably the cause of this performance issue. The rewrite is entirely using the AudioWorkletNode which produces much better results which are more "correct" than using the feedback delay which caused some discontinuities in the output. The issue is that now it requires much more processing for these nodes which use a lot of AudioWorkletNodes like these two reverbs. 

I'm thinking of just deprecating these nodes and recommending users just use `Reverb` and/or adding a notice in the docs which explains that users should expect poor performance with these nodes. That is until i figure out how to optimize the performance of the AudioWorkletNode (and maybe iron out a few bugs in Chrome and FF's implementations).

The specific issue that you mention of poor performance even when nothing is connected is because the rendering callback is always returning `true` in the [rendering callback](https://github.com/Tonejs/Tone.js/blob/typescript/Tone/component/filter/FeedbackCombFilter.ts#L144-L146), which means that it's always processing even when there are no connections. I think there might be a bug in Chrome which causes it to be silent until i add that in there. i haven't had time to investigate further which is why i'm just returning `true` in all cases for now.

**Comment by JackCA** [comment]
Thanks for the thorough explanation on this. The fix for https://github.com/Tonejs/Tone.js/issues/569 should unblock me from using `Reverb` instead of either of these nodes.

I think adding notes in the release/docs about the performance differences would be helpful for sure.

However, as I was reading Paul's notes on [Reverb performance](https://padenot.github.io/web-audio-perf/#cheaper-reverb), he specifically mentions that ConvolverNode's are more CPU intensive. 

I think it would be nice to be able to allow the user to choose between a more correct or more performant node.

If given the choice, and due to how complexity of the audiograph I'm working on, I would opt-for performance over correctness.

Would you consider winding back and keeping one of the "less correct" nodes around? I know maintaining the old implementation moving forward may be pain, but just throwing my 2 cents in.

**Comment by JackCA** [comment]
should I close this?
