### ISSUE TITLE
Safari + TypeScript branch: No GrainPlayer Audio

### ISSUE THREAD

**Issue by JackCA** [Tonejs/Tone.js#572]
It appears that no audio is emitted when using a `GrainPlayer` in Safari.

[Example with annoying looped sound](https://jsfiddle.net/JackCA/84bwh3mt/9/)

**Comment by tambien** [comment]
Seems like probably an autoplay issue. [The context is still 'suspended'](https://jsfiddle.net/yotammann/j2fm3xvq/). 

Try initiating the sound with a user interaction. lmk if that fixes it.

**Comment by JackCA** [comment]
@tambien I've updated the fiddle to require an interaction and added a regular `Player` as well. The `Player` works but `GrainPlayer` doesn't.

Might be related to https://github.com/Tonejs/Tone.js/issues/570?

**Comment by JackCA** [comment]
I've actually updated the example to remove the loops so you can hear if something is triggered or not. What's strange is that:
1. Press "start player"
2. Sound starts
3. Press "start grain player"
4. sound starts

but if reloading
1. Press "start grain player"
2. No sound

**Comment by tambien** [comment]
Still seems like a autoplay issue to me. If i log the state of the console after starting the GrainPlayer it still says 'suspended' in Safari: https://jsfiddle.net/yotammann/75ugyLom/

The relevant difference between Player and GrainPlayer in this situation is that GrainPlayer does not create and start AudioBufferSourceNode on start like Player does on click (which would satisfy the autoplay starting the context). Instead GrainPlayer starts a clock and in the clock's callback function it creates and starts the underlying AudioBufferSourceNodes. 

The surest way to fix this issue is to explicitly call `Tone.start` and wait for the promise to resolve before trying to start or schedule anything.

**Comment by JackCA** [comment]
You're right, [here's what happens with `Tone.start` in the callback. ](https://jsfiddle.net/JackCA/d0gnpukj/)

I was incorrectly assuming that if `Player` automatically started the context, then `GrainPlayer` would do the same.

I wonder if having some sort of developer feedback via the console would be helpful in situations where `start` is called on a 'suspended' context would be helpful?

Regardless, closing this. Sorry for the noise.
