### ISSUE TITLE
Safari + Typescript Branch: Panner no sound

### ISSUE THREAD

**Issue by JackCA** [Tonejs/Tone.js#574]
It seems that there's been a regression where a `Panner` node does not work in the typescript branch on safari.

I hear a small pop sound, but the same code works in `@next` 

[Example typescript](https://jsfiddle.net/JackCA/p1xLbq4n/8/)
[Example @next](https://jsfiddle.net/JackCA/gb3yq2ua/1/)

**Comment by tambien** [comment]
thanks for all your testing of the typescript branch! 

From what i can tell, this might be an issue with standardized-audio-context. And it seems like the issue might be fixed in the latest release. [Here's a minimal example](https://codesandbox.io/s/safari-stereo-panner-gel3i) of just standardized-audio-context@22.0.2 (which is what Tone.js is currently using). 

If you set it to 23.0.0, it seems to work ok. I'll update the dependency and see if the issue persists in Tone.js

**Comment by JackCA** [comment]
Just switched my local fork to use 23.0.0 and it does indeed seem to work :+1:

Could make a PR but assuming you want to check if there are any other issues

**Comment by tambien** [comment]
feel free to make a PR if all the tests pass. that’d be helpful to save me a little time.

**Comment by tambien** [comment]
closed by #576
