### ISSUE TITLE
Request: Add feedback option to Chorus to make a flanger

### ISSUE THREAD

**Issue by DannyDane** [Tonejs/Tone.js#575]
Hi there,

As I understand, the only differences between a Chorus and a Flanger are these:

1) A Flanger has a shorter delay time than a Chorus.

2) The delay time of a Flanger modulates to 0, but doesn't with a Chorus.

3) With a Flanger, the delay has feedback, with a chorus it doesn't.

You can do the first 2 with the current implementation, but not the 3rd.

Would it be possible to add a feedback option to the Chorus?
If it is as simple as swapping the Delay for a FeedbackDelay I could try it myself, although I'm not entirely familiar with Tone's architecture.

Or maybe make Flanger is own, separate effect. But I wouldn't know how to do that without copying alot of code from the Chorus effect.

Thanks in advance

**Comment by tambien** [comment]
I made Chorus extend StereoFeedbackEffect instead of StereoEffect which now gives it a feedback property. I test it out and with the right settings you get flanger-y effects. With `chorus.feedback.value = 0` it is the same old chorus effect. 

I'll also add a note in the docs which mentions that this effect can be used for both chorus and flanger effects

**Comment by DannyDane** [comment]
That's awesome. Thanks tambien!
