### ISSUE TITLE
Problem with importing tone.d.ts file

### ISSUE THREAD

**Issue by pleshakovalexander** [Tonejs/Tone.js#579]
![image](https://user-images.githubusercontent.com/50041552/68994667-9f5cd800-0896-11ea-8b28-927dfa71254c.png)
but it's here
![image](https://user-images.githubusercontent.com/50041552/68994672-c1eef100-0896-11ea-86b9-9b3dec882b3b.png)

**Comment by tambien** [comment]
There were a number of issues with that d.ts file so i ended up removing it from package.json. i guess the file was still being generated on build, but package.json no longer points to the file which is why your compiler isn't finding it. 

Going forward, it's best to just use install `tone@typescript`. the `typescript` branch is rewritten in typescript so should work well with a typescript project.

**Comment by pleshakovalexander** [comment]
@tambien can You add it to readme file for tone.js so fewer people will create this type of issue? 
Sorry for not searching for similar issues 😔

**Comment by tambien** [comment]
@pleshakovalexander no problem! good suggestion. i'll be sure to document typescript usage in the README once i'm done with the rewrite (which is hopefully soon!)

**Comment by xerosanyam** [comment]
@tambien eagerly waiting! Thanks for the hard work :)
