### ISSUE TITLE
Sequence playing notes multiple times in callback

### ISSUE THREAD

**Issue by bring2dip** [Tonejs/Tone.js#580]
I was trying to arpeggiate notes . I tried using Tone.Sequence for this. However, when I call/play the function to play the sequence, the notes are played multiple times.

First Call:
```
note, seqTime C4 3.846027178065821
note, seqTime E4 3.9464048979942876
note, seqTime G4 4.105932631765658
```

Second Call
```
note, seqTime C4 6.195315101800973
note, seqTime C4 6.196835114504218
note, seqTime E4 6.311545028802484
note, seqTime E4 6.3175260184741795
note, seqTime G4 6.448273617945778
note, seqTime G4 6.450643820818717
```

Here's the link to [JSFiddle](https://jsfiddle.net/bring2dip/qrLsx0nh/16)

I also posted this question on google group and @dirkk0 pointed out that the sequence initialization should be out of the function. That works but what if I want to have dynamic division and events.

**Comment by tambien** [comment]
I think @dirkk0 is right. The issue is that you are creating a new Sequence in the `play` function each time the function is called. If you'd like to create a new sequence each click be sure to dispose the previous one so that you are not hearing both. If you'd like the same sequence but at a different rate, try setting the `playbackRate` of the sequence to get different timing

**Comment by bring2dip** [comment]
I'm sorry to ask but is there a Static method or any global method to dispose previous sequence. In the `play` function how would i dispose previous sequence before the new one is created. I don't find it in the documentation.

**Comment by tambien** [comment]
I would probably just assign it to a variable that lives outside the function. and then in the function do something like: 

```javascript
if (previousSequence){
  previousSequence.dispose()
}
previousSequence = seq
```

**Comment by bring2dip** [comment]
It works great but this looks more of a hack. Is there any reason to not clear the previous Sequence by default? Because the Sequence is instantiated, I believe every instance should start clean.

**Comment by tambien** [comment]
Not sure i completely understand what you mean by "start clean". In Tone.js, generally anything you create with `new` will persist until you explicitly dispose it. That's why all of the previous Sequences that you create persist outside of the `play` function call. Clearing the previous Sequence would imply to me that it would only be possible to have one sequence at a time.

**Comment by bring2dip** [comment]
Okay I understand. Thanks for helping me out. And I wish the thing you said about `explicitly disposing` was on documentation.
