### ISSUE TITLE
Feature request: PolySynth could expose voice accessor

### ISSUE THREAD

**Issue by Y0hy0h** [Tonejs/Tone.js#582]
`PolySynth` conceptually has a map from `Note`s to `Voice`s. I need to specify a note when I `triggerAttack("C4")` and then specify that same note to stop it with `triggerRelease("C4")`.

I would like to implement pitchbending on a polyphonic instrument, for which I tought I could do something like
```
poly.triggerAttack("C4");

// ...

// Now I want to slightly shift that note. For simplicity, I'll change it to a "D4", but in reality I would like to increment the frequency only slightly.
const voice = poly.getVoice("C4");
if (voice != null) {
  voice.setNote("D4");
} else {
  console.error("Voice not found.");
}
```
Of course, there is no public `getVoice()` method.

This example points to an issue, however: If I trigger a `C4` and a `D4`, and then I pitch shift the `C4` to also be a `D4`, how do I address the correct `D4`? This address scheme practically prevents the same note from being played twice.

There are multiple solutions here:
1. Expose this voice getter, such that the voice can be controlled beyond triggering attack and release. Accept the tradeoff with not being able to address the same note playing twice correctly.
2. Keep the same note as the id, even if the actually played note becomes different. (This would enable the special case of shifting the `C4` to a `D4` from above, but still prevents two triggered `D4` notes from being addressed freely.) 
3. Return an id from `triggerAttack()` that has to be passed to `triggerRelease()`.
4. Reverse the addressing: Allow the caller of `triggerAttack` to pass some id. That same id can then also be used in `triggerRelease()`. (The advantage of this is that the id does not need to be passed back to a remote caller. The disadvantage is that if messages are dropped, the caller might assume that an id is free for reuse, when it has not yet been cleared by the `PolySynth`. However, the caller can mitigate this in their use of ids.)

What are your thoughts on such a feature?

**Comment by Y0hy0h** [comment]
I will probably implement a `PolySynth` alternative that handles my requirements. If that works, I can share the code.

**Comment by tambien** [comment]
Thanks for the question. I'm not sure the added complexity would provide any advantage over simply creating multiple Synths and managing each voice individually which would allow you to have precise control over each voice. 

An issue that comes to mind is that since `triggerAttack` and `triggerRelease` are both schedulable parameters, `getVoice` would have to be `getVoiceAtTime(note, time)`. So for example if you schedule multiple notes in the future, `getVoice` would need to disambiguate which voice you were referring to in order to return the correct one. 

If `triggerAttack` and `triggerRelease` took an 'id', it might cause some breaking API changes. And returning the original synth voice would break the memory ownership convention in Tone.js. Since currently PolySynth manages all of the voices, so it is able to create and dispose of voices. If a voice were returned, it might not be able to dispose the voice since the caller would have a reference to that voice. 

I'm not sure i have a vision for how to build this feature without adding a lot of complexity. And the current alternative of just creating multiple synths seems pretty straightforward. I'd be curious to see your implementation, so please send it along when you've got it to a solid place. It'd be great to see how you tackle this.

**Comment by Y0hy0h** [comment]
You're right. When I tried implementing this, I basically ended up with a "default map", i. e. a map that I could `get(id)` on and that would simply generate a default voice, if there was none. And even that does not feel flexible enough for the two instruments I'm programming, so I'll probably end up with custom voice management in each instrument.

So I initially thought this would be a simple, straightforward feature, but I realize that it is hard to properly generalize. I agree that it's best to keep PolySynth as is for the common use case of triggering and releasing multiple voices.
