### ISSUE TITLE
using Noise to control a Synth.frequency causes endless sound

### ISSUE THREAD

**Issue by chaosprint** [Tonejs/Tone.js#585]
```
var synth = new Tone.Synth(440, "sawtooth").toMaster()

/* var lfo = new Tone.LFO(10, 400, 4000);
lfo.connect(synth.frequency);
lfo.start() */

var scale = new Tone.Scale(500, 1000);
var noise = new Tone.Noise().connect(scale)
scale.connect(synth.frequency)
noise.start()

var loop = new Tone.Loop(function(time){
	synth.triggerAttackRelease("C1", "8n", time)
}, "4n")

Tone.Transport.start()
loop.start(0).stop('2m')
```

The same for LFO (see the commented part).

By the way, is there any method to select a certain pitch every time the synth is triggered?

**Comment by tambien** [comment]
Seems like there was a problem when the signal was overridden, through a connected signal like in your example. It was not converting the scheduled note to a frequency value. 

Should be fixed now in `tone@>=14.5.0`. Here's a fork of the code that you posted: https://codesandbox.io/s/issue-585-gceuf

In this case "C4" or any pitch you want to schedule in the synth is disregarded since the value is being overridden by the connected signal.
