### ISSUE TITLE
Typescript Branch: Player implicitEnd timeline issue

### ISSUE THREAD

**Issue by JackCA** [Tonejs/Tone.js#594]
It appears that some recent changes in the typescript branch make it so that [the `implicitEnd` event in `Player`](https://github.com/Tonejs/Tone.js/blob/typescript/Tone/source/buffer/Player.ts#L226-L228) prevents the player from starting again before that time by emitting a `The time must be greater than or equal to the last scheduled time` error.

I believe the fix may be to cancel that event if it exists when starting again.

[Example](https://jsfiddle.net/hjarnkpy/2/) -- should through an error in the console and does not happen 100% of the time it is run

**Comment by tambien** [comment]
Do you have an example which throws this error more consistently? of the hundreds of times i've run this code, i've only seen the error once or twice. makes it hard to find any fix. i've currently got it running in a tab auto refreshing itself every 2 seconds to try and trigger the error. 

I'm not sure it's line that you pointed to since it current isn't waiting for the end of the buffer to finish otherwise it wouldn't be able to retrigger so rapidly. [If the source is still playing, it'll restart it](https://github.com/Tonejs/Tone.js/blob/typescript/Tone/source/Source.ts#L254-L261).

**Comment by JackCA** [comment]
It consistently happens for me when I use a looped @tone/midi-based `Tone.Part` and that example is way too convoluted to be helpful.

If I throttle my CPU in chrome developer tools, I don't trigger the error with that example code so it must be correlated to performance timing in some way.

As clunky as it may be, I can offer any debug info that you want since I can trigger it

**Comment by tambien** [comment]
does it make any difference if you schedule with the specific time passed in from the part instead of immediately? also does the issue only happen immediately on startup or does it happen after it's been running for a second?

**Comment by JackCA** [comment]
> does it make any difference if you schedule with the specific time passed in from the part instead of immediately?

Yes, but not in that example. I'm going to put something together that looks more like what I'm seeing in production

> also does the issue only happen immediately on startup or does it happen after it's been running for a second?

I'll hear a few notes play and then it triggers the error

**Comment by JackCA** [comment]
@tambien [Check out this example](https://jsfiddle.net/wge98452/)

**Comment by tambien** [comment]
i'm seeing those first two midi events have the same `time` value. i think that might be the root of the error. i think you shouldn't be able to schedule two events at the same time. 

I think this should probably throw an error:

```javascript
const time = player.now() + 0.1
player.start(time)
player.start(time)
```

There does seem to be more to this though since the above code doesn't throw an error. only when you invoke it a third time does it throw the error (like so)

```javascript
const time = player.now() + 0.1
player.start(time)
player.start(time)
player.start(time)
```

Still investigating, but that's what i've found so far

**Comment by JackCA** [comment]
just FYI: I only have a single player here for the sake of the example; in the realworld application, there are multiple players uniquely associated to each midiNote.

**Comment by tambien** [comment]
that makes sense. if you're using separate players, then it wouldn't throw this error. i've added an assertion to make sure that this code throws an error:

```javascript
const time = player.now() + 0.1
player.start(time)
player.start(time)
```
 Will now throw: `"Start time must be strictly greater than previous start time"`, so would be easier to catch the scenario where you're accidentally scheduling the player twice with the same time.

**Comment by JackCA** [comment]
I think that error is really helpful and an improvement; unfortunately, the example wasn't a great representation of what's happening in production because this original error continues to occur.

[Here's another version that uses different players for each midiNote](https://jsfiddle.net/JackCA/zmohs694/3/) -- note that we're not getting the new error you introduced.

**Comment by tambien** [comment]
took another swing at a solution. works for me locally and seems to have stopped the error in the fiddle that you posted. let me know if you're still seeing that issue

**Comment by JackCA** [comment]
That was it! 🎊 All good
