### ISSUE TITLE
Can't detune one of the MonoSynth when using it in a DuoSynth in a PolySynth

### ISSUE THREAD

**Issue by maximedupre** [Tonejs/Tone.js#602]
Please see this simple example: https://stackblitz.com/edit/tone-js-issue-602

As you can see, I tried detuning the MonoSynth, but that didn't work. So I tried to detune it's OmniOscillator, but that didn't work either.

Do you have anything I could use/hack with the internals or something? I would like to make it work quickly in the short term.

Cheers!

**Edit 1** 

Also tried using the `set` method, but it doesn't work.

**Edit 2** 

Same thing occurs with the volume (can't set the volume of individual voices). I guess it occurs with every param.

**Edit 3**

Updated example

**Edit 4**

Nvm, it works well with the volume.

**Edit 5**

Also there is now way to attach an LFO to each MonoSynth (voice1/voice2 of the DuoSynth) as it was previously possible in the non-typescript branch. Should I create a new ticket for that?

**Comment by tambien** [comment]
The detune for DuoSynth is on the top level object not the individual voices/oscillators. 

https://stackblitz.com/edit/tone-js-issue-602-qgji3r?file=index.ts

In order to avoid having the same parameter being settable in multiple places, i've hoisted the inner detune values wherever possible as in this case of DuoSynth and MonoSynth. The detune is not settable on the oscillator object, just on the synth itself. TypeScript makes it easier to enforce this behavior which wasn't as easily possible in previous versions of Tone. 

If you'd like a detune between the two voices, i would use the harmonicity parameter to do that.  

Not sure why it wouldn't be possible to set an LFO on either of the voices. Please open an issue for that.

**Comment by maximedupre** [comment]
Got it! The harmonicity param isn't flexible enough though, so maybe keep that as a feature request for the future?

Cheers!

**Comment by tambien** [comment]
Im curious why the harmonicity param isn’t flexible enough?

**Comment by maximedupre** [comment]
Let me know if I'm wrong, but I don't think the harmonicity param would let me, let's say, detune oscillator/voice 1  to -2443 (~-2 octaves) and detune oscillator/voice 2 to 3589 (~+3 octaves).

**Comment by tambien** [comment]
I think something like this should work. obviously a little more verbose, but avoids the issue of having multiple parameters controlling the same thing. 
 
```javascript
const difference = (3589 - -2443) // the difference between the two is the harmonicity ratio
const interval = difference / 100 // convert it from cents to semitones
synth.harmonicity.value = Tone.intervalToFrequencyRatio(interval)
synth.detune.value = -2443 // set the base offset
```

**Comment by maximedupre** [comment]
Nice, that worked! Thanks a lot.

```javascript
private setPolySynthHarmonicityAndDetune(
	octaveOsc1: number,
	detunePercentageOsc1: number,
	octaveOsc2: number,
	detunePercentageOsc2: number,
	isSettingOsc1: boolean
) {
	const osc1DetuneInCents =
		octaveOsc1 * CENTS_PER_OCTAVE +
		detunePercentageOsc1 * CENTS_PER_OCTAVE
	const osc2DetuneInCents =
		octaveOsc2 * CENTS_PER_OCTAVE +
		detunePercentageOsc2 * CENTS_PER_OCTAVE
	const difference = isSettingOsc1
		? osc1DetuneInCents - osc2DetuneInCents
		: osc2DetuneInCents - osc1DetuneInCents
	const interval = (isSettingOsc1 ? -difference : difference) / 100
	const harmonicity = Tone.intervalToFrequencyRatio(interval)
	const detune = osc1DetuneInCents

	this.synthAudioNodes.polySynth.set({ harmonicity, detune })
}
```

Some logic needs to be reversed when setting voice1 or voice2.

Cheers!
