### ISSUE TITLE
Official Tone.js Examples are causing crackling on my android phone

### ISSUE THREAD

**Issue by designcourse** [Tonejs/Tone.js#604]
I have a Samsung Galaxy S8+ (Android 9, Chrome 79), and my wife has a Samsung Galaxy Note 8 -- If I visit:
https://tonejs.github.io/examples/simpleSynth.html and just press a key for a long time, the crackling occurs almost immediately.

This also happened in my own project when I was sending a simple triggerAttack, and also with a sequence. I thought it was just my code, so that's why I checked out the official examples and they're doing the same.  Firefox and Chrome on my desktop are perfectly fine.

Any ideas here?

**Comment by tambien** [comment]
Seems like it's most likely performance crackling. There's a chance also that it's somehow clipping on the software side, so you can try setting the output of Tone.js to lower (`Tone.Master.volume.value = -10`). 

If it's performance limitations of the device, you can try using just the 'basic' oscillator instead of the 'am' or 'fm' oscillator which might be a little lighter on the processor. My guess since it happens on sustained notes is that it's not really anything that i can fix on the Tone.js-side, but a limitation of running the Web Audio API on your phone. 

Have you run any non-Tone.js example to compare the performance of vanilla Web Audio vs Tone.js? There's a simple fm synth example [here](http://www.taktech.org/takm/WebFMSynth/). Let me know if it runs any better than the Tone.js synth

**Comment by designcourse** [comment]
It's not just on sustained notes, it happens on regular non-sustained notes during sequences or loops too. 

I tried out that simple fm synth example, and it still crackles on my phone.  I'm starting to think it's just an issue with our devices/current version of the OS and/or Chrome. 

I tried out these examples on my daughter's Amazon Kindle Fire HD10 tablet and it was fine -- had my mom try them out on her old iPhone and it works fine. 

Hopefully an update to Android will fix the issue(s).  

Thanks!

**Comment by tambien** [comment]
@designcourse thanks for following up. yeah it's unfortunate that the Web Audio API's performance varies so much between devices. There's only so much i can do if the underlying device can't support certain things. 

I'm going to close this. but if you or anyone discovers there's something specific that can be done for this device, please share!

**Comment by easycodeboy** [comment]
Same problem here on phone using audio or synth. But have had others try it on their now-faster processor phones and it seemed to not be there anymore-suggesting to me a processor performance issue. But now I get a double play when playing an .mp3 note on the phone-but not on desktops or laptops.  https://icanplaypiano.com//  Any suggestions?

**Comment by leotohill** [comment]
I experienced the problem on a pixel 6 device.  Setting sampler.Volume = -5 corrected the issue.

**Comment by easycodeboy** [comment]
Thank you. Forgot I had the problem. Seems like it ended when I switched from using P5.js to straight html.
