### ISSUE TITLE
Can't attach an LFO to voice0 and voice1 of a DuoSynth in a PolySynth

### ISSUE THREAD

**Issue by maximedupre** [Tonejs/Tone.js#608]
As talked about in https://github.com/Tonejs/Tone.js/issues/602, I'm creating a new ticket.

The problem is that there doesn't seem to be a way to connect the LFO to each voice independently on the DuoSynth of the PolySynth.

`lfo.connect(?)`

To my knowledge, the public API does not have a functionality that exposes the underlying voice instances of the PolySynth. But that wouldn't help a lot, because then we would need to attach the LFO to each new instance and need a way to be notified of new instances. 

We would need to be able to tell the PolySynth that every new DuoSynth instance should have an LFO attached to voice1 and another LFO attached to voice 2.

``` javascript
const polySynth = new PolySynth(DuoSynth)
const futureDuoSynthsBlueprint = polySynth.blueprint

lfo1.connect(futureDuoSynthsBlueprint.voice0.volume) 
lfo2.connect(futureDuoSynthsBlueprint.voice1.volume) 
```

I hope this makes sense or that it's less complicated than I envision the problem to be ^^.

Cheers!

**Comment by tambien** [comment]
Thanks for clarifying that from #602. Unfortunately, this isn't possible at this time. PolySynth doesn't expose the voices since that would complicate the dynamic voice managing. 

Your intuition about adding a prototype of the voice and connecting to that i think would be the way to do that, but this is not something that's implemented. Though i'm happy to review a PR. The considerations there would be an implementation that doesn't add a lot of performance overhead and is easily extensible as new synth types are added. 

The only way to currently pull this off would be to create and manage your own DuoSynth voices.
