### ISSUE TITLE
Clarification about versions

### ISSUE THREAD

**Issue by cristiano-belloni** [Tonejs/Tone.js#611]
Hi, this is not a bug I can repro, but I'm incredibly confused about versions and documentation.
I am running a project made with Tone, and `npm i` seems to install `v13.8.34`. I'm happy with that, and it works well enough for me.

I'm about to do some Offline work, and [this comment](https://github.com/Tonejs/Tone.js/issues/368) suggests using the new `@next` version, which installs as version 14 and, for some reason, breaks my app (no sound if I `.sync()` a Player. I have a complex application and couldn't repro the issue so far).

On top of that, [npm](https://www.npmjs.com/package/tone) suggest that the `latest` of Tone is `13.8.25`, which I know wouldn't work for me [because of this issue that was solved in a later version](https://github.com/Tonejs/Tone.js/issues/540).

Obviously, I use documentation from the main site (https://tonejs.github.io/docs/), but I have no idea which of the versions the docs refer to, so it's extremely frustrating to try and solve the v14 mysterious issue with docs that are potentially for v13 (and which one?)

Could anyone please shed some light on how versioning and documentation works for this project?

**Comment by tambien** [comment]
tone@latest is 13.8.25 and tone@next is currently 14.5.30

You can find the version which corresponds to what you've installed using the terminal

```bash
npm show tone@next version
```

`next` is the development version which is why it is so far ahead. The docs on the main page are for the `latest` version which is the stable version. 

You can find the docs for the `next` version by using the version number in the URL for example: 

https://tonejs.github.io/docs/14.5.30/Transport

The docs for the `next` version are updated once daily so not all version numbers are in there, just the version as it was at the end of the day.
