### ISSUE TITLE
distorted/high bass sounds after replaying sound several times

### ISSUE THREAD

**Issue by pidddgy** [Tonejs/Tone.js#613]
after playing a sound several times, the sound becomes distorted and all other sound e.g. sound coming from desktop apps, other tabs are also distorted.

I've created a demo here: https://github.com/pidddgy/tonejstest. To reproduce, just open index.html and click the button really fast over and over.

The original context of the issue is here: https://github.com/llaske/sugarizer/issues/564

**Comment by tambien** [comment]
Seems like most likely the crackling is coming from overloading your system. You are creating new player and pitchshifter each time. These components (especially the PitchShifter) are meant to be reused since they correspond to web audio nodes under the hood. 

The player is pretty light weight, but the PitchShifter is composed of a number of components with a feedback loop which would make it difficult for the garbage collector to remove it. 

I'd suggest that you reuse the components and just trigger `player.start()` each time in the `play` function. Otherwise, you can set a timeout and `dispose` of the player and pitchshifter after the player is done playing the sample.
