### ISSUE TITLE
Tone.Player seconds

### ISSUE THREAD

**Issue by Grimones** [Tonejs/Tone.js#621]
Hi @tambien 

Sorry for posting this in github issues but it seems that forum is not really active and a lot of questions are answered for a long time.

So I'm writing a player with an ability to seek while playing and automatically play next song when current ends.

The first problem I've encountered is that `Tone.Player` doesn't have an option to check the current time while playing. Then I've found this issue https://github.com/Tonejs/Tone.js/issues/361

I've tried to make workaround with syncing player to `Tone.Transport` and it worked as expected by changing slider position with `Tone.Transport.seconds`. But unfortunately I can't get the event when the song has fully played. I'm using the typescript branch. Assigning an `onstop` callback on `Tone.Player` and calling `Tone.Transport.pause()` triggers `onstop` callback on player.

I've also investigated in using `Tone.ToneBuffersSource` but he has the same problem as `Tone.Player` not having an option to check the current time playing.

I've made a workaround using `Tone.Player.onstop` callback and checking the difference between `Tone.Player.buffer.duration` and `Tone.Transport.seconds`. But it has some deviation which depends on the performance of system and can be from -0.1 to -0.5. 

Also I have in mind another workaround by triggering a `Tone.Event` at the song duration time
Something like here https://github.com/Tonejs/Tone.js/blob/7236600182d336d6598f86d7d7afe8761e733774/Tone/source/OneShotSource.ts#L171-L176

Maybe there is an option to add back seconds to the `Tone.Player` or provide one more state value when pausing? Or I have missed something in docs

Thanks

**Comment by tambien** [comment]
@Grimones Unfortunately it's not possible to add seconds back because of the complexities of having variable playbackRates with the player combined with loopStart/End behavior. Once safari allows for playbackRate to be scheduled with another signal by connecting it (currently [not easily possible](chrisguttandin/standardized-audio-context#479) to create a shim for this behavior as well), i think there is another way where adding seconds is possible. 

Until then i am going to close this issue. I think the simplest solution to your issue is to either use `onstop` but since as you pointed out that's not using the Web Audio API's scheduling parameter, it is susceptible to loose timing. The other solution would be to try to compute the end time of your player manually by calculating the `startTime + duration / playbackRate` and scheduling the next buffer to start exactly at that time. 

Hope that helps! i will try to check back once safari gets around to fixing this behavior.
