### ISSUE TITLE
Feature Request: UserMedia - MediaRecorder integration

### ISSUE THREAD

**Issue by codeape2** [Tonejs/Tone.js#644]
See also: https://stackoverflow.com/questions/61172161/using-tone-js-with-mediarecorder

Use case: Record microphone input.

I am a tone.js noob so very likely that I have overlooked how to do this - but I cannot find anything in the API, examples or demos on how to record UserMedia.

**Comment by codeape2** [comment]
@tambien I have a related/follow-up question on Stack Overflow:

https://stackoverflow.com/questions/62011452/sample-accurate-punch-in-and-punch-out-recording-using-tone-js

**Comment by codeape2** [comment]
@sanderwapstra I saw your comment "... building a DAW for iPad where recording is important ..." on PR #655 . Perhaps you have some insights on https://stackoverflow.com/questions/62011452/sample-accurate-punch-in-and-punch-out-recording-using-tone-js ?

I am trying to build a sort of in-browser looping station.

**Comment by tambien** [comment]
MediaRecorder API does not provide sample-accurate scheduling. The start/pause/stop methods are not like the rest of the Web Audio API (since it's not part of the Web Audio API) and can't be timed precisely. 

My initial thought is maybe to record before and after your punch in/out and then trim it to the length that you'd like.
