### ISSUE TITLE
Sequence chaining weird behavior

### ISSUE THREAD

**Issue by oricordeau** [Tonejs/Tone.js#651]
Hi,

I have an issue with Sequence chaining. Please have a look at the following code :
https://jsfiddle.net/oricordeau/vkfqeu7g/97/

The code above starts a first sequence, and starts a second sequence when the first one ends. Here are some questions :

1. Why is there a silence between the two groups of 4 notes ? According to the code, seq1 and seq2 are supposed to be chained. Am I correct ?
2. If you click the 'Start' button, you'll get the time delta between seq1's last event and seq2's first event. This delta is supposed to be 0 second (this is the first question). Now, if you click the 'Run' button (on top left - in order to reinitialise everything, including reloading Tone.js) and then click the 'Start' button again, you'll get a different delta value. You can repeat that several time : each time the delta changes, which feels inconsistent. Is it normal ?

I'm not sure if it's a bug or an API misuse. If you think it's an API misuse on my side, please tell me how I can chain two Sequence objects. In the app I'm working on (https://acompas.org), the goal is to chain an introduction sequence (which does not loop) with another sequence which loops. If you see a more relevant way, please tell me.

Best regards and congratulation for that nice library you made ! Really.

**Comment by tambien** [comment]
The issue here seems to be in the difference between the Transport time and the AudioContext time. When scheduling things with Tone.Sequence, it is along the Transport's timeline. [There's a wiki article](https://github.com/Tonejs/Tone.js/wiki/TransportTime) i wrote a while back about it, hopefully it's still useful and relevant. 

Basically you're trying to schedule the next Sequence using the AudioContext time when you should be using the Transport's time value. This is going to lead to a large gap, and as the AudioContext time increases, that gap is going to keep getting larger since the AudioContext time just keeps counting up from page load. 

The approach i would suggest would be to either figure out ahead of time how long the first sequence is and chain the two like so:

```javascript
seq1.start(0)
const seq1Duration = "2m"
seq2.start(seq1Duration)
```

Or if you want to schedule it just-in-time inside the callback, use the Transport.seconds time to schedule the second sequence

```js
function seq1Callback(time){
  // this will start seq2 at the current position of the transport. 
 seq2.start(Transport.seconds)
}
```

**Comment by oricordeau** [comment]
Thanks for your reply ! I got it working using the first proposed option.
