### ISSUE TITLE
The transport time runs away by the time we can schedule

### ISSUE THREAD

**Issue by stephaneeybert** [Tonejs/Tone.js#657]
The transport time is running away, and after starting the transport, when a bit later on, the measures are scheduled, they are done so from a time of 0, when in fact the transport time is already past that, and away in the future.

I have done an [example](https://stackblitz.com/edit/angular-tone-xbxd3e) to illustrate the issue.

**Comment by tambien** [comment]
Unless i'm misunderstanding something, this is the desired behavior. 

This is what i'm seeing in your example: 
1) You start the transport. it starts counting up from 0. 
2) You later schedule events at regular intervals: 0, 1, 2, 3, 4, etc.
3) You observe that the output printed is 4, 5, 6, 7, etc. 

Because some time has passed since you started the transport, you are essentially scheduling the first few events _in the past_ which means they would not be triggered until you stop and restart the transport so that it passes those times again. 

If the expected behavior is that it starts counting up from 0, 1, 2, 3, etc, then i'd start the transport when you schedule all of the events. so that the transport is not already running past the notes that you'd like to hear. 

let me know if i'm misunderstanding your use case.

**Comment by stephaneeybert** [comment]
It is my misunderstanding then.

I had understood that when the transport starts, the timeline starts. And that when a note is to be scheduled in a given time, it is done from the transport time of the schedule call time.

My understanding was:

Schedule note call with specified time of 4 called at transport time 19
Current transport time
--------------------19------------------------------------------------------------------
Schedule note call with specified time of 4
------------------------23--------------------------------------------------------------
The note should be played at 23


To correct this, I had reset the transport when scheduling the note. This matches the understanding you above explained to me.

Thanks for your understanding :-)

**Comment by tambien** [comment]
So if i'm understanding you correctly, you'd like to schedule an event 4 second _from_ the current transport time. The syntax to be able to do that is '+4' which will add 4 seconds to the current Transport time. 

```js
Transport.start()
// ... some time passes // 
Transport.schedule(time => console.log(time), '+4')
```
