### ISSUE TITLE
Calling Tone.Clock.stop() also stops Tone.Transport (Firefox)

### ISSUE THREAD

**Issue by hiddedejong** [Tonejs/Tone.js#66]
When calling `stop` on a `Tone.Clock`, `Tone.Transport` stops ticking in Firefox (Developer Edition). `Tone.Transport` still thinks it's running.

It should only stop `Tone.Clock`, works as expected in Chrome and Safari.

This jsfiddle shows the issue.
http://jsfiddle.net/v18c4o0j/

**Comment by yukulele** [comment]
+1
another example: http://codepen.io/yukulele/pen/jPvbBR

**Comment by tambien** [comment]
@yukulele this seems like it's related to #78, no?

Also, again, it's unnecessary to create a new Tone.Oscillator and Tone.AmplitudeEnvelope on every keypress. These should be created at the top and reused. otherwise your application is going to end up eating a lot of memory and with enough key presses, run up against the performance capabilities of the browser and web audio.

**Comment by tambien** [comment]
Looks like this is fixed in `r6-dev`

http://jsfiddle.net/v18c4o0j/1/

The issue was probably some strange interaction between ScriptProcessorNodes.
