### ISSUE TITLE
Safari OfflineAudioContext NotSupportedError (also in examples)

### ISSUE THREAD

**Issue by sanderwapstra** [Tonejs/Tone.js#662]
In Safari on a desktop Mac I'm getting a `NotSupportedError: The operation is not supported.`

<img width="1031" alt="Screenshot 2020-04-30 at 10 32 32" src="https://user-images.githubusercontent.com/20322474/80689673-f6193f80-8acd-11ea-8f79-c97dc797d5a4.png">

It is also happening in the offline example:
https://tonejs.github.io/examples/offline.html

Is this a bug or is there a way to work around this? Thanks!

**Comment by tambien** [comment]
I'm unable to reproduce this error in Safari 13.1. What version are you on and what arguments are you passing to the OfflineAudioContext?

**Comment by sanderwapstra** [comment]
I have no idea what happened but my app and the Tone example are working again 🤷🏻‍♂️. Really sorry for taking your time!

**Comment by tambien** [comment]
that's alright! sometimes audio APIs do weird things

**Comment by sanderwapstra** [comment]
@tambien I have a little bit more information! It's weird but it happens when I have another website (Google Meet in this case, I was showing a demo of our app) in Chrome open that is using a mic/audio.

<img width="2032" alt="Screenshot 2020-05-07 at 15 59 19" src="https://user-images.githubusercontent.com/20322474/81304095-e759fc00-907c-11ea-83f7-f526d4090468.png">

<img width="2032" alt="Screenshot 2020-05-07 at 16 00 08" src="https://user-images.githubusercontent.com/20322474/81304097-e7f29280-907c-11ea-98c3-b1d4203279d0.png">

Real edge case of course!

**Comment by tambien** [comment]
Does the same issue happen if you try and open a vanilla Web Audio API (non-Tone.js) page in Safari under those circumstances? 

Given how you reproduce the error, i don't think there is much Tone.js could do about it. Seems like a Safari issue. But if we can pinpoint its cause, maybe there's a sensible error that could be thrown instead of just NotSupportedError. 

My only guess without being able to reproduce the issue is that i think all browsers have a hard limit on the number of simultaneous AudioContexts that can be open at once across the entire system, not just per-page. it's possible that Google Meet was using one of those AudioContexts which tipped your page over the edge.

**Comment by tambien** [comment]
I don't think there is anything that i can do about this, seems more like a Safari + Web Audio issue than anything Tone.js specific. Going to close, but open to ideas if anyone comes across a solution or a way to reproduce the issue more consistently.

**Comment by sanderwapstra** [comment]
Yes, I think you are right. I'm sorry that I haven't had more time to investigate further!
