### ISSUE TITLE
Freeverb seems to be broken

### ISSUE THREAD

**Issue by danijar** [Tonejs/Tone.js#663]
Example: https://jsfiddle.net/v8t3o57p/

```js
synth = new Tone.PolySynth(Tone.FMSynth)
// effect = new Tone.Gain()
effect = new Tone.Freeverb()
synth.chain(effect, Tone.Destination)
document.addEventListener('click', () => {
  synth.triggerAttackRelease('C4', 1)
})
```

```
Uncaught (in promise) SyntaxError: Unexpected token '==='
Promise.then (async)
cn @ AudioContext.ts:52
ln @ AudioContext.ts:52
pn @ AudioContext.ts:52
(anonymous) @ AudioContext.ts:52
ts @ AudioContext.ts:52
(anonymous) @ (index):38
```

**Comment by tambien** [comment]
I had converted to a new system for handling AudioWorkletProcessors where i could write everything in typescript and convert using `toString()` to a blob url. The issue is that the webpack's optimizer really mangles everything which caused this error. I've converted all of the worklets back to strings which should fix this issue, but unfortunately the worklets don't get any benefits of type checking now.
