### ISSUE TITLE
Provide guidelines on how to implement the examples ourselves

### ISSUE THREAD

**Issue by stephaneeybert** [Tonejs/Tone.js#677]
The [examples](https://tonejs.github.io/examples/polySynth.html) shows a nice piano but it does not tell us how to use it in our application. I have an Angular application and I've been unable to configure a nice sounding synth.

It would be nice to have a few guidelines on how to implement such examples.

**Comment by tambien** [comment]
I wish i had more time to provide more educational resources on synthesis. I will try to include more examples and principles where i can in the docs. I wouldn't be able to provide a definitive guideline since synthesis is just about what you think sounds good and there are no hard and fast rules to it. 

If you could pinpoint places in the docs or examples that could give more context, i could try addressing those specifically.

**Comment by stephaneeybert** [comment]
What I had in mind is having a simple pre-configured synth that offers an instrument, say a guitar or a piano.

I tried to use some [web audio fonts](https://github.com/surikov/webaudiofont) as it has a [typescript implementation](https://github.com/yw662/webaudiofont-ts) but failed to get it working.

Anyway, it's not a big deal if it does not exist.

Thanks anyway !
