### ISSUE TITLE
Setting latencyHint breaks Tone.Sequence

### ISSUE THREAD

**Issue by jhurliman** [Tonejs/Tone.js#679]
```js
await Tone.start()

// comment this line out to fix the sequence
Tone.setContext(new Tone.Context({ latencyHint: 'playback' }))

const seq = new Tone.Sequence((time, note) => {
  console.log(`callback(${time}, ${note})`)
}, [0, 1, 2, 4, 5, 6, 7], '8n').start()

Tone.Transport.start()
```

**Comment by tambien** [comment]
i just added a getter for the global singletons like Transport. Since Tone.Transport is tied to the context when you get the reference to `Tone.Transport` (or even `Tone.start()`) it no longer refers to the new context that you just set. and so the new context is never started. 

The updated way to make this work should be: 

```typescript
// comment this line out to fix the sequence
Tone.setContext(new Tone.Context({ latencyHint: 'playback' }))

// only invoke start after the new context is set to make sure that you're starting the new context
await Tone.start()

const seq = new Tone.Sequence((time, note) => {
  console.log(`callback(${time}, ${note})`)
}, [0, 1, 2, 4, 5, 6, 7], '8n').start()

// get the global Transport singleton
Tone.getTransport.start()
```

**Comment by tambien** [comment]
Should be fixed, going to close.

**Comment by jasonjsnell** [comment]
I ran into a similar issue trying to use Tone.Part after running Tone.setContext. The Part wouldn't start until I started accessing Transport via Tone.getTransport() rather than Tone.Transport.
