### ISSUE TITLE
"param must be an AudioParam" error on 14.7.3 with Firefox

### ISSUE THREAD

**Issue by KurtPreston** [Tonejs/Tone.js#681]
Firefox seems to handle the `AudioContext`'s `AudioListener` property different than other browsers. In particular, it doesn't seem to initialize some some orientation values Tone.js is attempting to read in, causing it to throw in `Listener.js`:

```
  30 | this.forwardY = new Param({
  31 |     context: this.context,
  32 |     param: this.context.rawContext.listener.forwardY,
> 33 | });
     | ^  34 | this.forwardZ = new Param({
  35 |     context: this.context,
  36 |     param: this.context.rawContext.listener.forwardZ,
```

The error is reproduced by this jsfiddle in Firefox:
https://jsfiddle.net/69r4szhy/

I create an `AudioContext`, apply `Tone.setContext`, but then Tone will error the first time I attempt to call `.toDestination()` with the error `param must be an AudioParam`

I'm on Firefox 77.0b7, but have noticed the same error in their mobile browser.

**Comment by tambien** [comment]
Thanks for the issue. This has to do with the way that you are creating and setting your own AudioContext since Tone.js is designed agains the Web Audio API specification on not browser-specific implementation. 

Tone.js uses [standardized-audio-context](https://github.com/chrisguttandin/standardized-audio-context/) to smooth out differences between browsers. One of the big differences is in the AudioListener which varies between browsers if they have forwardX/Y/Z as an AudioParam or just a number. 

Since you are setting your own AudioContext, it does not have the same polyfills to normalize the Web Audio API which is causing that error. I'd suggest that if want to create your own context which will work the same in all browsers, you should use standardized-audio-context or create a context using Tone.js' AudioContext wrapper which already wraps standardized-audio-context. To do this you could use `new Tone.Context()` in the line where you have `new AudioContext()`.

**Comment by KurtPreston** [comment]
Works great! Much appreciate the clear explanation and quick reply, thanks!
