### ISSUE TITLE
Playback stops when minimize or change tab

### ISSUE THREAD

**Issue by ZheTheBear** [Tonejs/Tone.js#687]
¡Hi all!
I've developed a simple html file with some js to add instruments with tonejs. The issue is when I change the tab or minimize the web browser the sound stops. I'm using some sequencers like the ones in the ui examples:

           var loop = new Tone.Sequence(

            function(time, col){
                var column = document.querySelector(`tone-step-sequencer[value="${num}"]`).currentColumn;
                if (isfirst[num] == 0 ) { //ARREGLITO
                    console.log(isfirst);
                    isfirst[num]=1;

                } else {
                    column.forEach(function(val, i){
                    if (val){
                        //slightly randomized velocities
                        //var vel = Math.random() * 0.5 + 0.5;
                    if (mchnorsynth==0){

                        synth.triggerAttackRelease(noteNames[i],"16n");    
                    } else {
                        synth.get(noteNames[i]).start(time, 0, "16n"); //"32n"
                    }
                        
                        //keys.get(noteNames[i]).start(time, 0, "4n"); //"32n"
                    }
                });
                //set the column on the correct draw frame

                }
                Tone.Draw.schedule(function(){
                document.querySelector(`tone-step-sequencer[value="${num}"]`).setAttribute("highlight", col);

                }, time); }, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], "16n").start(0);

¿Is this a problem of the sequencer or is it a problem of the audiocontext?

**Comment by tambien** [comment]
Most javascript callbacks are throttled when they happen in a background tab. Tone.js uses an WebWorker as it's main clock source since it doesn't get throttled in the same way as UI updates like requestAnimationFrame. Looks like maybe your code relies somewhere on a UI event to update state (which is the case with tone-step-sequencer if you're using the one from the examples page) . I think the issue may have to do with the first line in your callback where you get the current columnNumber which is only updated in the Tone.Draw callback (that happens on requestAnimationFrame which is not fired in the background tab). 

I'd suggest the best way to get your application to work in a background tab is to create a data structure separate from tone-step-sequencer which does not rely on updates that happen in the draw loop.

**Comment by ZheTheBear** [comment]
I was thinking on almost everything you said but I couldn't relate it that way. I'm going to try and make a Tone.transport scheduled sequencer instead of one relying on UI elements!
You saved my app, Thank you sincerely :)
