### ISSUE TITLE
iOS 11-12.1 Safari Error in Tone.js v14.7.2+ 

### ISSUE THREAD

**Issue by jasonfarrell** [Tonejs/Tone.js#695]
Hey Yotam! I found an issue with the `standardized-audio-context` dependency in the newer versions of Tone.

Tone seems to be breaking when bundled on iOS 11-12.1 — and I found people talking about it in the dependency's repo: https://github.com/chrisguttandin/standardized-audio-context/issues/950  — they were saying to try downgrading `standardized-audio-context`, but I'm not sure of the implications…

`TypeError: undefined is not an object (evaluating 'n.connect(r).connect')`

<img width="1470" alt="Screen Shot 2020-07-08 at 2 50 41 PM" src="https://user-images.githubusercontent.com/739781/86974467-3da1f480-c12b-11ea-8514-a8ea0b0e1fca.png">

See it in action on [Song Maker](https://musiclab.chromeexperiments.com/Song-Maker/)

**Comment by tambien** [comment]
Thanks for the issue Jason. This one is kinda tricky. My gut is to stick with the most recent versions of standardized-audio-context since it will have the best support of current and future browsers and i completely understand (and agree with) @chrisguttandin not supporting browsers older than 2 versions (though maybe 3 versions would be better in this case). 

Looking at [these usage stats](https://caniuse.com/usage-table), i'm wondering how many users are affected by sticking to the latest version of std-audio-context instead of trying to roll back and potentially losing some current or future browsers. 

Is this incompatibility reported by `Tone.supported()` or is the error thrown when Tone is loaded and initialized? because at least if the error is caught, then there would be a way to alert the user.

**Comment by jasonfarrell** [comment]
Thanks for the response @tambien — totally makes sense. 

Looks like the the error happens during the initialization (but I do see the Tone.js version logged out), but the web app code in the same webpack bundle remains unreachable.

**Comment by chrisguttandin** [comment]
Hi Jason, I do understand that dealing with outdated browsers is very frustrating. It was the reason why I started to build standardized-audio-context and wrote all the tests for it to make sure it really works in every browser.

On the other hand I also don't want it to be an ever growing code base. Therefore I usually delete the workarounds when the become unnecessary (after a while).

But I would really love to have a flexible system. Something which works like Babel and let's you define which browsers you want to support. If you're project only works with the Web MIDI API there is no need to ship all the workarounds for Safari. But if you're building something that appears to be very popular on iOS devices you may need them all.

Unfortunately I can't build such a system in my free time. But who knows, maybe there is some company interest in sponsoring such a flexible solution one day.

**Comment by TaoJinjin-Thomas** [comment]
@ jasonfarrell Have you found a solution to this? I am also trying to catch this error during the  initialization

**Comment by anxLiang** [comment]
Saddly, I am stuck in here too!

**Comment by tambien** [comment]
Since Tone.js relies on standardized-audio-context, only the last two versions of each browser are supported. I think the only workaround would be to load in a previous version of standardized-audio-context and use `setContext` to set that supported version.

**Comment by pesinasiller** [comment]
i had the same problem, downgrading to tone@13.8.18 worked in ios 12
