### ISSUE TITLE
Tone.context isn't set on Tone.setContext

### ISSUE THREAD

**Issue by maximedupre** [Tonejs/Tone.js#701]
As you can see in the fiddle, the reference to `Tone.context` isn't the right one after using `setContext`.

https://jsfiddle.net/1vq74ye3/23/

`getContext` works as expected, but I believe Tone uses `Tone.context` at some places in the internals which causes problems such as `ERROR DOMException: Failed to execute 'connect' on 'AudioNode': cannot connect to a destination belonging to a different audio context.`.

**Comment by tambien** [comment]
because `context` is just a constant, it won't update when the context is updated. if you use `setContext`, you can get the global context with `getContext`, similarly, you'll need to use `getTransport` and `getDestination` instead of `Transport` and `Destination`. I am thinking about deprecating the `context`, `Transport` and `Destination` variables in the next version in favor of the getter functions to avoid this exact issue. 

I believe doing so may also resolve #699

**Comment by maximedupre** [comment]
@tambien Please correct me If I'm wrong, but deprecating `context` would not be enough, unless by "deprecating" you also mean replacing all the `Tone.context` by `Tone.getContext()` in the lib internals. 

My code always use `Tone.getContext()` and never `Tone.context`, yet I still get this error: `ERROR DOMException: Failed to execute 'connect' on 'AudioNode': cannot connect to a destination belonging to a different audio context.`, which is why I'm implying there are some `Tone.context` lurking in the Tone codebase.

**Comment by tambien** [comment]
Can you provide an example? Are you using `Tone.Destination` anywhere?

**Comment by maximedupre** [comment]
Ah, yes, using `getDestination()` solves this problem. I made sure to refactor `context`, `Transport` and `Destination` to their respective getters. Thank you.
