### ISSUE TITLE
Adding a channel causes sampler to sound worse

### ISSUE THREAD

**Issue by vincent-bassoon** [Tonejs/Tone.js#704]
A sampler that is connected directly to the destination node sounds normal. However, when a channel with no volume or panning adjustments is added in between the sampler and the destination node, the audio quality suffers. The best way I can describe it is a tinnier and narrower sound.

Implemenetation: https://jsfiddle.net/tb9qhLjc/

**Comment by tambien** [comment]
this change is sound is likely because the stereo audio file is being turned into a mono file. Currently `Tone.Channel` is missing a `channelCount` property like all of the other uses of `Tone.Panner`. I'll update that shortly and then you'll have to explicitly set the `channelCount` to `2` like this

```javascript
const channel = new Tone.Channel({
  channelCount: 2
})
```

**Comment by vincent-bassoon** [comment]
This works perfectly for the other uses of Tone.Panner. Thanks for all your work and the prompt response!
