### ISSUE TITLE
Player._loopStart and Player._playbackRate and Player.sync() may cause problem

### ISSUE THREAD

**Issue by Francis-Tao-jinjin** [Tonejs/Tone.js#721]
It is v14 tonejs. Inside the player._start method, if the player is synced, then computedOffset will multiply by _playbackRate, if the computedOffset is _loopStart, then does it mean the _loopStart value should refer to the stretched sound instead of actual audioBuffer? If so, set loopStart shouldn't compare the value with buffer.duration if the player is synced.
<img width="759" alt="Screen Shot 2020-08-23 at 6 37 02 PM" src="https://user-images.githubusercontent.com/17539265/90976438-ae805d00-e56f-11ea-8cea-5d9fa6546ff3.png">

**Comment by tambien** [comment]
That's because of these lines: 

https://github.com/Tonejs/Tone.js/blob/826a51d5943e87776869522640b41feff7cf3daf/Tone/source/buffer/Player.ts#L198-L200

but now i'm not sure why that's in there. it does seem to cause some problems. I'll take another look and see if it needs to be in there, if not i'll remove it and update the tests.
