### ISSUE TITLE
Player synced to transport fades out when running `Transport.stop()` instead of stopping immediately

### ISSUE THREAD

**Issue by bduffany** [Tonejs/Tone.js#725]
# Repro
https://jsfiddle.net/e20t5vdx/1/

# Actual behavior
Clicking 'stop' stops the transport but the audio continues playing, even though it's synced to the transport. The audio fades out according to the `fadeOut` property set on the `Player`.

# Expected behavior
The `Player` stops immediately instead of fading out. I would expect `fadeOut` to be relative to the `Player`'s end time, not the time when the transport is stopped.

# More context
I'm implementing an online DAW where the user can fade clips in and out. It is a weird experience if they press "stop" and audio continues playing. As a workaround, I plan on temporarily setting the global volume to 0 then restoring it back to the previous value when pressing play.

**Comment by bduffany** [comment]
Hm I tried a workaround of setting the `Destination` volume value to 0, but this doesn't seem to work. https://jsfiddle.net/e20t5vdx/7/ Not sure what I'm missing.

**Comment by tambien** [comment]
Volume is in decibels, so 0db is no change. `Tone.Destination.volume.value = -Infinity` would silence it. 

i think what you're describing is the expected behavior. `fadeOut` applies the envelope after the player is stopped and `sync`ing to the transport will sync the start/stop methods. so i would expect then when the Transport is stopped, it would stop the Player and also apply the envelope. 

I agree it's not the expected behavior for a DAW, so some workarounds might be to silence the output as you mentioned, or possibly change the `fadeOut` to 0 before stopping the Transport.

**Comment by bduffany** [comment]
@tambien What are the use cases for `Transport`, other than a DAW-like scenario?

**Comment by tambien** [comment]
Transport is a general a way to synchronize many events against the same timeline. Unlike a DAW, in Tone.js it's possible to have sounds that are scheduled on the Transport and others run independently of the Transport. This is kind of a departure from a traditional DAW that only makes sound while the Transport is running. 

There's also other instruments/components that won't become totally silent when you synchronize them to the Transport such as any of the synths or Sampler. Those will similarly complete their decay before going silent after being triggered to stop by `Transport.stop()`, so the behavior of Player seems consistent.

**Comment by bduffany** [comment]
So, is `fadeOut` effectively meant to be the "Release" part of an ADSR envelope?

**Comment by tambien** [comment]
I consider both cases are essentially a "release" envelope. in the second case the release time just clamped to `buffer.duration - fadeOutTime`. 

Silencing the player immediately when 'stop' is called would remove the possibility of release envelopes that happen before the full duration of the buffer. So if you wanted to have it fade out without reaching the end of the sample, you'd have to add another component like a Gain to achieve that. 

Another alternative would be that the fade is applied so that it reaches gain=0 at "stopTime" when you call `stop(stopTime)`. This would mean that the fadeOut envelope could be 0 if you called `stop(now())` since there is no time to apply an envelope. I could see this being equally confusing since in order to hear the fadeOut, you'd need to schedule the stop time in the future like `stop(now() + fadeOutDuration)`. 

I think the current implementation can be a little confusing as you point out, but maybe more understandable than the last suggestion while still being able to achieve fadeOuts before the end of the sample.
