### ISSUE TITLE
unable to change monoSynth.filter.frequency.value

### ISSUE THREAD

**Issue by Francis-Tao-jinjin** [Tonejs/Tone.js#734]
![Screen Shot 2020-09-07 at 12 35 12 AM](https://user-images.githubusercontent.com/17539265/92330539-1a031800-f0a2-11ea-8fc5-b73632c8769a.png)
I have added the screenshot above so you can see what going on. Basically I want to draw the frequencyResponse curve of monoSynth.filter, so I call monoSynth.filter.getFrequencyResponse(). But it keep returning all zero array.

**Comment by Francis-Tao-jinjin** [comment]
This problem is pretty weird because I didn't touch monoSynth.filter.frequency at all, and it only happens when the filter is the member of monoSynth. If I create a new filter alone, it won't have such a problem.

**Comment by tambien** [comment]
`MonoSynth.filter.frequency` is being controlled by the FrequencyEnvelope which is connected to it. You'll see `MonoSynth.filter.frequency.overridden` is `true` indicating that setting its values has no effect. This also means that checking the filter's frequencyResponse is going always return 0 because the frequency value is also 0. 

Maybe a warning when a user sets a value that's overridden would be helpful in this case.

**Comment by Francis-Tao-jinjin** [comment]
Thank you
