### ISSUE TITLE
how to switch beetwen 2 part

### ISSUE THREAD

**Issue by sarahBuisson** [Tonejs/Tone.js#748]
I have various music in my game, that  play in loop
Since they play in loop, I have put each music  in tone.Part() class

My issue is, when I pass from a music to another, the previous part still play until the end simultaneously than the previous one.
How can I prevent it ?

My code=
```

const music1=new Part(...);
const music2=new Part(...);
music1.start(now());

...
music1.stop(now())
music2.start(now())

```

**Comment by tambien** [comment]
all of the event classes take the Transport-relative time as arguments. `now` returns the time along the AudioContext. 

Instead of `now` you could use no arguments (e.g. `music1.stop()`) to change it at the current Transport time. Or us an argument like `music1.stop(Transport.seconds)` to stop it at the current Transport time.
