### ISSUE TITLE
getTransportTime() in seconds?

### ISSUE THREAD

**Issue by georgealways** [Tonejs/Tone.js#75]
Hi There. Thank You For The Wonderful JavaScript Library.

Soooo, imagine one wants to move a playhead along a step sequencer in a smooth, linear fashion ... problem is the beat string that you get from `Transport.getTransportTime()` only has 16th note resolution. Desired result here is a 0.0-1.0 float that represents progress through a looping transport. 

Right now I'm just subtracting the currentTime from Transport's start time to get "elapsed seconds" then dividing by `Tone.Transport.notationToSeconds( '1m' )` ... but is there a better way? Seems like this would break too if you were doing a tempo ramp or something.

**Comment by HighOnDrive** [comment]
+1 Was considering the same thing myself, having a high resolution position indicator is a must and wondered why none of the demos featured one. Here is an example from another library: http://adamrenklint.com/bap/#sequences.

I take it that notes can have any duration and their callbacks will be fired. So if I have a score with some 128th notes in it the ability to schedule callbacks with a constant grid value of a 16th would not cut it. What is the preferred way to schedule a complex score with variable longer and shorter note durations?

**Comment by tambien** [comment]
@georgealways Good question. This kind of thing isn't currently possible with the API. There are two pretty simple changes/additions that i could make to accommodate it though: I think i will change `Transport.position` (formerly `Transport.getTransportTime()`) to return a floating point 16th note value, instead of truncating them as it currently does. for example it could return  `"1:0:1.234"` instead of just  `"1:0:1"`. It'd still be on you to parse that string subtract the `loopStart` time and divide by the difference between the `loopStart` and `loopEnd` to get a normalized value. 

I could also add `loopProgress` (or something to that nature) as a read-only attribute of the transport which would return a value between 0-1 to monitor the loop progress. Since it would be computing things on the tick level, it wouldn't have to go through ticks->beats->string->seconds as you'd have to if you were working with `Transport.position` and my above suggestion. 

I'll push my first suggestion to the dev branch soon, but I want to think a little more about the API for the second one so that it is consistent with a few other looping/sequencing additions i've got planned for r6. 

@HighOnDrive The TransportTime type is truncated to a 16th note, but the transport itself operates on a higher resolution tick. Currently a 32 note triplet (12 PPQ), but i'm thinking of raising that to 24 or 48 PPQ (which would accommodate up to 128th note triplet. or possibly exposing PPQ as a configurable attribute (related to #62).

**Comment by HighOnDrive** [comment]
Awesome, looking forward to the additions! Raising and exposing the PPQ and making it configurable is a must have for me.

**Comment by georgealways** [comment]
@tambien awesome. yea +1 to loopProgress, would be nice not to have to parse the "1:0:1" style string. Then I wonder if it might be nice to have something like that which wasn't "loop percentage" based ... fractional seconds or maybe fractional 16th notes elapsed since Transport.start() was called. 

keep killin' it yotam

**Comment by georgealways** [comment]
unabashed spam / feature creep: if you had a parameter like `Transport.getProgress( respectShuffle )` you'd be able to make moving images that were like ... "literally funky" :)

anywho, seems like the desired "units of progress" are:

- float 16th notes
- loop percentage
- "1:0:1" style string
- seconds

**Comment by tambien** [comment]
thanks for the feedback. If i'm going to do sixteenths, it seems consistent to do beats and bars as well. 

`Transport.sixteenths` returns the number of elapsed 16th notes (floats)
`Transport.beats` returns same but for quarter notes
`Transport.bars` returns same but for bars
`Transport.loopProgress` returns the loop progress 0-1. 

I've gotta think a little more about seconds since it complicates things slightly to deal with tempo shifting. The solution would be to have two clock sources: one in seconds and one in ticks. That way tempo changes would only affect the ticks clock and not the other one.
