### ISSUE TITLE
sound will strangely stop when playing multiple Part with a lot event on for dozens of seconds

### ISSUE THREAD

**Issue by Francis-Tao-jinjin** [Tonejs/Tone.js#755]
It is difficult for me to provide an absolute right sample code to produce this problem, but I will describe what happened in as much detail as possible.

I’m developing a daw like a program. In the program, after clicking the play button, an Tone.Part will be created for the clips on each track. All the notes in the region will be passing as the second parameter of Tone.Part.

what happing is if there are multiple Parts and each Part has quite a lot event to handle, the music will stop after playing about 50s, but the callback function pass to Part is still being called, transport.seconds still increasing, context.status is still 'running', but there is just no sound at all, stop the transport then start it again doesn't help. When this situations happen, I have tried to create a Tone.Oscillator and toDestination then start it, still no sound. Only if I stop the transport  and  wait for a few minutes and do nothing during this period, is it possible to make the sound be played again

![Screen Shot 2020-09-29 at 12 59 07 AM](https://user-images.githubusercontent.com/17539265/94464631-49182f80-01f1-11eb-8870-7843143fb060.png)

**Comment by Francis-Tao-jinjin** [comment]
As shown in the picture above, there are six tracks and each track has one region. So 6 Tone.Part will be created after clicking the play button. Each Part has many events on it. the midi I play is  https://bitmidi.com/uploads/37563.mid , But you can try anything you want.

**Comment by tambien** [comment]
Without a way to reproduce, my guess is that it's performance-related. i've seen this type of thing before, it usually happens when the AudioContext is overloaded and can no longer process all of the events that you give it. In these cases it will just go silent. It's easy enough to reproduce by creating a setInterval that keeps creating and starting an oscillator. Eventually all the browser goes silent. When they go silent depends on the browser and probably your computer as well. 

Some suggestions would be if you are playing AudioBuffers, to also schedule the 'stop' when you schedule the start, to keep the number of active sources to a minimum. Same with Oscillators. You can also try to reduce the number of events or render some things using the OfflineContext. Each track for example could be rendered using the OfflineContext and then just play back the resulting AudioBuffer where you can mix and adjust the gains and effects live. 

If you're able to create a minimal repro case, i can take a closer look

**Comment by Francis-Tao-jinjin** [comment]
Thanks for the quick reply, It looks like AudioContext overloaded could be the reason, maybe I should take some measures to limit voices

**Comment by tambien** [comment]
Going to close. If you're able to create a test-case please post it here or start a new more specific issue. 

thanks!
