### ISSUE TITLE
`Tone.Part` loop not always starting at first note in array

### ISSUE THREAD

**Issue by dsholes** [Tonejs/Tone.js#778]
First of all, thank you for all of your hard work on Tone.js, it's awesome!

I'm not sure if this is a bug or just my misunderstanding of intended behavior.

I'm playing around with looping a `Part`:
https://codepen.io/dsholes/pen/jOrKKNV

The `Part` plays as expected the during the first and second loop, but then it skips the first measure entirely on the third and fourth loop. Am I doing something wrong or is this a bug?

Also, a strange side note (maybe I should open a separate issue): when I use `Tone.Transport.stop()` and then follow it up with `Tone.start()` and `Tone.Transport.start()`, the timbre of the synth seems to change. Upon reloading the page, the timbre is back to normal. Should I be stopping the AudioContext in a different way? Why would the timbre change like this?

Thanks again!

**Comment by tambien** [comment]
Thanks for the great test case! I think this should be fixed now and i added a simple test (based on yours) to make sure that it doesn't creep back in in the future. 

The issue was caused by an implicit "stop" event which was scheduled when `part.loop = 4` was set, but then never removed when the `part.loopEnd` was extended beyond its previous loopEnd value. I removed the line which caused this issue and seems to be working fine now and all tests pass. 

You can find the fix at `tone@14.8.1`.

**Comment by dsholes** [comment]
Awesome, thanks a lot!
