### ISSUE TITLE
.keypress/.keydown creates a cacophony

### ISSUE THREAD

**Issue by spencerthayer** [Tonejs/Tone.js#78]
Here is a use case of a problem that isn't really the fault of Tone.JS but does however create a terrible sound when using Tone.JS in the most simple way. Both `keypress` or `keydown` consistently repeat the key command which activates `startSound();` so many times it becomes unbearable.

Do you have any suggests for getting around this issue?

```javascript
$(window).keydown(function(event) {
  console.log("KEYON:"+event.timeStamp);
  startSound();
});
$(window).keyup(function(event) {
  console.log("KEYOFF:"+event.timeStamp);
  stopSound();
});
```
```javascript
function startSound() {
    ran = Math.floor((Math.random()*2000)+1);
    osc = new Tone.Oscillator(ran, "triangle")
    env = new Tone.AmplitudeEnvelope();
        osc.connect(env);
        env.toMaster();
        osc.toMaster();
        osc.start();
        env.triggerAttack();
}
function stopSound() {
    env.triggerRelease();
    osc.stop();
}
```

**Comment by spencerthayer** [comment]
Here is a codepen of the problem I am having. http://codepen.io/spencerthayer/pen/pJZGVx

**Comment by lukephills** [comment]
Javascript keydown events keep firing if the key is held down. 
All you need to do is save the held down key and then check if it's being held. If it is, do nothing.
http://unixpapa.com/js/key.html

**Comment by tambien** [comment]
I'd also like to point out that you are creating a new oscillator and envelope on every keypress. You will quickly run up against the performance capabilities of your browser. 

You just need to create one oscillator and envelope and then call `env.triggerAttack` on the keypress. Since AmplitudeEnvelope will keep the `osc` from passing through, you also don't need to bother starting and stopping it on every press/release. 

I'll update the wiki article on building a [basic synth](https://github.com/Tonejs/Tone.js/wiki/BasicSynth) to include some info about tying it to a keypress which should clarify this situation for people in the future. 

```javascript
var osc = new Tone.Oscillator(ran, "triangle")
var env = new Tone.AmplitudeEnvelope();
osc.connect(env);
env.toMaster();
osc.start();

function startSound() {
    ran = Math.floor((Math.random()*2000)+1);
    osc.frequency.value = ran;
    env.triggerAttack();
}
function stopSound() {
    env.triggerRelease();
}
```

**Comment by spencerthayer** [comment]
@tambien your code example spits out a `TypeError: osc is undefined`.

**Comment by tambien** [comment]
I get a `ReferenceError` because `ran` was not defined before i used it.

This should fix it:
```javascript
var osc = new Tone.Oscillator({
  "type" : "triangle"
});
```

**Comment by iiimosley** [comment]
Setting a conditional statement utilizing `event.repeat` in your keydown event handler helps resolve this issue.

Maybe nest it like so:
`
$(window).keydown(function(event) {
  console.log("KEYON:"+event.timeStamp);
  if (!event.repeat) {
    startSound();
  }
});
`
