### ISSUE TITLE
Documentation / additional examples for key functionality needed

### ISSUE THREAD

**Issue by cdcv** [Tonejs/Tone.js#794]
There are a number of key functions of an Audio processing package that I would like to suggest need better documentation with a simple example.  A couple of code examples that might take only a few minutes to produce could save many hours of Tone.js user time.  Thanks!

Simplest suggestion: include a link to the wiki prominently featured in the beginning of the docs.  This would have saved me a lot of time.  Only discovered the Wiki well into trying to work things out without it.  It was mentioned in the original docs, but only at the bottom and primarily as related to contributing to the repo.  ;-) thx

Some of these issues we've been able to figure out, but it was pretty time-consuming.  Some of them appear to include incorrect documentation.  Some we still haven't figured out.  These are all things that seem like basis functionality / use cases of an audio library, and that even after substantial time reading the docs and even digging into the original repo code have been challenging.

*Master/Global Volume/Gain Control and Ramp
Have tried dozens of ways to get this to work, read the docs and examples.  Have tried gain nodes and other approaches.  Closest come so far:
Tone.Destination.volume.input.linearRampToValueAtTime(1, "+1");
This seems able to set the master gain immediately, rather than ramping it.  Also, it doesn't allow a time duration for the ramp as far as we can tell.  Guessing there is a simpler approach that doesn't dig so deeply into the object.  If there isn't, feature suggestion.

*Master/Global pause/resume
Figured out a solution to this one eventually:
    pauseAll() {
        Tone.context.rawContext.suspend();
    },
    resumeAll() {
        Tone.context.rawContext.resume();
    },
Also, this stops/starts the Tone.now() clock, which is helpful to know.  Is there a better way to do this?  Add this to docs?

*What is the notation that's being used for all the functions?
I kind of get what's going on with the parameter value notation, eg "C2", "+1", "1m", sometimes values and sometimes strings.  This is a non-standard notation.  Would be very helpful to have a help key/rosetta stone or even just some more examples to explain this.  Have spent lots of time on trial and error trying to work it out (after reading the docs on this).

*Rate/Time stretch without pitch shift
Is this possible?  Have tried combinations of changing the rate and the pitch, and tried grain.  Haven't been able to find a way to do this that doesn't substantially degrade sound quality.  In comparison, doing this with lower-level libraries works quite well and produces little noticeable distortion.   For example, in a React Native audio library implanted for web (so running in a browser), this command setRateAsync(rate, maintainPitch) can produce good quality changes in audio rate while maintaining pitch.  Since this works in a browser, presumably Tone.js could do something similar.  Not sure how it's implemented in React Native.

*Sound ramp volume to target level over x seconds
Still can't figure out how to do this.  Thx

*Callback for sound end
Is there a simple way to add a callback function for sound end or loop?

*AudioSprites
Is this possible in Tone.js without having to implement it, like in: https://github.com/goldfire/howler.js#documentation

Thanks for your help!

**Comment by tambien** [comment]
Hi @cdcv. i'll try to shed some light on these questions

> include a link to the wiki prominently featured in the beginning of the docs. This would have saved me a lot of time. 

I have been meaning to replace the wiki with better guides on the Tone.js website. as you note, the Wiki has some outdated info from previous versions, so i'm trying to find some time move it over to a new place. 

> *Master/Global Volume/Gain Control and Ramp 

I added a quick example to the documentation. The API uses `rampTo` which simplifies the Web Audio's `linearRampToValueAtTime` which is still included for those that want more control over the envelopes. 

```js
// ramp to silence over 2 seconds
Tone.Destination.volume.rampTo(-Infinity, 2);
// ramp up to +6db over 8 seconds
Tone.Destination.volume.rampTo(6, 8);
```

> *Master/Global pause/resume

I think the API you've found is probably the best way to do that for now. I will think about adding a 'suspend' method to Tone.Context, but Tone.Transport is a startable/stoppable clock which is meant to be used instead of suspending and resuming the context. 

> *What is the notation that's being used for all the functions?

I know i just said that the wiki is a little out of date and not necessarily reliable, but [this wiki page](https://github.com/Tonejs/Tone.js/wiki/Time) is the best overview of Time notations. 

> *Rate/Time stretch without pitch shift

Currently only Tone.GrainPlayer supports this. I'd suggest playing around with the parameters that are available to remove the artifacts. I couldn't easily find React's implementation, so not sure how they are achieving such better quality.

> *Sound ramp volume to target level over x seconds

Similar to the above example

```js
const osc = new Tone.Oscillator()
// ramp the oscillator volume to 
osc.volume.rampTo(-10, 4)
```

> *Callback for sound end

You could use `onstop` which is available from the Tone.js sources like Tone.Player and Tone.Oscillator. There is no loop callback, but if you're not adjusting the playback rate, it's possible to do it by aligning things to the transport. 

```js
// sync the player to Tone.Transport
const player = new Tone.Player(url).sync().start(0)
... wait for player to load
// schedule a repeated callback at the duration of the players buffer
Tone.Transport.scheduleRepeat(loopCallback, player.buffer.duration)
// start the Transport
```

> *AudioSprites

There's no built-in method for doing audio sprites. Though if you have defined sprite regions, you could schedule the player to start with an offset and play for a specific duration. 

Modifying Howler's example: 

```js
const player = new Tone.Player('sounds.mp3').toDestination()
// [offset, duration]
const sprites = {
  blast: [0, 3],
  laser: [4, 1],
  winner: [6, 5]
}
// ... wait for it to load
function play(name){
  const [offset, duration] = sprites[name]
  // start immediately with the given offset and duration
  player.start(Tone.now(), offset, duration)
}
// Shoot the laser!
play('laser')
```

I think it'd be somewhat cleaner to use separate audio files for each sound with something like `Tone.Players`, and i think with browsers supporting HTTP/2, there's not as much of an advantage of audio sprites these days since many requests can all be handled in parallel without the same amount of overhead of HTTP.
