### ISSUE TITLE
Setting playback rate on ToneBufferSource

### ISSUE THREAD

**Issue by pathime** [Tonejs/Tone.js#809]
Hi, this is less a bug and more an observation. If you create a ToneBufferSource node, then set its playbackRate value, and then fire start(), there is an audible delay before the playbackRate gets updated, i.e. you can hear that the starting rate is 1 and then it shifts to whatever you set it to. It's most obvious when you pass currentTime to start(), less so if it's triggered via a transport scheduled event.

```
const player = new Tone.ToneBufferSource({ url: myBuffer });
player.playbackRate.value = 2;
player.start(Tone.context.currentTime);
```

Setting playbackRate in the constructor solves this, and indeed feels neater. But it throws you a bit if you're expecting it to behave like the native BufferSourceNode.

**Comment by tambien** [comment]
All values internally are scheduled with a "lookAhead" applied to Tone.context.currentTime. internal `player.playbackRate.value = 2` is just doing `player.playbackRate.setValueAtTime(2, Tone.now())`. Since `Tone.now() === Tone.context.currentTime + Tone.context.lookAhead`, the value is going to be _after_ the currentTime. Which is why changes after the source is started. 

To fix this, you could use Tone.now() in `start` to schedule it at the same time, or you could schedule the value explicitly so that it's changed at the same time as the player is started by doing this: `player.playbackRate.setValueAtTime(2, Tone.context.currentTime)`

Let me know if that makes sense!

**Comment by pathime** [comment]
Ahh ok. Yes that makes sense. Thanks for explaining.
