### ISSUE TITLE
Interoperability with AudioContext API?

### ISSUE THREAD

**Issue by zackradisic** [Tonejs/Tone.js#811]
I'm using the AudioContext API's Biquad filter but its roll off is fixed to 12db/octave. Is [Tone.Filter](https://tonejs.github.io/docs/14.7.38/Filter) or (any of this project's audio nodes, for that matter) interoperable with the AudioContext API? Thanks.

**Comment by tambien** [comment]
Yes it uses the Web Audio Context API under the hood. Tone.Filter chains multiple BiquadFilterNodes in order to achieve rolloffs above 12db/octave. It should be interoperable with the raw Web Audio Context nodes as long as they are sharing the same underyling audio context which can be accessed from `Tone.getContext().rawContext` or set with `Tone.setContext()`. To connect native audio nodes to Tone.js, you can use `Tone.connect(yourNode, tonejsNode)`
