### ISSUE TITLE
scheduleRepeat with 1i does not match Tone.Transport.ticks

### ISSUE THREAD

**Issue by wuharvey** [Tonejs/Tone.js#824]
Ticks don't match: https://jsfiddle.net/quzehtkm/3/

Tick doesn't change on next call: https://jsfiddle.net/1fx68rt9/4/

**Comment by tambien** [comment]
For this, you'll wanna use `Tone.Transport.getTicksAtTime(time)` with the time passed into the callback. Like in [this example](https://jsfiddle.net/v7qnhk5f/5/). Tone.js timing is done by keeping a short look ahead time and scheduling values in advance. Callbacks like schedule/schedulRepeat are invoked before the time of the event which is why the ticks are still at 0.
