### ISSUE TITLE
Feature Request: fanIn(), fanOut(), Tone.Tuner, Tone.Equalizer, Tone.ChannelEQ, Tone.EnvelopeFollower

### ISSUE THREAD

**Issue by Hazmatron7** [Tonejs/Tone.js#834]
Hey I have some other cool ideas I would like to suggest to add for this library:

**1.** ```fanIn()``` and ```fanOut()```:
       

- basically its the same as ```ToneAudioNode.prototype.fan()``` but ```fanIn()``` does the opposite.
- Example: 
```javascript
/*
 *
 * Fan In:
 * 
 *  Node ---------->
 *                  \
 *                   -> Node
 *                  /        
 *  Node --------->
 * 
 * 
 * Fan Out:
 * 
 *           --------> Node   
 *          / 
 * Node --->
 *          \
 *           --------> Node
 * 
 */
```

**2.** ```"sawtoothUp"``` and ```"sawtoothDown"``` for ```Tone.LFO```:

- sawtooth on it's own, by default it goes up. To make it go down it easy, just invert the waveform.

**3.** ```Tone.Tuner```:

- It's a meter there where it gets frequencies from the waveform and detect notes from it.
- It should have at least a param called ```frequency``` to set a **A4** target reference to detect notes by. Default value should be 440Hz.
- It should be possible to implement using ```Tone.Analyser``` (or ```Tone.FFT```) and then calculate the frequencies to detect  notes and use an event or something to retrieve the results when it's detected a note.
- This could be very useful, especially when using midi notes.

**4.** ```Tone.Equalizer```:

- This could be very useful to use. I'm not sure exactly what type to suggest, either a graphic or parametric or something. But I'll leave that up to you to choose what's best.
- This is definitely achievable using BiquadFilters and or OnePoleFitler in series etc.

**5.** ```Tone.EnvelopeFollower```:

- It similar to ```Tone.AutoWah``` method  where it uses ```Tone.Follower``` as input and ```Tone.Scale``` as a output but with an AREnvelope and with sensitivity control.
- This could be useful for modulating an audio param from an other audio signal via envelope control

**6.** ```Tone.ChannelEQ```:
- This effect is used in Ableton Live. Here's an Image of it: 
![image](https://user-images.githubusercontent.com/48817592/106243460-602b6480-6259-11eb-900d-9be7b425b826.png)
- It's an effect with a 3 band gain controls and mid frequency and a toggle-able  80Hz highpass filter. Think of it as a 3 band equalizer.
- This sounds similar to ```Tone.EQ3``` but trust me it may have similar controls but the sound result is very different.
- This can be achieved with [this code](https://github.com/mosmeh/web-channel-eq/blob/master/src/eq.js) that I found. I've tested it on Firefox and I've compared with the real Ableton live 10 software and it works well and sounds great.

I hope you like some of these ideas. 
What do you think? 😄

**Comment by garrettmichaelgeorge** [comment]
I'd like to try implementing a few of these! I'm new to the project and am very interested in contributing. Let me know if I should go ahead and get to work, @tambien – if so, I'll jump in and update when I've made progress.

**Comment by tambien** [comment]
thanks @garrettmichaelgeorge and @Hazmatron7, i think of all these suggestions maybe the one that makes the most sense to start with @garrettmichaelgeorge would be `Tone.fanIn` or "sawtoothDown".

Regarding the Tuner, i think that pitch following is a pretty expansive with a lot of ways to do it, plus there's already [a few great libraries](https://www.npmjs.com/package/pitchfinder) out there to do that. EnvelopeFollower seems very similar to Tone.Follower, so i would prefer to extend the ability of Tone.Follower rather than introduce a new class, same goes for ChannelEQ, seems very similar to EQ3 that it would be better to modify EQ3 to match the behavior that you want rather than introduce a new class to do it. 

Equalizer would be useful, but not sure what is a useful API for doing that which is more useful than a user just chaining a bunch of BiquadFilters together themselves. 

@garrettmichaelgeorge please feel free to jump in if you're interested, you can share WIP Pull Requests if you'd like feedback sooner than later on your implementation

**Comment by Hazmatron7** [comment]
@tambien  @garrettmichaelgeorge  Aweswome Thanks guys. I had a good feeling this would be a great idea. 😄 👍

**Comment by garrettmichaelgeorge** [comment]
@tambien Sounds good. I've started working on `fanIn`. I'm looking at modeling it after `connect` and `disconnect`. Let me know if the following sounds like the right approach:

- Write 2 tests in `Tone/core/context/ToneAudioNode.test.ts`: one in `context("ToneAudioNode", ...)` and one in `context("connect native node", ...)`. Expect the destination's `numberOfInputs` to equal the correct number after calling the function.
- Tests fail
- Declare and implement `fanIn` as standalone function in `Tone/core/context/ToneAudioNode.ts`.
- Tests pass
- Export `fanIn`

If this sounds good, I'll make those tests pass and submit a pull request. Let me know if you'd prefer a different direction.

**Comment by garrettmichaelgeorge** [comment]
On second thought, I figured it would be easier to look at something concrete and went ahead and submitted a WIP PR (#856).
