### ISSUE TITLE
Crash on mobile mixer app

### ISSUE THREAD

**Issue by dolce-dog** [Tonejs/Tone.js#838]
Hello. First of all, this library is very easy to handle sound sources on javascript and is very useful.
I am very grateful to Tone.js.

I am creating a music player app that plays multiple sound sources at the same time.
A native app for SPA smartphones using Angular and Ionic.
The app crashes in certain cases.

When the user selects a song, the player screen starts and the sound source data saved in the mobile terminal is read.

```
for (let i = 0; i < this.trackArr.length; i++) {
  const file = //[Omitted] blob data generation
  this.solos[i] = new Tone.Solo().toDestination();
  this.sounds[i] = new Tone.Player({
    url: file,
    loop: false,
    autostart: false,
    onload: () => {
      //Code omitted. Checking the number loaded.
    }
  }).connect(this.solos[i]).sync().start(0);
}
```

Once everything is loaded, the Play Button will be enabled, and then when the user presses the button,
`Tone.Transport.start();`
Is executed and played simultaneously on the same time axis.

The player screen is open in a modal window and when the user presses the close button it does the following:
(There may be unnecessary instructions...)

```
Tone.Transport.stop();
setTimeout(async () => {
  this.sounds.forEach((sound) => {
    sound.dispose();
    sound.disconnect();
  });
  this.solos.forEach((solo) => {
    solo.dispose();
    solo.disconnect();
  });
  this.sounds = new Array();
  this.solos = new Array();
}, 500);
```

It doesn't really matter here ...
[setTimeout] is used because a crash will occur if you do not wait for a while after [Tone.Transport.stop()].

The Tone.js library is loaded when the app starts.

That's all for the overview of the app.
Think of it as a simple DAW app with only playback capabilities, with solos and mute.

I am suffering from a crash in two cases. The following is an event on a device with low specifications (GALAXY S5 / android v6.0.1), and the problem does not occur on a relatively new iPhone.

### No.1
**About the target sound source**
Number of files: 7
Time: 4 minutes 30 seconds
File size: 3.2MB / File

**Error**
It always crashes while loading.

### No.2
**About the target sound source**
Number of files: 10
Playing time: 3 minutes 29 seconds
File size: 818KB / File

**Error**
Launch the app, the first load is completed without any problems, and you can play it.
However, if you close the modal screen (player screen), select a song again, and start loading for the second time, it will crash in the middle like **No.1**.

The timing of each crash is the same.
I think that No. 1 can't be helped because the file size is large, but because **No.2** can be read once, I think that there is a solution .
By the way, if you reduce the number of **No.2** files from 10 to 3, a crash will occur after about 10 times starting. 

I would appreciate it if you could answer any hints.
Thank you very much.

**Comment by tambien** [comment]
My guess here is that the browser is running out of memory and it's not necessarily something related to Tone.js. 

Using the file sizes that you mentioned, a single 4:30 mp3 file would decode into approx 95MB of RAM. Here's my math:

```
270 (second audio file) * 44100 (common sample rate) * 2 (for stereo files) * 4 (bytes in a float 32 sample) = 95MB
```

7 files at this size would be a big load on a memory constrained devices and i guess in some cases cause the system to shut it down for taking up too much resources. It doesn't really matter that the files were relatively small when they were compressed because Web Audio Buffers are the raw PCM data of the audio file stored in a Float32Array.

In the past when i've tried to load big files like this, i would split them up into smaller chunks and only load them when necessary. I typically used the transport to create a callback before the file is needed and then load that group of files. 

I've seen a library which helps with this technique here: https://github.com/AnthumChris/fetch-stream-audio

It seems like the crash is not unique to Tone.js, but more of a Web Audio / javascript issue of loading large files into memory.

**Comment by liJie-wk** [comment]
> In the past when i've tried to load big files like this, i would split them up into smaller chunks and only load them when necessary. I typically used the transport to create a callback before the file is needed and then load that group of files.

**In the past when i've tried to load big files like this, i would split them up into smaller chunks and only load them when necessary. I typically used the transport to create a callback before the file is needed and then load that group of files.**
Pls, is there any example of application in Tone correspondence, I ran into this trouble
