### ISSUE TITLE
Filter rolloff only accepts numeric input

### ISSUE THREAD

**Issue by polyrhythmatic** [Tonejs/Tone.js#84]
Cannot use a string to set filter rolloff, string has to be evaluated to an integer.

**Comment by tambien** [comment]
Do you have an example of where we would need to use a string instead of a number? Currently the documentation defines it as a number. I'm not sure why it would be better to use a string instead.

**Comment by polyrhythmatic** [comment]
An example would be helpful!

Trying to use the value of an HTML dropdown

```HTML
<select id="hpr0"	value="=-24">
    <option selected="selected" value="-12">-12</option>
    <option value="-24">-24</option>
    <option value="-48">-48</option>
</select>
```

```javascript
	$("#hpr0").on("change", function(){
		cymbal["highPass0"].rolloff = parseInt($("#hpr0").val());
	});
```

I thought it might not be hard to add something that checks and sees if the string is "-12" "-24" or "-48" before rejecting it, and that it might vibe with the flexibility that score currently offers.

**Comment by tambien** [comment]
that's a pretty good use case, but it seems just as simple to have it parse the string before passing it to the filter rolloff (like you did) as it would be to do that internally. plus there's a sort of inconsistency of passing in a string and getting back a number. 

for example: 
```javascript
filter.rolloff = "-48";
filter.rolloff; //returns -48 (as a number)
```

I think this sort of thing makes more sense for the score because the `Time` typedef encompasses both strings and numbers. if rolloff takes a number _and_ a string, then the most consistent thing would be to allow all numeric values in Tone to also accept a string in the form of a number; i'm not quite convinced that this would be necessary or useful at this point.

**Comment by polyrhythmatic** [comment]
Good point!

I suppose since rolloff doesn't take continuous values it seemed to make sense it would parse strings since -12, -24 etc. seem to represent names more than numbers. Doesn't sound worth it.

**Comment by tambien** [comment]
that's true. so it would merit an enumeration type rather than a numeric value... 

thanks for the dialogue around API considerations.

I'm convinced. I will add this. plus it'd be so damn simple to accommodate your request.
