### ISSUE TITLE
set() has no time argument?

### ISSUE THREAD

**Issue by thely** [Tonejs/Tone.js#845]
I'm working on a project where the keys on the (computer) keyboard produce a bunch of different semi-random sounds. Currently, I have a large object where each letter is mapped to a bunch of changes that could happen to an FMSynth. Like this:

```js
let keys = {
  "a": {
    frequency: 1000,
    harmonicity: 5.3,
    modulationIndex: 100,
  },
  "b": {
    frequency: 487,
    harmonicity: 1.8,
    modulationIndex: 58.4
  },
  // ...etc
}
```

Optimally, what I'd like to be able to do is `synth.set(keys.a)`, and bulk-set all the parameters I need from the object at whatever value. But since `set` doesn't take a time argument, the result on keypress is a ~100ms jump from the synth's previous values to its new ones. I can reduce this by making the result of the key press happen 100ms in the future, but I'd like to make it mostly instantaneous if I can.

Is this the wrong way to use `set()`? Should I be individually setting all these values by looping through the object and doing `setValueAtTime()` on all of them? I was going about it this way because one constantly-changing synth seems more performant than 26 different ones.

Minimal example:
```js
window.addEventListener("keydown", (e) => {
  if ("a" <= e.key && e.key <= "z") {
    if (e.key in keys) {
      synth.set(keys[e.key]);
    } else {
      synth.frequency.value = 200;
    }
    synth.triggerAttack(synth.frequency.value, Tone.context.currentTime + 0.1);
  }
});

window.addEventListener("keyup", (e) => {
  if ("a" <= e.key && e.key <= "z") {
    synth.triggerRelease(Tone.context.currentTime);
  }
});

// use "keys" array above as an example
```

**Comment by tambien** [comment]
thanks @thely for the suggestion. I see a potential issue with the suggested API of including a time with `set` that could make it confusing to use. Not all object properties are schedule-able. For example someone could try and schedule a change of an oscillator type value at a given time like this `oscillator.set({ type :"square", frequency: 200}, "+5")` but since `type` isn't a signal property like `frequency`, it wouldn't change at the scheduled time, it'd change immediately. let me know if i'm overlooking something about your proposed API

I think in your case i would recommend just iterating over the values in your object and setting each of the parameters individually just like you suggested. That's going to give you much more precise results than using `currentTime`.
