### ISSUE TITLE
successive plays of simple tone sequence causes distortion that deriorates with each play if i stop playback before sequence completes

### ISSUE THREAD

**Issue by laurencefass** [Tonejs/Tone.js#850]
**Describe the bug**

A description of what the bug is. 
I've been having this issue in a more complex application so ive created a sandbox to demonstrate the issue.

**To Reproduce**
https://codesandbox.io/s/simple-tonejs-demo-czwvd?file=/src/App.js

1. Click synth button to start and stop a simple synth with effects. Repeat a few times. note it works fine.
2. Click poly button to start playback. Wait for it to complete. Click button to stop/start. repeat a few times. note it works fine.
3. interrupt the playback on the poly sequence by pressing stop before it ends. note how the playback deteriorates with each successive playback. Once it deteriorates, the clean synth signal also distorts on repeating 1.

**Expected behavior**
Playback should repeat without deteriorating.

**Additional context**
I am using React state to ensure that multiple instances of the synth are not being loaded so there is guaranteed only to be one poly and one synth in this component.

**Comment by tambien** [comment]
I can't find any Tone.js code in the link that you provided. Maybe it's the wrong version?

**Comment by laurencefass** [comment]
Hi i clicked on the link to make sure its correct.

extract from first few lines... can you see this?


```
import * as Tone from "tone";
....
const Synth = () => {
  let [synth, setSynth] = useState(new Tone.Synth().toDestination());

  useEffect(() => {
    const now = Tone.now();
    synth.triggerAttack("C3", now);
     return () => {
      synth.triggerRelease(now);
     }
  }, [synth]);

  return <h1>Synth playing</h1>;
}
```

**Comment by tambien** [comment]
oh there it is! sorry was totally boilerplate for me before

**Comment by tambien** [comment]
I'm playing around with it a bit now, i'm curious about the type of distortion you're referring to. When i click "stop/stop poly" quickly in succession, i hear overlapping notes from the end of the PolySynth phrase. It seems like there is a peaking distortion from the values being too high (the solution here is to reduce the volume of the PolySynth). That peaking distortion also happens when i click "start/stop synth". The distortion goes away if i let the PolySynth notes fully decay, then successive triggering doesn't seem to have any distortion. Is the behavior your hearing or is there a different distortion that you're referirng to?

**Comment by laurencefass** [comment]
thanks i understand i wasnt aware of peaking distortion but makes sense. 

if i may ask one more question before i close?

when i stop the poly component it calls

```
poly.triggerRelease(notes,  Tone.now());
```

but the sequence plays to conclusion. is there a way to stop the sequence at the point of closure without it playing through?

https://codesandbox.io/s/simple-tonejs-demo-czwvd?file=/src/App.js:842-881

**Comment by tambien** [comment]
Yeah the sounds directly from the synth are close to unity gain, so there's no head room and when you layer them on each other. they tend to peak if you don't reduce the gain before combining with other sounds. 

You're scheduling all of your synths ahead of in your forEach loop, the another way to handle this (so that you can handle cancelling) is to use Tone.Sequence or Tone.Part in combination with the Tone.Transport. If you don't want to mess with that, you can also add a Tone.Gain at the end of your synths and then silence the rest of the notes when you want them to stop. You'll need to create a new PolySynth object (which i believe React is doing for you already in the way that the objects are being instantiated) each time you need to play the notes, but it'd be minimal modifications to your existing code.
