### ISSUE TITLE
Delay time not reflecting transport bpm

### ISSUE THREAD

**Issue by drumnickydrum** [Tonejs/Tone.js#879]
My assumption is that delayTime of Tone.FeedbackDelay would be in sync with Tone.Transport.bpm .  Is this not the case?  The delayTime property itself works, but the timing is fixed and unrelated to transport bpm.

**Comment by tambien** [comment]
@drumnickydrum are you using [Tone.Transport.syncSignal](https://tonejs.github.io/docs/14.7.77/Transport.html#syncSignal)? 

Something like this should keep the delayTime in sync even when you adjust the transport.bpm

```js
const feedbackDelay = new Tone.FeedbackDelay('4n')
Tone.Transport.syncSignal(feedbackDelay.delayTime)
```

**Comment by drumnickydrum** [comment]
It doesn't seem to have an effect.  I have 5 delay channels and hooked them all up as you suggested.  Inspecting the Transport._synchedSignals shows them connected.  But no change to the timing of these delays.

```
_syncedSignals: Array(5)

0:
initial: 0.8
ratio: Gain {debug: false, _wasDisposed: false, context: Context, name: "Gain", _internalChannels: Array(0), …}
signal: Signal {debug: false, _wasDisposed: false, context: Context, name: "Signal", _internalChannels: Array(0), …}
__proto__: Object

1:
initial: 0.125
ratio: Gain {debug: false, _wasDisposed: false, context: Context, name: "Gain", _internalChannels: Array(0), …}
signal: Signal {debug: false, _wasDisposed: false, context: Context, name: "Signal", _internalChannels: Array(0), …}
__proto__: Object

// ...etc
```

**Comment by tambien** [comment]
I had a chance to play around with this a little more. The `delayTime` attribute is synced, but doesn't seem like it's necessarily synced in the desired way. When you call `syncSignal`, and adjust the transport bpm the delay time will be proportional to the bpm, but the desired behavior is likely to be to keep the delayTime inversely proportional to the bpm. 

For example if you set the delayTime to `0.5` and then double the bpm, the delayTime will be `1`, but in order to keep things locked at the same subdivision, the delayTime should be `0.25`. 

https://codesandbox.io/s/syncing-delaytime-oqmwr

I'm not sure of the solution here, i feel like this was the behavior previously, but not sure how many versions ago, will have to dig up some old code to see what changed.

**Comment by drumnickydrum** [comment]
The last meaningful commit to syncSignal I think is here: [implement syncSingnal](https://github.com/Tonejs/Tone.js/commit/ae2804fbc538b0e5cd2b75596b5de1dd7bba30a1#diff-4d3d60badd3649d824d8ac634cbb7401f201277c13ff430f948abf72516148c0)

from:
```
ratio = signal.getValueAtTime(now) / this.bpm.getValueAtTime(now);
```

to:
```
const bpm = this.bpm.getValueAtTime(now);
const computedFreq = 1 / (60 / bpm / this.PPQ);
ratio = signal.getValueAtTime(now) / computedFreq;
```

**Comment by yifanmai** [comment]
This is caused by a unit / dimensionality mismatch i.e. connecting a frequency signal to a time signal. Addressing this in #1050.

Also, sorry for the accidental commit message spam.
