### ISSUE TITLE
Tone.Meter doesn't output stereo value correctly

### ISSUE THREAD

**Issue by thcrack** [Tonejs/Tone.js#882]
Reproduce: 
- Go to [Mixer](https://tonejs.github.io/examples/mixer) example
- Solo Guitar 0
- Pan Guitar 0 all the way to left
- Play
- Observe that the right channel of the meter still pumps up, albeit lower than the left one.

Probably some changes underneath messed with the meter calculation?

**Comment by yifanmai** [comment]
This is a bug. When using a smoothed meter with multiple channels, cross-channel smoothing occurs because the [state used for smoothing](https://github.com/Tonejs/Tone.js/blob/364040cefe135801006004339d1c71089cff5461/Tone/component/analysis/Meter.ts#L47) is incorrectly shared across all channels. Opened #1018 for this.
