### ISSUE TITLE
Documentation for Draw and FFT very limited

### ISSUE THREAD

**Issue by cordial** [Tonejs/Tone.js#897]
**Describe the bug**

Firstly, this is a great library and I'm really sorry to raise this 'issue' here, but I'm very stuck. There is not really much in the way of documentation or examples with regard to the FFT and Draw objects, which I think I need to use to proceed with my task. I am trying to do the following and are very much struggling to get started - 

i) I have two oscillators continuously playing from Tone.js. They are 'playing' at frequency A and B out of left and right output respectively, to create a binaural sound. The difference between the two i will call the range. So for example, Osc1 might be 100hz, osc2 might be 104hz and the range is 4hz. These oscillators can be of any type allowed by tone.js (sawtooth, sine, triangle..)

ii) When the sound is playing i want to take the range frequency and attach it to two colours. So at the peak of the frequency colour A will be showing as a background colour and at the trough of the frequency colour B will be showing. Inbetween those times the colour will be morphing between the two i.e. at any time t the colour will be a representation of the Y position on the wave, that is reflective of the distance from 0. The overall effect being that over time the background colour of the area will fluctuate from colour A to colour B and back in sync with the range frequency wah wah noise. 

**To Reproduce**

https://stackoverflow.com/questions/67537305/draw-vizualizations-colour-changes-based-on-the-shape-of-an-oscillator-wave-in-a/67552707#67552707

I created a stackoverflow ticket, but although one poster gave me an idea of what objects I need, I cannot for the life of me work out how I would go about starting this using tone.js. From what he told me, I need to use the FFT (and maybe Draw?), but I don't really see how i can repeated get the FFT details over time. Should I be using a Loop object maybe (set at a very low time?). I don't really see how Draw fits into all this, is it effectively the same as a Loop object but is better synchronised to the overall audio context clock making it more suitable than loop? 

**Expected behavior**
Some examples of FFT and Draw would be very useful to get me going. 

**What I've tried**
As I mentioned I opened a ticket in stack overflow which got one reply (and also in the google groups which got none)

Also, looking through the existing tickets I came across one about FFT not being able to do real time (although it was from 2017) and suggested using the Medya library. Is this still the case?
https://github.com/Tonejs/Tone.js/issues/268

**Comment by tambien** [comment]
Hi @cordial. 

from what i gather, you want to sync the audio to visuals, so you might want to use requestAnimationFrame which will give you a callback on each draw frame. or a library like [p5.js](https://p5js.org/) which is designed for drawing using HTMLCanvasElement. 

Tone.FFT is used to analyze the incoming frequency and you can query it to get the value on each draw frame with something like this: 

```js
function loop(){
  requestAnimationFrame(loop);
  // fftValues is an array of decibel levels at each bin of the FFT
  const fftValues = fft.getValue();
}
loop()
```

FFT will give you the [spectrogram](https://musiclab.chromeexperiments.com/spectrogram/) of the incoming signal. Given that you are setting the frequency of `oscA` and `oscB` in your example, it'll probably be easier to _not_ have to analyze the spectrogram for the fundamental frequencies, but instead just use `oscA.frequency.value - oscB.frequency.value` which will give you what you're looking for (if i'm following along). 


So your range at each draw frame could be found like this: 

```js
function loop(){
  requestAnimationFrame(loop);
  const range = oscA.frequency.value - oscB.frequency.value;
  // use range to map color values
}
loop()
```

I'm not sure Tone.Draw is going to be useful in your scenario either since in your prompt you are not using the Tone.Transport. Tone.Draw syncs Tone.Transport times with the closest animation frame. But you could just use requestAnimationFrame directly.
