### ISSUE TITLE
Reloading returns undefined ampEnvelope Object

### ISSUE THREAD

**Issue by PhilippAubert** [Tonejs/Tone.js#901]
I did a little synth-app with React. 
My synth engine has a load/save-function embedded as modals. Patches can be stored as objects. Once loaded, they will setState the synth according to the saved object-values (such as oscillator, filter, amp and reverb). 

However, when I press load without a patch selected, I receive an error, amp.envelope.attack being undefined. 

I wonder why this is the case. 

[Link to my repo](https://github.com/PhilippAubert/capstone-digitalSynth)
[Link to Vercel](https://capstone-digital-synth-git-bugfix2-philippaubert.vercel.app/)

Thank you for taking a look 😃

**Comment by tambien** [comment]
Looks like a cool app, but this issue seems like it might be more of a React question than a Tone.js question. I don't know React well, so i'm not sure i can help you. If you're able to rewrite this issue with just vanilla Tone.js, i'm happy to take another look. 

In the most basic example without React `synth.envelope.attack` works just fine: 

```js
import { Synth } from "tone";
const synth = new Synth().toDestination();
console.log(synth.envelope.attack);
```

https://codesandbox.io/s/cranky-boyd-0syom?file=/src/index.ts
