### ISSUE TITLE
connecting player with pitchshift seems to play audio twice?

### ISSUE THREAD

**Issue by Earu** [Tonejs/Tone.js#905]
Hi, so I'm not quite sure if it's a bug or if it's because there's something I'm doing wrong but whenever I connect a `PitchShift` node to a `Player` node and then call `start` on the player node, it plays both the sound non pitched and the sound pitched at once. Any idea as to what's happening?

Here's my code:
```ts
// in class1.ts
	processAudio(player: Tone.Player): Tone.Player {
		const pitchShift: Tone.PitchShift = new Tone.PitchShift(100).toDestination();
		pitchShift.pitch = this.value;

		return player.connect(pitchShift);
	}

// in class2.ts
	async process(): Promise<void> {
		const buffer: Tone.ToneAudioBuffer = await this.resolveBuffer();

		let ply: Tone.Player = new Tone.Player(buffer);
		for (const modifier of this.chatsound.modifiers) {
			ply = modifier.processAudio(ply);
		}

		ply = ply.toDestination().start()
		await this.listen(ply);
	}
```

**Comment by thely** [comment]
It looks like both your Tone.Player and your Tone.PitchShift are both being sent to `toDestination()`. Remember that the Destination is your speakers. So instead of the chain you expect, which is `Player -> PitchShift -> Speakers`, you've got `Player -> Speakers` *and* `Player -> PitchShift -> Speakers`.

Just get rid of the toDestination() on `ply.toDestination()`.

**Comment by tambien** [comment]
@thely 🙏🏻
