### ISSUE TITLE
Sound Differences Between Firefox and Other Browsers

### ISSUE THREAD

**Issue by mjhasbach** [Tonejs/Tone.js#91]
Tone sounds similar in Chrome 44.0.2403.157 m and Edge 20.10240.16384.0, but rather harsh in Firefox 40.0.2. I assume this is due to differences in the implementation of `AudioContext`, but figured I would open this issue in case some sort of normalization could be achieved. The differences can be heard in [this CodePen](http://codepen.io/anon/pen/LVwYxW) from an unrelated issue.

**Comment by JackCA** [comment]
just discovering this as well.

Thought it might be related to https://github.com/Tonejs/Tone.js/issues/5.

@tambien are those separate tickets you mentioned in #5 (whether open or closed) queued somewhere?

**Comment by tambien** [comment]
I think what i'd like to do with this issue is break it up into specific places where FF differs from Chrome and where we could improve those. I discovered one place was Tone.Envelope and I took a few steps to try to narrow this gap. 

This way issues can be individually addressed and closed and maybe some could even be brought to the attention of the FF and Chrome devs to help normalize the Web Audio implementations across browsers.

I'm going to close this for now, but definitely having things sound good and similar across browsers is a big priority.
