### ISSUE TITLE
BiQuadFilter

### ISSUE THREAD

**Issue by firelex** [Tonejs/Tone.js#919]
Tone.BiQuadFilter({ frequency: 100, type: 'highpass'} ) works great.

Tone.BiQuadFilter({ options: {frequency: 100, type: 'highpass'} } ) doesn't.  It cuts out almost the entire frequency spectrum.

Shouldn't the result be the same?

**Comment by tambien** [comment]
`options` is not a key that can be passed into the constructor. `Tone.BiQuadFilter({ frequency: 100, type: 'highpass'} )` is the correct API. Likely the reason that it sounds very different is because the second BiquadFilter is just using the default paramteres which is `{type: 'lowpass', frequency: 440}`

[These are](https://tonejs.github.io/docs/14.7.77/interface/BiquadFilterOptions) the options that can be passed into the constructor. 

Hope that helps clarify!
