### ISSUE TITLE
Tone.Envelope not working?

### ISSUE THREAD

**Issue by supershwa** [Tonejs/Tone.js#925]
So it seems the Tone.Envelope is not working at all for me.  I just hear a "pop" sound (seems the oscillator isn't connected properly?)

The Tone.AmplitudeEnvelope works fine - just not Tone.Envelope.

Example:

```
testEnv = new Tone.AmplitudeEnvelope({
    attack: 0.11,
    decay: 0.21,
    sustain: 0.5,
    release: 1.2
}).toMaster();

testOsc = new Tone.Oscillator({
    partials: [3, 2, 1],
    type: "custom",
    frequency: "C#4",
    volume: -8,
}).connect(testEnv).start();

testEnv.triggerAttack();
```

^this works fine

But this:

```
testEnv = new Tone.Envelope({
    attack: 0.11,
    decay: 0.21,
    sustain: 0.5,
    release: 1.2
}).toMaster();

testOsc = new Tone.Oscillator({
    partials: [3, 2, 1],
    type: "custom",
    frequency: "C#4",
    volume: -8,
}).connect(testEnv).start();

testEnv.triggerAttack();

```
^ does not work.

Any ideas?

**Comment by tambien** [comment]
Thanks for the question. Tone.Envelope generates an envelope signal, but can't be used as an Amplitude Envelope directly like you're trying to do. For that you would need to take its generated signal and connect it to a Gain node (which is exactly what Tone.AmplitudeEnvelope does). 

You should probably be getting an error when you try to connect the oscillator to testEnv that it has no inputs since it only has a signal output.

**Comment by supershwa** [comment]
Ah, makes sense - thank you!
