### ISSUE TITLE
Tone buffer onload iOS

### ISSUE THREAD

**Issue by mjanssen** [Tonejs/Tone.js#96]
I'm using the Tone.Buffer.onload to inspect if two Tone.Player's are done loading. Everything seems to work fine on dekstop (Chrome) / Android. But on iOS & Safari, the .onload function is never called.

I've placed a button on start to initiate loading (to start with user input), but this does not solve the problem... Any help out there?

**Comment by tambien** [comment]
I just tried to recreate the issue and the loading worked fine for me on iOS. Maybe you could post a snippet somewhere so that i can take a look.

I did however discover a different bug which might be an issue here. It seems Apple has thrown a wrench at us with the iOS 9 update: previously a `touchstart` event would initiate the AudioContext, but now they want a `touchend`. Here's [a link](http://www.holovaty.com/writing/ios9-web-audio/). I tested it myself just now and that switch fixed the examples. 

Try switching `touchstart` to `touchend` in your application and see if that helps.

**Comment by mjanssen** [comment]
Hey, thanks for your reply :)

I've been working with the `bgmusic = new Tone.Player('../music/ambient-sound.mp3').toMaster();` code.
After that;

```
Tone.Buffer.onload = function ()
{
    audioBuffered();
};
```

Is set.

In the audioBuffered(), the preloader which is shown is hidden, but the Tone.Buffer.onload is never called.

I've now placed a 'starting button' around the code, so there has to be user interaction before loading.
This is now done with `$startButton.on('touchend', function () { *Code from above* })`. This does not seem to fix the problem, but I'm starting to think I'm doing something wrong... (since everything is working fine for you).
