### ISSUE TITLE
How much is too much when it comes to instruments (mainly oscillators)?

### ISSUE THREAD

**Issue by cordial** [Tonejs/Tone.js#976]
**Describe the bug**

I'm getting lots of crackling and pops when i play a lot of 'instruments'. I realise this might be a 'how long is a piece of string question/issue', but I'm looking to get a sense if we're 'taking the ****' with the number of things we're trying to play at the same time in the browser or if it should be fine and maybe I'm doing something incorrectly or whether there is any scope or process by which i can tune usage or memory or buffer or whatever?

**To Reproduce**
Here are the object types being used on this page -

"import { Clock, Player, Oscillator, Waveform } from "tone";"

I've got 14 oscillators playing client side in a react environment (next.js), using a Merge Object to channel some to the right ear and some to the left ear. you can edit the volume, frequency and base type (although we only really use 'sine') of each while the sounds are playing and/or if they're not. 

On top of that, I have 2 metronome sounds playing, using loaded files from firebase, which are playing using Clock objects (i.e. every 0.1 seconds it might play the sound once to create one metronome effect) 

And finally the wave form object, is used to monitor the shape of the wave and display colours in a box relating to where the wave is with at time X (using p5.js)

**Expected behavior**
I'd like it to play without the crackling etc. 

**What I've tried**
I read this - 
https://github.com/Tonejs/Tone.js/wiki/Performance

and the corresponding links it mentions but there is nothing specific enough for me to attempt for performance (assuming the issue is Tone.js itself). 

**Additional context**
This is for a project that needs to make binaural sounds. So there are 2 binaural sounds made (2 oscillators each for a total of 4), 2 dual binaural sounds (4 oscillators each for a total of 8) and 2 base sounds (2 more oscillators).

**Comment by marcelblum** [comment]
Can you give some more context on your target platform(s)? Some general suggestions:

- Throttle the framerate of your visualization animation. 40 fps is often fine enough. Typically `requestAnimationFrame` gives you 60 fps. Animations can definitely compete for cpu with audio processing.
- Try turning down the sampling rate of your audio context (but note: some platforms don't support custom sample rates). This can reduce cpu/ram load tremendously. Many platforms default to 48khz. A lot of times I've found when I encounter glitches from using a lot of effects, just turning it down to 44.1khz gets perfect playback without audible quality reduction. Sometimes you can get away with 32khz without noticeable degradation. To continue using `standardized-audio-context` with a new context in Tone with a custom sample rate use `Tone.setContext( new Tone.Context( new Tone.context.rawContext.constructor( {sampleRate: 32000} ) ) )`
- Depending on target platforms, you might be able to get away with bypassing `standardized-audio-context` which brings some of its own overhead; you can use a native context instead on Chrome for example `Tone.setContext( new Tone.Context( { context: new AudioContext( {sampleRate: 32000} ) } ) )`
- Did you try experimenting with `latencyHint` and `lookAhead`? If you don't need lowest latency these can make a difference especially on older hardware.

**Comment by cordial** [comment]
hey, thanks for the comments, very useful and various things I can try. 

Currently the target is web (and only latest browsers of none microsoft ones), but eventually i will be appifying the system using Ionic probably, so the app will be android and iOs. I presume phones are going to be able to do a fair amount less than running in a browser on a laptop?

**Comment by tambien** [comment]
Thanks @marcelblum those are all really good suggestions. 

@cordial i stay away from giving hard and fast rules for performance because it depends on so many factors such as what else is happening on that web page, what kind of computer, what else that computer is doing, and in some cases browser-specific implementations of components. 

I would add though in your case, 14 oscillators seems very doable even on mobile. One challenge with raw oscillators is managing gain and envelopes. Peaking will cause distortion if you don't lower the oscillators volume and especially with raw oscillators low frequencies may also cause distortion in some speakers and headphones. Also, stopping the oscillators can cause a click if no envelopes are applied because of the discontinuity. 

Once you've investigated both of those potential causes, i'd take a look at [this great article](https://web.dev/profiling-web-audio-apps-in-chrome/) on profiling to see if Web Audio is your performance bottleneck. 

Hope that helps! If you provide a small snippet of code on codesandbox or something similar, it may be helpful for debugging
