### ISSUE TITLE
Tone.Player current playback position/time

### ISSUE THREAD

**Issue by gherkins** [Tonejs/Tone.js#978]
**The feature you'd like**
Having the current playback position of a sample available as some property or event.
So that you could implement some kind of position indicator, with the waveform for example...

basically as in the HTMLMediaElement: timeupdate event    
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/timeupdate_event

**Any alternatives you've considered**
not really 🤷‍♀️

**Additional context**
I might have had something along that lines implemented in a project...
I think the `ScriptProcessorNode` is now being replaced by the `AudioWorklet` though.

    //basically just create some sort of tick, to update the position on 
    this.processor = this.context.createScriptProcessor(256);
        this.processor.connect(this.context.destination);
        this.processor.onaudioprocess = function () {
            if (self.playing) {
                self.updateTrackPositions();
            }
        }

set an internal timestamp on playback start per Player instance

    this.timer = this.context.currentTime;

then calculate the current playback position for the Player instance   
with an internal time per player and the `this.context.currentTime` property.

    let time = this.floatSecondsToMilliSeconds(this.context.currentTime - this.timer);
    let track_time = (((time * this.get('playbackRate')) % this.getLength()) + this.get('start'));
    let percent = ( track_time / this.get('duration')) * 100;

I guess you could also script that outside of Tone.js, but I thought that would be a cool feature to have ✨

**Comment by W-KE** [comment]
My assumption is supporting this would be extra hard as Tone.js supports Midi? If we only take audio buffers into account, we can calculate the position based on the sample position we are currently pulling. This is purely my guess.

**Comment by tambien** [comment]
I saw recently they are considering adding `position` to the AudioBufferSourceNode in the Web Audio spec, that would probably be the best solution overall for this situation. 

I'm reticent to add a ScriptProcessor or AudioWorklet to each Player object since it would be a lot of performance overhead for this feature. In the simple case with no `playbackRate` changes, it's fairly simple to track `Player.position` in your app, but my previous attempts to calculate position given start/stop scheduling and dynamic changes in `playbackRate` have introduced a lot of bugs. 

I'm going to close this for now since it's not something i'll add to the Player object anytime soon. But we might want to consider creating a PositionPlayer or something similar which includes a AudioWorklet component to track the playback position for people who need it.

**Comment by jackbach** [comment]
First at all, I really appreciate the work in this library.

I would like to share my interest on this feature, in case you ever wonder which features users would really love,

Thanks for the great work!
