### ISSUE TITLE
Pitch bend midi data apply to sampler instrument - Is this possible?

### ISSUE THREAD

**Issue by rhelsing** [Tonejs/Tone.js#983]
How would the pitch bend data from midi be applied to the sampler.

```javascript
track.notes.forEach((note) => {
  // track.pitchBends = [{ ticks: 343, value: 0.0234375 }, ...] - size 2560 values - normalized value 0.0-1.0 
  //Tone.js pitch shifter deals in semitones..
            //TODO: handle pitch bend and modwheel signals?
              sampler.triggerAttackRelease(
                  note.name,
                  note.duration*scaler,
                  note.time*scaler,
                  note.velocity
              );
          });
```

**Comment by tambien** [comment]
You can pass in frequency values (e.g. 440) instead of note names (e.g. A4) which will give you more fine grained control over pitch to get values between two semitones. Sampler doesn't support pitch curves though. For that, i would suggest using ToneBufferSource and scheduling the playbackRate so that you get the pitch bend that your looking for.

**Comment by rhelsing** [comment]
@tambien thank you. Is there an example somewhere showing the usage of pitch curves with a monosynth?

**Comment by rhelsing** [comment]
@tambien It seems like being able to ramp the pitch value on a PitchShift node might be a good way to accomplish this? Is this possible? or would it jump by discrete semitones? How might I go about allowing pitch shift to operate on cent values as opposed to semitones and allow it to be ramped?
