### ISSUE TITLE
web page crash (out of memory) once using a lot of mp3 files  v-tone@14.7.58

### ISSUE THREAD

**Issue by DaniilFawkes** [Tonejs/Tone.js#996]
Hi there
We are working on music studio (some browser analog of garage band / fl studio) at the moment and have a some kind of problem. page crashes due to out of memory (i guess problem is how audio buffer decoding mp3 files or smth)

on our home page we have a solid piano which uses 30 mp3 samples and works smooth even on very old phones with low ram 
but once its going to studio, where we have near 15 instruments (so its mean near 450 sound files) using of ram becoming near 4-5gb and even not all laptops ccan handle it... 
they way how we create players for our sequencer is next: 

1. connection of samples
`var samplesB = {
        'A0' : 'A0.mp3',
        'C1' : 'C1.mp3',
        'D#1' : 'Ds1.mp3',
        'F#1' : 'Fs1.mp3',
        'A1' : 'A1.mp3',
        'C2' : 'C2.mp3',
        'D#2' : 'Ds2.mp3',
        'F#2' : 'Fs2.mp3',
        'A2' : 'A2.mp3',
        'C3' : 'C3.mp3',
        'D#3' : 'Ds3.mp3',
        'F#3' : 'Fs3.mp3',
        'A3' : 'A3.mp3',
        'C4' : 'C4.mp3',
        'D#4' : 'Ds4.mp3',
        'F#4' : 'Fs4.mp3',
        'A4' : 'A4.mp3',
        'C5' : 'C5.mp3',
        'D#5' : 'Ds5.mp3',
        'F#5' : 'Fs5.mp3',
        'A5' : 'A5.mp3',
        'C6' : 'C6.mp3',
        'D#6' : 'Ds6.mp3',
        'F#6' : 'Fs6.mp3',
        'A6' : 'A6.mp3',
        'C7' : 'C7.mp3',
        'D#7' : 'Ds7.mp3',
        'F#7' : 'Fs7.mp3',
        'A7' : 'A7.mp3',
        'C8' : 'C8.mp3'
    };`

`const *instrument name* = new Tone.Sampler({
    urls: samplesS,
    baseUrl: "../wp-content/themes/generatepress_child/js-dev/samples/*instrument name*/",
    curve: "exponential",
    attack: 0,
    release: 4,
    sustain: 1,
    decay: 1,
    onload: () => {console.log('laoded');} 
}).toDestination();`
    
2. usage of instruments 
`if (pianoInputs.checked) {
        note = $(pianoInputs).attr('data-note');
        piano.triggerAttackRelease(note);
    }`

so the question is next why its using all the ram, coz in netvork tab all the files taking 100mb only, as i can understand its happening coz of decoding mp3 to ram or smth, so is any way to wrokaround this issue...
P.s also switch to latest version of ToneJS not possible at the moment, coz it was moved to TypeScript + we have a lot of customisation to let multitouch works on tablets and phones

**Comment by marcelblum** [comment]
Doesn't sound like a Tone issue, rather just a Web Audio issue given that it forces decoding all sounds to uncompressed 32-bit audio data. If you want the low latency of web audio, you have to submit to decoding everything to RAM with no option to go lower than 32-bit for now ([this should be improving eventually](https://github.com/WebAudio/web-audio-api/issues/2396)). I know that current desktop Chromium browsers have around a 4gb limit per tab, not sure about webkit or mobile variations.

Solutions:

- more managed lazy loading/decoding of audio files only as needed
- use a lower `sampleRate` audio context which consumes less memory (though not all browsers support non-default context sample rates)
- use mono sounds instead of stereo where practical
- use `<audio>`/`createMediaElementSource()` where practical to play long background tracks/sounds that don't require low latency, this avoids the decoding step entirely

The amount of RAM a soundfile will consume once decoded = `seconds * channels * current context sample rate * 4`. 100mb of mp3s could easily be 100 minutes of audio (or more) so in a 48kHz audio context that would be about 2.3gb of audio data. Downloading and decoding that all at once can certainly cause temporary spikes larger than that too because the process of converting the downloaded mp3 first to an `arrayBuffer` and then to the decoded audio uses even more temporary memory until it's garbage collected, so that's another reason delayed/lazy loading can help. Still, it's hard to see how you get from 2.3gb to "4-5gb" without a really heavy UI or huge dependency chain, so you may have more sleuthing to do to see where all the rest of that memory usage is coming from.

**Comment by tambien** [comment]
Thanks for jumping in @marcelblum 

yeah unfortunately there isn't anything that Tone.js can do about memory constrained browsers crashing when you load too much audio data. As @marcelblum mentioned, i would look into alternatives to loading all of the audio up front and consider more just-in-time loading.
